import { NEXUS_ALLOWED_GUILD_ID } from '../security/access';
const DISCORD_API = 'https://discord.com/api/v10';
type DiscordRequestOptions = { method?: string; body?: unknown; reason?: string };
export class DiscordApiError extends Error { status: number; details: unknown; constructor(status: number, details: unknown) { super(`Discord API request failed with status ${status}`); this.status = status; this.details = details; } }
function token() { const value = process.env.NEXUS_DISCORD_BOT_TOKEN; if (!value) throw new Error('Configuration error: NEXUS_DISCORD_BOT_TOKEN is not configured.'); return value; }
function assertGuild(guildId: string) { if (guildId !== NEXUS_ALLOWED_GUILD_ID) throw new Error('Authorization error: cross-guild Discord operation rejected.'); }
async function request(path: string, options: DiscordRequestOptions = {}) {
  const headers: Record<string, string> = { Authorization: `Bot ${token()}`, 'Content-Type': 'application/json', 'User-Agent': 'NEXUS/1.0 (+Discord AI operations)' };
  if (options.reason) headers['X-Audit-Log-Reason'] = encodeURIComponent(options.reason.slice(0, 512));
  const response = await fetch(`${DISCORD_API}${path}`, { method: options.method || 'GET', headers, body: options.body === undefined ? undefined : JSON.stringify(options.body), cache: 'no-store' });
  const text = await response.text(); let data: unknown = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!response.ok) throw new DiscordApiError(response.status, data); return data;
}
export async function guild(guildId: string) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}?with_counts=true`); }
export async function channels(guildId: string) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}/channels`); }
export async function roles(guildId: string) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}/roles`); }
export async function members(guildId: string, query = '', limit = 50) { assertGuild(guildId); const p = new URLSearchParams({ limit: String(Math.min(Math.max(limit, 1), 1000)) }); if (query) p.set('query', query); return request(`/guilds/${encodeURIComponent(guildId)}/members?${p}`); }
export async function member(guildId: string, userId: string) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}/members/${encodeURIComponent(userId)}`); }
export async function auditLog(guildId: string, limit = 50) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}/audit-logs?limit=${Math.min(Math.max(limit, 1), 100)}`); }
export async function messages(channelId: string, limit = 50) { return request(`/channels/${encodeURIComponent(channelId)}/messages?limit=${Math.min(Math.max(limit, 1), 100)}`); }
export async function channel(guildId: string, channelId: string) { assertGuild(guildId); const data: any = await request(`/channels/${encodeURIComponent(channelId)}`); if (String(data?.guild_id || '') !== guildId) throw new Error('Authorization error: target channel does not belong to the authorized guild.'); return data; }
export async function createChannel(guildId: string, input: { name: string; type?: number; parentId?: string; topic?: string; reason?: string }) { assertGuild(guildId); if (input.parentId) await channel(guildId, input.parentId); return request(`/guilds/${encodeURIComponent(guildId)}/channels`, { method: 'POST', reason: input.reason, body: { name: input.name, type: input.type ?? 0, parent_id: input.parentId, topic: input.topic } }); }
export async function editChannel(guildId: string, channelId: string, changes: Record<string, unknown>, reason?: string) { await channel(guildId, channelId); if (changes.parent_id) await channel(guildId, String(changes.parent_id)); return request(`/channels/${encodeURIComponent(channelId)}`, { method: 'PATCH', reason, body: changes }); }
export async function deleteChannel(guildId: string, channelId: string, reason?: string) { await channel(guildId, channelId); return request(`/channels/${encodeURIComponent(channelId)}`, { method: 'DELETE', reason }); }
export async function createRole(guildId: string, input: { name: string; color?: number; hoist?: boolean; mentionable?: boolean; permissions?: string; reason?: string }) { assertGuild(guildId); return request(`/guilds/${encodeURIComponent(guildId)}/roles`, { method: 'POST', reason: input.reason, body: { name: input.name, color: input.color, hoist: input.hoist, mentionable: input.mentionable, permissions: input.permissions } }); }
export async function editRole(guildId: string, roleId: string, changes: Record<string, unknown>, reason?: string) { assertGuild(guildId); const rs: any[] = await roles(guildId) as any[]; if (!rs.some((r) => String(r?.id) === roleId)) throw new Error('Authorization error: target role does not belong to the authorized guild.'); return request(`/guilds/${encodeURIComponent(guildId)}/roles/${encodeURIComponent(roleId)}`, { method: 'PATCH', reason, body: changes }); }
export async function assignRole(guildId: string, userId: string, roleId: string, reason?: string) { assertGuild(guildId); await member(guildId, userId); const rs: any[] = await roles(guildId) as any[]; if (!rs.some((r) => String(r?.id) === roleId)) throw new Error('Authorization error: target role does not belong to the authorized guild.'); return request(`/guilds/${encodeURIComponent(guildId)}/members/${encodeURIComponent(userId)}/roles/${encodeURIComponent(roleId)}`, { method: 'PUT', reason }); }
export async function timeoutMember(guildId: string, userId: string, durationSeconds: number, reason?: string) { assertGuild(guildId); await member(guildId, userId); const clamped = Math.min(Math.max(Math.floor(durationSeconds), 1), 2419200); return request(`/guilds/${encodeURIComponent(guildId)}/members/${encodeURIComponent(userId)}`, { method: 'PATCH', reason, body: { communication_disabled_until: new Date(Date.now() + clamped * 1000).toISOString() } }); }
export async function kickMember(guildId: string, userId: string, reason?: string) { assertGuild(guildId); await member(guildId, userId); return request(`/guilds/${encodeURIComponent(guildId)}/members/${encodeURIComponent(userId)}`, { method: 'DELETE', reason }); }
export async function banMember(guildId: string, userId: string, reason?: string) { assertGuild(guildId); await member(guildId, userId); return request(`/guilds/${encodeURIComponent(guildId)}/bans/${encodeURIComponent(userId)}`, { method: 'PUT', reason, body: { delete_message_seconds: 0 } }); }
export async function sendMessage(guildId: string, channelId: string, content: string, embeds?: unknown[], reason?: string) { await channel(guildId, channelId); if (!content && !embeds?.length) throw new Error('Validation error: message content or embeds are required.'); return request(`/channels/${encodeURIComponent(channelId)}/messages`, { method: 'POST', reason, body: { content: content.slice(0, 2000), embeds: embeds?.slice(0, 10) } }); }
export async function createEmbed(guildId: string, channelId: string, embed: unknown, reason?: string) { return sendMessage(guildId, channelId, '', [embed], reason); }
export async function webhooks(guildId: string, channelId: string) { await channel(guildId, channelId); return request(`/channels/${encodeURIComponent(channelId)}/webhooks`); }
export async function createWebhook(guildId: string, channelId: string, name: string, avatar?: string, reason?: string) { await channel(guildId, channelId); return request(`/channels/${encodeURIComponent(channelId)}/webhooks`, { method: 'POST', reason, body: { name: name.slice(0, 80), avatar } }); }
