"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Clock3, LogOut, Megaphone, Shield, Users } from "lucide-react";
import { signOut } from "next-auth/react";

type Content = { announcements?: any[]; calendar?: any[]; divisions?: any[] };
type User = { id: string; username: string; avatar?: string | null; nick?: string | null; access?: string; highestRole?: { name: string } | null; roles?: string[]; guildMember?: boolean };

export default function MemberDashboard() {
  const [user, setUser] = useState<User | null>(null);
  const [content, setContent] = useState<Content>({});
  const [loading, setLoading] = useState(true);
  const [member, setMember] = useState<boolean | null>(null);
  useEffect(() => { let cancelled=false; (async()=>{ try { const [me,data]=await Promise.all([fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()),fetch("/api/content",{cache:"no-store"}).then(r=>r.ok?r.json():{})]); if(!cancelled){setUser(me.authenticated?me.user:null);setMember(me.authenticated?me.guildMember !== false:false);setContent(data||{});} } catch {if(!cancelled){setUser(null);setMember(false)}} finally{if(!cancelled)setLoading(false)}})(); return()=>{cancelled=true}; },[]);
  const announcements=useMemo(()=> (content.announcements||[]).filter(x=>x.published).slice(0,5),[content]);
  const events=useMemo(()=> (content.calendar||[]).filter(x=>x.status!=="draft").slice(0,5),[content]);
  const divisions=useMemo(()=> (content.divisions||[]).filter(x=>x.status!=="inactive"),[content]);
  if(loading)return <Shell><div className="min-h-screen flex items-center justify-center"><Loading/></div></Shell>;
  if(!user)return <Shell><div className="min-h-screen flex items-center justify-center px-5"><div className="w-full max-w-lg rounded-3xl border border-border bg-panel p-10 text-center"><Users className="mx-auto text-golddim" size={36}/><h1 className="font-serif text-4xl font-bold mt-5">Member access</h1><p className="text-textdim mt-3">Authorize with Discord to continue to your profile.</p><a className="button button-primary inline-flex mt-7" href="/authorize">AUTHORIZE WITH DISCORD <ArrowRight size={13}/></a></div></div></Shell>;
  if(member===false)return <Shell><div className="min-h-screen flex items-center justify-center px-5"><div className="w-full max-w-xl rounded-3xl border border-border bg-panel p-8 sm:p-10 text-center"><div className="mx-auto h-20 w-20 rounded-full overflow-hidden border border-border bg-bg">{user.avatar?<img src={user.avatar} alt="Discord avatar" className="h-full w-full object-cover"/>:<Users className="mx-auto mt-6 text-golddim"/>}</div><p className="font-mono text-[9px] tracking-[2px] text-golddim uppercase mt-5">{user.username}</p><h1 className="font-serif text-3xl sm:text-4xl font-bold mt-2">You're invited.</h1><p className="text-textdim text-sm leading-6 mt-3">Your Discord account is authorized, but it isn't currently in the FBMRP server. Join our main server to receive server roles and member information.</p><a className="button button-primary inline-flex mt-7" href="https://discord.gg/fbmr">JOIN THE FBMRP SERVER <ArrowRight size={13}/></a><button onClick={()=>signOut({callbackUrl:"/"})} className="button button-ghost mt-3">SIGN OUT</button></div></div></Shell>;
  return <Shell><header className="border-b border-border bg-bg/90 sticky top-0 z-40"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-4 flex items-center justify-between gap-4"><div className="flex items-center gap-4 min-w-0"><a href="/" className="h-10 w-10 shrink-0 rounded-xl border border-border flex items-center justify-center"><ArrowLeft size={15}/></a><div className="min-w-0"><div className="font-mono text-[8px] tracking-[2px] text-golddim uppercase">FBMRP / MEMBER PORTAL</div><h1 className="font-serif text-xl sm:text-2xl font-bold truncate">Welcome, {user.nick||user.username}</h1></div></div><div className="flex gap-2"><a href="/quota" className="button button-primary hidden sm:inline-flex !py-2">STAFF QUOTA</a><a href="/staff" className="button button-ghost hidden sm:inline-flex !py-2"><Shield size={12}/> STAFF PANEL</a><button onClick={()=>signOut({callbackUrl:"/"})} className="h-9 px-3 rounded-lg border border-border font-mono text-[8px] uppercase flex items-center gap-2"><LogOut size={12}/> SIGN OUT</button></div></div></header>
  <div className="max-w-7xl mx-auto px-5 sm:px-8 py-8 sm:py-10"><section className="rounded-3xl border border-border bg-panel p-6 sm:p-10 mb-7"><div className="flex flex-col sm:flex-row items-center sm:items-start gap-6"><div className="h-28 w-28 sm:h-32 sm:w-32 shrink-0 rounded-full overflow-hidden border-2 border-golddim/50 bg-bg flex items-center justify-center">{user.avatar?<img src={user.avatar} alt="Discord avatar" className="h-full w-full object-cover"/>:<Users size={38} className="text-golddim"/>}</div><div className="text-center sm:text-left min-w-0"><div className="flex flex-wrap justify-center sm:justify-start gap-2"><span className="rounded-full border border-border bg-bg px-3 py-1 font-mono text-[8px] uppercase text-golddim">{user.access||"member"}</span><span className="rounded-full border border-border bg-bg px-3 py-1 font-mono text-[8px] uppercase text-textfaint">DISCORD VERIFIED</span></div><h2 className="font-serif text-3xl sm:text-5xl font-bold mt-4">{user.nick||user.username}</h2><p className="text-textdim mt-2">@{user.username}</p><p className="font-mono text-[9px] uppercase tracking-wider text-golddim mt-4">{user.highestRole?.name||"FBMRP MEMBER"}</p><div className="flex flex-wrap justify-center sm:justify-start gap-2 mt-4">{(user.roles||[]).map(r=><span key={r} className="rounded-lg border border-border bg-bg/60 px-2.5 py-1 font-mono text-[8px] text-textfaint">SERVER ROLE</span>)}</div></div></div></section>
  <section className="grid sm:grid-cols-3 gap-4 mb-8"><Stat icon={<Megaphone size={17}/>} label="Published updates" value={announcements.length}/><Stat icon={<CalendarDays size={17}/>} label="Upcoming operations" value={events.length}/><Stat icon={<Shield size={17}/>} label="Active divisions" value={divisions.length}/></section><section className="grid xl:grid-cols-[1.35fr_.65fr] gap-6"><Panel title="Latest intelligence" eyebrow="01 / ANNOUNCEMENTS" icon={<Megaphone size={16}/>}><div className="space-y-3">{announcements.map(a=><article key={a.id} className="rounded-xl border border-border bg-bg/60 p-5"><h3 className="font-serif text-xl font-bold">{a.title}</h3><p className="text-textdim text-sm leading-6 mt-2 whitespace-pre-wrap">{a.body}</p></article>)}{!announcements.length&&<Empty text="No published announcements yet."/>}</div></Panel><Panel title="Next operations" eyebrow="02 / CALENDAR" icon={<CalendarDays size={16}/>}><div className="space-y-3">{events.map(e=><article key={e.id} className="rounded-xl border border-border bg-bg/60 p-4"><h3 className="font-semibold">{e.title}</h3><div className="mt-3 space-y-2 font-mono text-[8px] uppercase text-textfaint"><div className="flex gap-2"><CalendarDays size={11}/>{e.date||"DATE TBA"}</div><div className="flex gap-2"><Clock3 size={11}/>{e.time||"TIME TBA"}</div></div></article>)}{!events.length&&<Empty text="No upcoming operations."/>}</div></Panel></section><Panel title="Your organization" eyebrow="03 / DIVISIONS" icon={<Users size={16}/>}><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{divisions.map(d=><article key={d.id||d.code} className="rounded-2xl border border-border bg-bg/60 p-5"><h3 className="font-serif text-xl font-bold">{d.name}</h3><p className="text-textdim text-sm leading-6 mt-2">{d.description||"Official FBMRP division."}</p></article>)}{!divisions.length&&<Empty text="No divisions published."/>}</div></Panel><div className="flex flex-wrap justify-center gap-3"><a href="/quota" className="button button-primary">STAFF QUOTA</a><a href="/staff" className="button button-ghost"><Shield size={12}/> STAFF PANEL</a></div></div></Shell>;
}
function Shell({children}:{children:ReactNode}){return <main className="min-h-screen bg-bg text-white">{children}</main>}; function Loading(){return <p className="font-mono text-[9px] uppercase tracking-[2px] text-textfaint">Loading live member data…</p>}; function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-border bg-panel p-5"><div className="h-9 w-9 rounded-lg border border-border flex items-center justify-center text-golddim">{icon}</div><div className="font-serif text-3xl font-bold mt-5">{value}</div><div className="font-mono text-[8px] uppercase tracking-wider text-textfaint mt-1">{label}</div></div>}; function Panel({title,eyebrow,icon,children}:{title:string;eyebrow:string;icon:ReactNode;children:ReactNode}){return <section className="rounded-2xl border border-border bg-panel p-5 sm:p-6 mb-6"><div className="flex items-center justify-between mb-5"><div><div className="font-mono text-[8px] tracking-[2px] text-golddim uppercase">{eyebrow}</div><h2 className="font-serif text-2xl font-bold mt-1">{title}</h2></div><div className="h-9 w-9 rounded-lg border border-border flex items-center justify-center text-golddim">{icon}</div></div>{children}</section>}; function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-border p-8 text-center text-textfaint text-sm">{text}</div>}
