// @ts-ignore Generated by @opennextjs/cloudflare at build time.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(_event: ScheduledController, env: Record<string, string>, ctx: ExecutionContext) {
    const secret = env.CRON_SECRET;
    if (!secret) throw new Error("CRON_SECRET is not configured");

    const request = new Request("https://qusm-site.internal/api/cron/cleanup-developer-media", {
      method: "GET",
      headers: { authorization: `Bearer ${secret}` },
    });

    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`Developer media cleanup failed with HTTP ${response.status}`);
    }
  },
};
