"use client";
import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Megaphone, Users, Shield, ScrollText, LogOut, Plus, Trash2, Landmark, BadgeCheck, Rss, Image as ImageIcon, Settings, Save, CalendarDays, Edit3, Send, Search, CheckCircle2, AlertCircle, GitBranch } from "lucide-react";
import { signOut } from "next-auth/react";

type Field = { key: string; label: string; type?: "text" | "textarea" | "url" | "date" | "time" | "number" | "select"; options?: string[] };
type Section = { id: string; label: string; icon: any; permission: string; fields: Field[]; private?: boolean };

const cocFields: Field[] = [
  { key: "title", label: "Position / Level" }, { key: "name", label: "Assigned Person" },
  { key: "description", label: "Description", type: "textarea" }, { key: "active", label: "Status", type: "select", options: ["active", "inactive"] }, { key: "order", label: "Display order", type: "number" },
];

const SECTIONS: Section[] = [
  { id: "org", label: "Site", icon: Settings, permission: "site:edit", fields: [
    { key: "name", label: "Short name" }, { key: "fullName", label: "Full name" }, { key: "owner", label: "Owner" }, { key: "coOwner", label: "Co-owner" },
    { key: "heroEyebrow", label: "Hero eyebrow" }, { key: "heroTitle", label: "Hero title" }, { key: "heroDescription", label: "Hero description", type: "textarea" },
    { key: "recruitmentUrl", label: "Recruitment URL", type: "url" }, { key: "footerText", label: "Footer command text" }, { key: "status", label: "Status", type: "select", options: ["active", "maintenance", "closed"] },
  ]},
  { id: "announcements", label: "Announcements", icon: Megaphone, permission: "announcements:manage", fields: [{ key: "title", label: "Title" }, { key: "body", label: "Announcement", type: "textarea" }, { key: "published", label: "Status", type: "select", options: ["draft", "published"] }] },
  { id: "calendar", label: "Calendar", icon: CalendarDays, permission: "calendar:manage", fields: [{ key: "title", label: "Event title" }, { key: "date", label: "Date", type: "date" }, { key: "time", label: "Time", type: "time" }, { key: "location", label: "Location" }, { key: "description", label: "Description", type: "textarea" }, { key: "status", label: "Status", type: "select", options: ["draft", "published"] }] },
  { id: "cocLeadership", label: "Leadership CoC", icon: GitBranch, permission: "site:edit", fields: cocFields },
  { id: "cocStaff", label: "Staff CoC", icon: GitBranch, permission: "site:edit", fields: cocFields },
  { id: "cocRoleplay", label: "Roleplay CoC", icon: GitBranch, permission: "site:edit", fields: cocFields },
  { id: "leadership", label: "Command", icon: Users, permission: "leadership:edit", fields: [{ key: "title", label: "Position" }, { key: "name", label: "Name" }, { key: "discordId", label: "Discord ID" }, { key: "division", label: "Division" }, { key: "rank", label: "Rank" }, { key: "description", label: "Description", type: "textarea" }, { key: "active", label: "Status", type: "select", options: ["active", "inactive"] }, { key: "order", label: "Display order", type: "number" }] },
  { id: "divisions", label: "Divisions", icon: Shield, permission: "divisions:edit", fields: [{ key: "code", label: "Code" }, { key: "name", label: "Division name" }, { key: "description", label: "Description", type: "textarea" }, { key: "status", label: "Status", type: "select", options: ["active", "inactive", "temporary"] }, { key: "leadership", label: "Leadership" }, { key: "logoUrl", label: "Logo URL", type: "url" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "rules", label: "Rules / CoC", icon: ScrollText, permission: "site:edit", fields: [{ key: "title", label: "Rule title" }, { key: "category", label: "Category" }, { key: "body", label: "Rule", type: "textarea" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "government", label: "Government", icon: Landmark, permission: "site:edit", fields: [{ key: "name", label: "Name" }, { key: "role", label: "Role" }, { key: "department", label: "Department" }, { key: "description", label: "Description", type: "textarea" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "ranks", label: "Ranks", icon: BadgeCheck, permission: "site:edit", fields: [{ key: "name", label: "Rank" }, { key: "level", label: "Level" }, { key: "description", label: "Description", type: "textarea" }, { key: "insigniaUrl", label: "Insignia URL", type: "url" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "news", label: "News", icon: Rss, permission: "site:edit", fields: [{ key: "title", label: "Headline" }, { key: "excerpt", label: "Summary", type: "textarea" }, { key: "body", label: "Article", type: "textarea" }, { key: "date", label: "Date", type: "date" }, { key: "imageUrl", label: "Image URL", type: "url" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "media", label: "Media", icon: ImageIcon, permission: "media:manage", fields: [{ key: "title", label: "Title" }, { key: "caption", label: "Caption", type: "textarea" }, { key: "imageUrl", label: "Image URL", type: "url" }, { key: "videoUrl", label: "Video URL", type: "url" }, { key: "category", label: "Category" }, { key: "order", label: "Display order", type: "number" }] },
  { id: "applications", label: "Applications", icon: Users, permission: "applications:manage", private: true, fields: [{ key: "name", label: "Applicant" }, { key: "type", label: "Application type" }, { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] }, { key: "notes", label: "Staff notes", type: "textarea" }] },
];

const uid = () => crypto.randomUUID();
const blank = (fields: Field[]) => fields.reduce((o: any, f) => ({ ...o, [f.key]: f.type === "select" ? (f.options?.[0] || "") : f.type === "number" ? 0 : f.key === "active" ? "active" : "" }), { id: `local-${uid()}` });

export default function AdminClient({ initialContent, email, access, permissions }: { initialContent: any; email: string; access: string; permissions: string[] }) {
  const [content, setContent] = useState<any>(initialContent || {});
  const [active, setActive] = useState("org");
  const [editing, setEditing] = useState<number | null>(null);
  const [query, setQuery] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const allowed = (p: string) => permissions.includes(p) || permissions.includes("admin:all");
  const section = SECTIONS.find(s => s.id === active)!;
  const items = Array.isArray(content[active]) ? content[active] : [];
  const filtered = useMemo(() => items.filter((x: any) => !query || JSON.stringify(x).toLowerCase().includes(query.toLowerCase())), [items, query]);

  useEffect(() => { const s = new URLSearchParams(location.search).get("section"); if (s && SECTIONS.some(x => x.id === s) && allowed(SECTIONS.find(x => x.id === s)!.permission)) setActive(s); }, []);

  const save = async () => {
    setSaving(true); setError(""); setSaved(false);
    try {
      const response = await fetch("/api/content", { method: "PUT", headers: { "Content-Type": "application/json", "x-content-section": active }, body: JSON.stringify({ [active]: content[active] }) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || `Save failed (${response.status})`);
      setSaved(true); setTimeout(() => setSaved(false), 2500);
    } catch (e: any) { setError(e?.message || "Save failed"); }
    finally { setSaving(false); }
  };

  const add = () => { setContent((c: any) => ({ ...c, [active]: [...(Array.isArray(c[active]) ? c[active] : []), blank(section.fields)] })); setEditing(items.length); };
  const remove = async (index: number) => { const item = items[index]; if (!item) return; if (!confirm("Delete this record?")) return; setContent((c: any) => ({ ...c, [active]: items.filter((_: any, i: number) => i !== index) })); setEditing(null); };
  const updateItem = (index: number, key: string, value: any) => setContent((c: any) => ({ ...c, [active]: items.map((x: any, i: number) => i === index ? { ...x, [key]: value } : x) }));
  const publish = async (index: number) => { const item = items[index]; if (!item || active !== "announcements") return; setSaving(true); setError(""); try { const r = await fetch("/api/announcements", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...item, published: true }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw Error(d.error || "Publish failed"); setContent((c: any) => ({ ...c, announcements: items.map((x: any, i: number) => i === index ? d : x) })); setSaved(true); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };

  return <div className="min-h-screen bg-bg text-white pb-28">
    <header className="sticky top-0 z-30 border-b border-border bg-bg/95 backdrop-blur px-5 sm:px-10 py-5 flex justify-between items-center"><div><div className="font-mono text-[10px] tracking-[2px] text-golddim uppercase">FBMRP Administration</div><h1 className="font-serif text-xl font-bold">Staff Management</h1><div className="font-mono text-[9px] text-textfaint uppercase mt-1">{access} · {permissions.length} permissions</div></div><button onClick={() => signOut({ callbackUrl: "/" })} className="font-mono text-[10px] uppercase border border-border px-3 py-2 flex gap-2 items-center"><LogOut size={12}/> Sign out</button></header>
    <main className="px-5 sm:px-10 py-8 max-w-7xl mx-auto"><div className="mb-7 flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="font-mono text-[10px] text-textfaint">SIGNED IN · {email}</span><h2 className="font-serif text-4xl font-bold mt-2">Content Command</h2><p className="text-textdim text-sm mt-2">Every public section is backed by the same persistent content record. Staff changes are written to the database, then the website reads that same state.</p></div><div className="relative"><Search size={14} className="absolute left-3 top-3 text-textfaint"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search records…" className="bg-panel border border-border rounded-lg pl-9 pr-3 py-2.5 text-sm outline-none focus:border-golddim w-full md:w-64"/></div></div>
      {error && <div className="mb-5 flex items-center gap-2 border border-red-500/40 bg-red-500/10 text-red-200 rounded-xl p-3 text-sm"><AlertCircle size={15}/>{error}</div>}{saved && <div className="mb-5 flex items-center gap-2 border border-green-500/30 bg-green-500/10 text-green-200 rounded-xl p-3 text-sm"><CheckCircle2 size={15}/> Changes saved.</div>}
      <AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>{active === "org" ? <SettingsEditor value={content.org || {}} fields={section.fields} setValue={(v) => setContent((c: any) => ({ ...c, org: v }))} /> : <CollectionEditor section={section} items={filtered} allItems={items} editing={editing} setEditing={setEditing} update={updateItem} add={add} remove={remove} publish={publish} />}</motion.div></AnimatePresence>
    </main>
    <nav className="fixed bottom-4 left-1/2 -translate-x-1/2 max-w-[96vw] overflow-x-auto rounded-2xl border border-border bg-panel/95 backdrop-blur px-2 py-2 flex gap-1 z-40">{SECTIONS.filter(s => allowed(s.permission)).map(s => { const I = s.icon; return <button key={s.id} onClick={() => { setActive(s.id); setEditing(null); setQuery(""); setError(""); history.replaceState(null, "", `/admin?section=${s.id}`); }} className={`px-3 py-2 rounded-xl text-[9px] font-mono uppercase whitespace-nowrap ${active === s.id ? "bg-gold text-black" : "text-textdim hover:text-white"}`}><I size={13} className="mx-auto mb-1"/>{s.label}</button>; })}</nav>
    {allowed(section.permission) && <button onClick={save} disabled={saving} className="fixed right-5 bottom-5 z-50 bg-gold text-black px-5 py-3 rounded-full font-mono text-[10px] uppercase disabled:opacity-50 flex gap-2 items-center shadow-lg"><Save size={13}/>{saving ? "Saving…" : "Save changes"}</button>}
  </div>;
}

function FieldInput({ field, value, onChange }: { field: Field; value: any; onChange: (v: any) => void }) { const cls = "mt-1 w-full bg-panel2 border border-border rounded-lg px-3 py-2.5 text-sm text-white outline-none focus:border-golddim"; if (field.type === "textarea") return <textarea value={value ?? ""} onChange={e => onChange(e.target.value)} rows={4} className={cls}/>; if (field.type === "select") return <select value={value ?? field.options?.[0] ?? ""} onChange={e => onChange(e.target.value)} className={cls}>{field.options?.map(o => <option key={o}>{o}</option>)}</select>; return <input type={field.type === "url" ? "url" : field.type === "date" ? "date" : field.type === "time" ? "time" : field.type === "number" ? "number" : "text"} value={value ?? ""} onChange={e => onChange(field.type === "number" ? Number(e.target.value) : e.target.value)} className={cls}/>; }

function SettingsEditor({ value, fields, setValue }: { value: any; fields: Field[]; setValue: (v: any) => void }) { return <section><div className="rounded-2xl border border-gold/30 bg-gradient-to-br from-gold/10 via-panel to-panel p-6 mb-5"><div className="font-mono text-[9px] tracking-[2px] text-golddim">SITE CONTROL</div><h3 className="font-serif text-3xl font-bold mt-2">Everything visitors see starts here.</h3><p className="text-textdim text-sm mt-2">Hero copy, identity, recruitment destination and footer messaging are editable without touching code.</p></div><div className="grid md:grid-cols-2 gap-4">{fields.map(f => <label key={f.key} className={`font-mono text-[9px] uppercase text-textfaint ${f.type === "textarea" ? "md:col-span-2" : ""}`}>{f.label}<FieldInput field={f} value={value[f.key]} onChange={v => setValue({ ...value, [f.key]: v })}/></label>)}</div></section>; }

function CollectionEditor({ section, items, allItems, editing, setEditing, update, add, remove, publish }: { section: Section; items: any[]; allItems: any[]; editing: number | null; setEditing: (v: number | null) => void; update: (i: number, k: string, v: any) => void; add: () => void; remove: (i: number) => void; publish: (i: number) => void }) { return <section><div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-5"><div><h3 className="font-serif text-2xl font-bold">{section.label}</h3><p className="text-textfaint text-xs mt-1">{items.length} record{items.length === 1 ? "" : "s"}{section.private ? " · staff only" : " · public website data"}</p></div><button onClick={add} className="bg-gold text-black px-4 py-2.5 font-mono text-[10px] uppercase flex gap-2 rounded-lg items-center"><Plus size={13}/> Add new</button></div>{items.map((item, displayIndex) => { const realIndex = allItems.findIndex(x => x.id === item.id); const open = editing === realIndex; return <article key={item.id || displayIndex} className="border border-border bg-panel mb-3 rounded-xl overflow-hidden"><div className="flex items-center justify-between px-4 py-3"><button onClick={() => setEditing(open ? null : realIndex)} className="flex-1 text-left flex items-center gap-3"><span className="font-mono text-[9px] text-textfaint">{String(realIndex + 1).padStart(2, "0")}</span><strong className="text-sm">{item.title || item.name || item.code || "Untitled record"}</strong>{section.id === "announcements" && <span className={`text-[9px] font-mono uppercase px-2 py-1 rounded ${item.published ? "bg-green-500/10 text-green-300" : "bg-white/5 text-textfaint"}`}>{item.published ? "Published" : "Draft"}</span>}</button><div className="flex items-center gap-1">{section.id === "announcements" && !item.published && <button onClick={() => publish(realIndex)} className="p-2 text-golddim" title="Publish"><Send size={14}/></button>}<button onClick={() => setEditing(open ? null : realIndex)} className="p-2 text-textdim" title="Edit"><Edit3 size={14}/></button><button onClick={() => remove(realIndex)} className="p-2 text-textdim hover:text-red-300" title="Delete"><Trash2 size={14}/></button></div></div><AnimatePresence>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="border-t border-border"><div className="p-4 grid md:grid-cols-2 gap-4">{section.fields.map(f => <label key={f.key} className={`font-mono text-[9px] uppercase text-textfaint ${f.type === "textarea" ? "md:col-span-2" : ""}`}>{f.label}<FieldInput field={f} value={item[f.key]} onChange={v => update(realIndex, f.key, v)}/></label>)}</div></motion.div>}</AnimatePresence></article>; })}{!items.length && <div className="border border-dashed border-border rounded-2xl p-12 text-center text-textfaint">No records yet. Use <strong>Add new</strong> to create the first one.</div>}</section>; }
