"use client";
import { useEffect, useMemo, useState } from "react";
import { signOut } from "next-auth/react";
import { Save, Plus, Trash2, Search, LogOut, Shield, Users, Megaphone, CalendarDays, ScrollText, Landmark, BadgeCheck, Newspaper, Image as ImageIcon, GitBranch, ShoppingBag, RefreshCw, Sparkles } from "lucide-react";
import MemberSearch from "./MemberSearch";
import { CMS_SECTIONS, type CmsField, type CmsSection } from "../../lib/cms-section-registry";
const icon=(id:string)=>({org:Shield,announcements:Megaphone,calendar:CalendarDays,cocLeadership:GitBranch,cocStaff:GitBranch,cocRoleplay:GitBranch,leadership:Users,divisions:Shield,rules:ScrollText,government:Landmark,ranks:BadgeCheck,news:Newspaper,media:ImageIcon,shop:ShoppingBag,applications:Users,customSections:Sparkles}[id]||Shield);
const uid=()=>`cms-${crypto.randomUUID()}`;
function blank(fields:CmsField[]){return fields.reduce((o:any,f)=>({...o,[f.key]:f.type==="select"?(f.options?.[0]||""):f.type==="number"?0:""}),{id:uid()});}

export default function AdminClientV2(props:{initialContent:any;email:string;access:string;permissions:string[];shopEditable?:boolean;readOnly?:boolean}){
 return <AdminEditor {...props}/>;
}

function AdminEditor({initialContent,email,access,permissions,shopEditable=false}:{initialContent:any;email:string;access:string;permissions:string[];shopEditable?:boolean}){
 const allowed=(s:CmsSection)=>s.id==="shop"?shopEditable:(permissions.includes("admin:all")||permissions.includes(s.permission));
 const visibleSections=CMS_SECTIONS.filter(allowed);const [active,setActive]=useState(visibleSections[0]?.id||"org");const [content,setContent]=useState<any>(initialContent||{});const [query,setQuery]=useState("");const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(false);const [msg,setMsg]=useState("");
 const section=CMS_SECTIONS.find(s=>s.id===active)||CMS_SECTIONS[0];const items=Array.isArray(content[active])?content[active]:[];const filtered=useMemo(()=>items.filter((x:any)=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const refresh=async()=>{setLoading(true);try{const r=await fetch("/api/content",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not read live CMS data");setContent(d);setMsg("Live database data loaded.")}catch(e:any){setMsg(e.message||"Refresh failed")}finally{setLoading(false)}};useEffect(()=>{void refresh()},[]);
 const save=async()=>{setSaving(true);setMsg("");try{const r=await fetch("/api/content",{method:"PUT",headers:{"Content-Type":"application/json","x-content-section":active},body:JSON.stringify({[active]:content[active]})});const d=await r.json();if(!r.ok)throw Error(d.error||"Save failed");setMsg("Saved. Public site uses the same live record.");await refresh()}catch(e:any){setMsg(e.message||"Save failed")}finally{setSaving(false)}};
 const update=(i:number,k:string,v:any)=>setContent((c:any)=>({...c,[active]:items.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}));
 const updateOrg=(k:string,v:any)=>setContent((c:any)=>({...c,org:{...(c.org||{}),[k]:v}));
 const add=()=>setContent((c:any)=>({...c,[active]:[...(Array.isArray(c[active])?c[active]:[]),blank(section.fields)]}));
 const remove=(i:number)=>{if(!confirm("Delete this record?"))return;setContent((c:any)=>({...c,[active]:items.filter((_:any,n:number)=>n!==i)}));};
 return <div className="min-h-screen bg-bg text-white pb-24"><header className="sticky top-0 z-30 border-b border-border bg-bg/95 backdrop-blur px-4 sm:px-8 py-4 flex justify-between items-center"><div><div className="font-mono text-[9px] tracking-[3px] text-golddim uppercase">FBMRP / Administration</div><h1 className="font-serif text-2xl sm:text-3xl font-bold tracking-tight">Staff Management</h1><div className="font-mono text-[8px] text-textfaint uppercase mt-1">{access} · {permissions.length} permissions</div></div><button onClick={()=>signOut({callbackUrl:"/"})} className="border border-border hover:border-gold px-3 py-2.5 font-mono text-[9px] uppercase flex gap-2 items-center"><LogOut size={13}/><span className="hidden sm:inline">Sign out</span></button></header>
 <main className="px-4 sm:px-8 py-7 max-w-[1400px] mx-auto"><div className="mb-6 flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><div className="font-mono text-[8px] tracking-[2px] text-textfaint uppercase">LIVE CONTENT CONTROL</div><h2 className="font-serif text-4xl sm:text-5xl font-bold mt-2">Content Command</h2><p className="text-textdim mt-3 max-w-2xl leading-6">All editors use one canonical section registry and one live content source.</p></div><button onClick={refresh} disabled={loading} className="self-start lg:self-auto border border-border hover:border-gold px-4 py-3 font-mono text-[9px] uppercase flex gap-2 items-center justify-center"><RefreshCw size={13} className={loading?"animate-spin":""}/>{loading?"Reading…":"Refresh live data"}</button></div>
 {access !== "owner" && access !== "staff" && access !== "aide" && <MemberSearch/>}
 <div className="mb-5 flex gap-1 overflow-x-auto border-b border-border pb-1 [scrollbar-width:none]">{visibleSections.map(s=>{const I=icon(s.id);return <button key={s.id} onClick={()=>{setActive(s.id);setQuery("");setMsg("")}} className={`group shrink-0 px-4 py-3 border-b-2 font-mono text-[8px] uppercase flex items-center gap-2 transition-all duration-200 ${active===s.id?"border-gold text-gold bg-gold/5":"border-transparent text-textfaint hover:text-white hover:bg-white/[.03]"}`}><I size={13}/>{s.label}</button>})}</div>
 <div className="mb-5 flex flex-col gap-2 sm:flex-row"><div className="relative min-w-0 flex-1"><Search size={14} className="absolute left-3 top-3.5 text-textfaint"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${section.label.toLowerCase()}…`} className="w-full bg-panel border border-border focus:border-gold px-10 py-3 text-sm outline-none"/></div>{active!=="applications"&&<button onClick={add} className="bg-gold hover:bg-golddim text-black px-5 py-3 font-mono text-[9px] uppercase flex gap-2 items-center justify-center"><Plus size={14}/> Add record</button>}<button onClick={save} disabled={saving} className="border border-gold text-gold hover:bg-gold hover:text-black px-5 py-3 font-mono text-[9px] uppercase flex gap-2 items-center justify-center"><Save size={14}/>{saving?"Saving…":"Save changes"}</button></div>
 {msg&&<div className="mb-5 border-l-2 border-gold bg-gold/5 px-4 py-3 text-sm text-golddim">{msg}</div>}
 {active==="org"?<div className="grid gap-x-6 gap-y-4 md:grid-cols-2 max-w-5xl">{section.fields.map(f=><label key={f.key} className="block"><span className="font-mono text-[8px] uppercase tracking-[1px] text-textfaint">{f.label}</span><FieldInput field={f} value={content.org?.[f.key]} onChange={v=>updateOrg(f.key,v)}/></label>)}</div>:<div className="space-y-3">{filtered.map((item:any,fi:number)=>{const realIndex=items.indexOf(item);return <article key={item.id||fi} className="border border-border bg-panel/60 hover:border-gold/30 transition-colors p-4 sm:p-5"><div className="mb-4 flex justify-between gap-3"><div><div className="font-mono text-[8px] text-golddim uppercase">{String(realIndex+1).padStart(2,"0")} / {section.label}</div><h3 className="mt-1 font-serif text-xl font-bold">{item.title||item.name||item.code||item.slug||"Untitled record"}</h3></div><button onClick={()=>remove(realIndex)} aria-label="Delete record" className="h-fit border border-red-400/20 p-2 text-red-300 hover:border-red-400/60"><Trash2 size={14}/></button></div><div className="grid gap-x-5 gap-y-4 md:grid-cols-2">{section.fields.map(f=><label key={f.key} className="block"><span className="font-mono text-[8px] uppercase tracking-[1px] text-textfaint">{f.label}</span><FieldInput field={f} value={item[f.key]} onChange={v=>update(realIndex,f.key,v)}/></label>)}</div></article>})}{filtered.length===0&&<div className="border border-dashed border-border p-12 text-center text-textfaint"><div className="font-serif text-xl text-white mb-2">No records in this section</div><p className="text-sm">Refresh reads the same live source used by the public site and Section Studio.</p></div>}</div>}
 </main></div>;
}
function FieldInput({field,value,onChange}:{field:CmsField;value:any;onChange:(v:any)=>void}){const cls="mt-1 w-full bg-panel2 border border-border focus:border-gold px-3 py-3 text-sm text-white outline-none transition-colors";if(field.type==="textarea")return <textarea rows={4} value={value??""} onChange={e=>onChange(e.target.value)} className={cls}/>;if(field.type==="select")return <select value={value??field.options?.[0]??""} onChange={e=>onChange(e.target.value)} className={cls}>{field.options?.map(o=><option key={o}>{o}</option>)}</select>;return <input type={field.type==="url"?"url":field.type==="date"?"date":field.type==="time"?"time":field.type==="number"?"number":"text"} value={value??""} onChange={e=>onChange(field.type==="number"?Number(e.target.value):e.target.value)} className={cls}/>}
