"use client";
import { useMemo, useState } from "react";
import { signOut } from "next-auth/react";
import { Save, Plus, Trash2, Search, LogOut, Shield, Users, Megaphone, CalendarDays, ScrollText, Landmark, BadgeCheck, Newspaper, Image as ImageIcon, GitBranch, ShoppingBag } from "lucide-react";

type Field={key:string;label:string;type?:"text"|"textarea"|"url"|"date"|"time"|"number"|"select";options?:string[]};
type Section={id:string;label:string;permission?:string;fields:Field[]};

const commonCoc:Field[]=[{key:"title",label:"Position / Level"},{key:"name",label:"Assigned Person"},{key:"description",label:"Description",type:"textarea"},{key:"active",label:"Status",type:"select",options:["active","inactive"]},{key:"order",label:"Display order",type:"number"}];
const sections:Section[]=[
{id:"org",label:"Site",fields:[{key:"name",label:"Short name"},{key:"fullName",label:"Full name"},{key:"owner",label:"Owner"},{key:"coOwner",label:"Co-owner"},{key:"heroEyebrow",label:"Hero eyebrow"},{key:"heroTitle",label:"Hero title"},{key:"heroDescription",label:"Hero description",type:"textarea"},{key:"recruitmentUrl",label:"Recruitment URL",type:"url"},{key:"footerText",label:"Footer text"},{key:"status",label:"Status",type:"select",options:["active","maintenance","closed"]}]},
{id:"announcements",label:"Announcements",fields:[{key:"title",label:"Title"},{key:"body",label:"Announcement",type:"textarea"},{key:"published",label:"Status",type:"select",options:["draft","published"]},{key:"createdAt",label:"Date",type:"date"}]},
{id:"calendar",label:"Operations",fields:[{key:"title",label:"Event title"},{key:"date",label:"Date",type:"date"},{key:"time",label:"Time",type:"time"},{key:"location",label:"Location"},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["draft","published"]}]},
{id:"cocLeadership",label:"Leadership CoC",fields:commonCoc},{id:"cocStaff",label:"Staff CoC",fields:commonCoc},{id:"cocRoleplay",label:"Roleplay CoC",fields:commonCoc},
{id:"leadership",label:"Command",fields:[{key:"title",label:"Position"},{key:"name",label:"Name"},{key:"discordId",label:"Discord ID"},{key:"division",label:"Division"},{key:"rank",label:"Rank"},{key:"description",label:"Description",type:"textarea"},{key:"active",label:"Status",type:"select",options:["active","inactive"]},{key:"order",label:"Display order",type:"number"}]},
{id:"divisions",label:"Divisions",fields:[{key:"code",label:"Code"},{key:"name",label:"Division name"},{key:"description",label:"Description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["active","inactive","temporary"]},{key:"leadership",label:"Leadership"},{key:"logoUrl",label:"Logo URL",type:"url"},{key:"order",label:"Display order",type:"number"}]},
{id:"rules",label:"Rules / CoC",fields:[{key:"title",label:"Rule title"},{key:"category",label:"Category"},{key:"body",label:"Rule",type:"textarea"},{key:"order",label:"Display order",type:"number"}]},
{id:"government",label:"Government",fields:[{key:"name",label:"Name"},{key:"role",label:"Role"},{key:"department",label:"Department"},{key:"description",label:"Description",type:"textarea"},{key:"order",label:"Display order",type:"number"}]},
{id:"ranks",label:"Ranks",fields:[{key:"name",label:"Rank"},{key:"level",label:"Level"},{key:"description",label:"Description",type:"textarea"},{key:"insigniaUrl",label:"Insignia URL",type:"url"},{key:"order",label:"Display order",type:"number"}]},
{id:"news",label:"News",fields:[{key:"title",label:"Headline"},{key:"excerpt",label:"Summary",type:"textarea"},{key:"body",label:"Article",type:"textarea"},{key:"date",label:"Date",type:"date"},{key:"imageUrl",label:"Image URL",type:"url"},{key:"order",label:"Display order",type:"number"}]},
{id:"media",label:"Media",fields:[{key:"title",label:"Title"},{key:"caption",label:"Caption",type:"textarea"},{key:"imageUrl",label:"Image URL",type:"url"},{key:"videoUrl",label:"Video URL",type:"url"},{key:"category",label:"Category"},{key:"order",label:"Display order",type:"number"}]},
{id:"shop",label:"Shop",permission:"shop:manage",fields:[{key:"name",label:"Faction / Family name"},{key:"type",label:"Type",type:"select",options:["faction","family"]},{key:"description",label:"Description",type:"textarea"},{key:"price",label:"Price"},{key:"gamepassUrl",label:"Gamepass link",type:"url"},{key:"imageUrl",label:"Image URL",type:"url"},{key:"status",label:"Status",type:"select",options:["active","inactive","sold-out"]},{key:"order",label:"Display order",type:"number"}]},
{id:"applications",label:"Applications",fields:[{key:"name",label:"Applicant"},{key:"type",label:"Application type"},{key:"status",label:"Status",type:"select",options:["pending","approved","rejected"]},{key:"notes",label:"Staff notes",type:"textarea"}]}
];
const permissionsBySection:Record<string,string>={org:"site:edit",announcements:"announcements:manage",calendar:"calendar:manage",cocLeadership:"site:edit",cocStaff:"site:edit",cocRoleplay:"site:edit",leadership:"leadership:edit",divisions:"divisions:edit",rules:"site:edit",government:"site:edit",ranks:"site:edit",news:"site:edit",media:"media:manage",applications:"applications:manage"};
const icon=(id:string)=>({org:Shield,announcements:Megaphone,calendar:CalendarDays,cocLeadership:GitBranch,cocStaff:GitBranch,cocRoleplay:GitBranch,leadership:Users,divisions:Shield,rules:ScrollText,government:Landmark,ranks:BadgeCheck,news:Newspaper,media:ImageIcon,shop:ShoppingBag,applications:Users}[id]||Shield);
const uid=()=>`cms-${crypto.randomUUID()}`;
function blank(fields:Field[]){return fields.reduce((o:any,f)=>({...o,[f.key]:f.type==="select"?(f.options?.[0]||""):f.type==="number"?0:""}),{id:uid()});}

export default function AdminClientV2({initialContent,email,access,permissions,shopEditable=false}:{initialContent:any;email:string;access:string;permissions:string[];shopEditable?:boolean}){
 const allowed=(s:Section)=>s.id==="shop"?shopEditable:(permissions.includes("admin:all")||permissions.includes(permissionsBySection[s.id]||"__none__"));
 const visibleSections=sections.filter(allowed); const [active,setActive]=useState(visibleSections[0]?.id||"org"); const [content,setContent]=useState<any>(initialContent||{}); const [query,setQuery]=useState(""); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const section=sections.find(s=>s.id===active)!; const items=Array.isArray(content[active])?content[active]:[]; const filtered=useMemo(()=>items.filter((x:any)=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const save=async()=>{setSaving(true);setMsg("");try{const r=await fetch("/api/content",{method:"PUT",headers:{"Content-Type":"application/json","x-content-section":active},body:JSON.stringify({[active]:content[active]})});const d=await r.json();if(!r.ok)throw Error(d.error||"Save failed");setMsg("Saved to database and public site.");}catch(e:any){setMsg(e.message||"Save failed");}finally{setSaving(false)}};
 const update=(i:number,k:string,v:any)=>setContent((c:any)=>({...c,[active]:items.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}));
 const add=()=>{setContent((c:any)=>({...c,[active]:[...(Array.isArray(c[active])?c[active]:[]),blank(section.fields)]}));};
 const remove=(i:number)=>{if(!confirm("Delete this record?"))return;setContent((c:any)=>({...c,[active]:items.filter((_:any,n:number)=>n!==i)}));};
 return <div className="min-h-screen bg-bg text-white pb-32"><header className="sticky top-0 z-30 border-b border-border bg-bg/95 backdrop-blur px-5 sm:px-10 py-5 flex justify-between items-center"><div><div className="font-mono text-[10px] tracking-[2px] text-golddim uppercase">FBMRP Administration</div><h1 className="font-serif text-2xl font-bold">Staff Management</h1><div className="font-mono text-[9px] text-textfaint uppercase mt-1">{access} · {permissions.length} permissions</div></div><button onClick={()=>signOut({callbackUrl:"/"})} className="border border-border px-4 py-3 font-mono text-[10px] uppercase flex gap-2 items-center"><LogOut size={13}/> Sign out</button></header>
 <main className="px-5 sm:px-10 py-8 max-w-7xl mx-auto"><div className="mb-7"><div className="font-mono text-[9px] text-textfaint uppercase">SIGNED IN · {email}</div><h2 className="font-serif text-4xl font-bold mt-2">Content Command</h2><p className="text-textdim mt-2 max-w-3xl">One database is the source of truth. Existing records are shown here, staff edits are persisted, and the public website reads the same records.</p></div>
 <div className="flex gap-2 mb-5 overflow-x-auto pb-2">{visibleSections.map(s=>{const I=icon(s.id);return <button key={s.id} onClick={()=>{setActive(s.id);setQuery("");setMsg("")}} className={`shrink-0 rounded-xl border px-4 py-3 font-mono text-[9px] uppercase ${active===s.id?"border-gold bg-gold text-black":"border-border bg-panel text-textdim"}`}><I size={14} className="mx-auto mb-1"/>{s.label}</button>})}</div>
 <div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-textfaint"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records…" className="w-full bg-panel border border-border rounded-xl pl-10 pr-4 py-3 text-sm"/></div>{active!=="applications"&&<button onClick={add} className="bg-gold text-black rounded-xl px-5 py-3 font-mono text-[10px] uppercase flex gap-2 items-center justify-center"><Plus size={14}/> Add new</button>}<button onClick={save} disabled={saving} className="border border-gold text-gold rounded-xl px-5 py-3 font-mono text-[10px] uppercase flex gap-2 items-center justify-center"><Save size={14}/>{saving?"Saving…":"Save changes"}</button></div>
 {msg&&<div className="mb-5 rounded-xl border border-gold/30 bg-gold/10 p-3 text-sm text-golddim">{msg}</div>}
 {active==="org"?<div className="grid md:grid-cols-2 gap-4">{section.fields.map(f=><label key={f.key} className="block"><span className="font-mono text-[9px] uppercase text-textfaint">{f.label}</span><FieldInput field={f} value={content.org?.[f.key]} onChange={v=>setContent((c:any)=>({...c,org:{...(c.org||{}),[f.key]:v}}))}/></label>)}</div>:<div className="space-y-4">{filtered.map((item:any,fi:number)=>{const realIndex=items.indexOf(item);return <article key={item.id||fi} className="rounded-2xl border border-border bg-panel p-5"><div className="flex justify-between gap-3 mb-4"><div><div className="font-mono text-[9px] text-golddim uppercase">{section.label} · {String(realIndex+1).padStart(2,"0")}</div><h3 className="font-serif text-xl font-bold mt-1">{item.title||item.name||"Untitled record"}</h3></div><button onClick={()=>remove(realIndex)} className="text-red-300 border border-red-400/20 rounded-lg p-2"><Trash2 size={14}/></button></div><div className="grid md:grid-cols-2 gap-4">{section.fields.map(f=><label key={f.key} className="block"><span className="font-mono text-[9px] uppercase text-textfaint">{f.label}</span><FieldInput field={f} value={item[f.key]} onChange={v=>update(realIndex,f.key,v)}/></label>)}</div></article>})}{filtered.length===0&&<div className="rounded-2xl border border-dashed border-border p-12 text-center text-textfaint">No records found. Existing database records will appear here after the CMS migration.</div>}</div>}
 </main></div>;
}
function FieldInput({field,value,onChange}:{field:Field;value:any;onChange:(v:any)=>void}){const cls="mt-1 w-full bg-panel2 border border-border rounded-xl px-3 py-3 text-sm text-white outline-none focus:border-gold";if(field.type==="textarea")return <textarea rows={4} value={value??""} onChange={e=>onChange(e.target.value)} className={cls}/>;if(field.type==="select")return <select value={value??field.options?.[0]??""} onChange={e=>onChange(e.target.value)} className={cls}>{field.options?.map(o=><option key={o}>{o}</option>)}</select>;return <input type={field.type==="url"?"url":field.type==="date"?"date":field.type==="time"?"time":field.type==="number"?"number":"text"} value={value??""} onChange={e=>onChange(field.type==="number"?Number(e.target.value):e.target.value)} className={cls}/>}
