"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Copy, Eye, GripVertical, Image as ImageIcon, Plus, Save, Sparkles, Trash2, Video } from "lucide-react";

type Block={id:string;type:string;title?:string;body?:string;imageUrl?:string;imageAlt?:string;images?:string[];videoUrl?:string;buttonLabel?:string;buttonUrl?:string;value?:string;label?:string;embedUrl?:string};
type Section={id:string;slug:string;eyebrow:string;title:string;description:string;layout:string;accent:string;published:boolean;order:number;blocks:Block[]};
const types=["text","image","gallery","video","quote","stats","cta","embed","divider"];
const uid=()=>crypto.randomUUID();
const blank=():Section=>({id:uid(),slug:"new-section",eyebrow:"FBMR INFORMATION",title:"New section",description:"",layout:"wide",accent:"gold",published:false,order:99,blocks:[]});
const newBlock=(type="text"):Block=>({id:uid(),type,title:"",body:"",images:[],imageUrl:"",videoUrl:"",buttonLabel:"OPEN",buttonUrl:"",value:"",label:"",embedUrl:""});

export default function SectionBuilder(){
 const [sections,setSections]=useState<Section[]>([]); const [active,setActive]=useState(0); const [preview,setPreview]=useState(false); const [status,setStatus]=useState("Loading live sections…"); const [loaded,setLoaded]=useState(false);
 const current=sections[active];
 const load=async()=>{try{const r=await fetch("/api/content",{cache:"no-store"});const d=await r.json();setSections(Array.isArray(d.customSections)?d.customSections:[]);setStatus("Live sections loaded.");setLoaded(true)}catch{setStatus("Could not load sections.");setLoaded(true)}};
 useEffect(()=>{void load()},[]);
 const update=(patch:Partial<Section>)=>setSections(a=>a.map((s,i)=>i===active?{...s,...patch}:s));
 const updateBlock=(i:number,patch:Partial<Block>)=>{if(!current)return;update({blocks:current.blocks.map((b,n)=>n===i?{...b,...patch}:b)})};
 const addBlock=(type="text")=>current&&update({blocks:[...current.blocks,newBlock(type)]});
 const save=async(publish?:boolean)=>{const next=sections.map((s,i)=>i===active&&publish!==undefined?{...s,published:publish}:s);setSections(next);setStatus("Saving…");try{const r=await fetch("/api/content",{method:"PUT",headers:{"Content-Type":"application/json","x-content-section":"customSections"},body:JSON.stringify({customSections:next})});const d=await r.json();if(!r.ok)throw Error(d.error||"Save failed");setStatus(publish?"Published to FBMR immediately.":"Draft saved. Public site unchanged until published.")}catch(e:any){setStatus(e?.message||"Save failed")}};
 const duplicate=()=>{if(!current)return;const copy={...current,id:uid(),slug:`${current.slug}-copy`,title:`${current.title} copy`,blocks:current.blocks.map(b=>({...b,id:uid()})),published:false,order:sections.length+1};setSections([...sections,copy]);setActive(sections.length)};
 const move=(dir:number)=>{const n=active+dir;if(!current||n<0||n>=sections.length)return;const a=[...sections];[a[active],a[n]]=[a[n],a[active]];a.forEach((s,i)=>s.order=i+1);setSections(a);setActive(n)};
 const addSection=()=>{const s=blank();s.order=sections.length+1;setSections([...sections,s]);setActive(sections.length)};
 const deleteSection=()=>{if(!current||!confirm("Delete this section?"))return;const a=sections.filter((_,i)=>i!==active);setSections(a);setActive(Math.max(0,active-1))};
 const previewData=useMemo(()=>current?[current]:[],[current]);
 if(!loaded)return <main className="min-h-screen bg-[#050706] text-white grid place-items-center"><div className="text-center"><Sparkles className="mx-auto mb-4 text-[#d4b56a]"/><p className="text-sm text-white/50">{status}</p></div></main>;
 return <main className="min-h-screen bg-[#050706] text-white">
  <header className="sticky top-0 z-50 border-b border-white/10 bg-[#050706]/95 backdrop-blur-xl"><div className="mx-auto max-w-[1600px] px-4 md:px-8 py-4 flex flex-wrap items-center justify-between gap-4"><div><div className="text-[9px] tracking-[.3em] text-[#d4b56a]">FBMR / SECTION STUDIO</div><h1 className="mt-1 text-xl md:text-2xl font-semibold">Information Builder</h1></div><div className="flex flex-wrap gap-2"><button onClick={()=>setPreview(!preview)} className="border border-white/15 px-4 py-2 text-[9px] tracking-widest uppercase flex items-center gap-2"><Eye size={14}/>{preview?"Editor":"Preview"}</button>{current&&<><button onClick={()=>save(false)} className="border border-[#d4b56a]/50 text-[#d4b56a] px-4 py-2 text-[9px] tracking-widest uppercase flex items-center gap-2"><Save size={14}/>Draft</button><button onClick={()=>save(true)} className="bg-[#d4b56a] text-black px-4 py-2 text-[9px] tracking-widest uppercase">Publish</button></>}</div></div></header>
  {preview&&current?<section className="mx-auto max-w-5xl px-5 md:px-10 py-16"><div className="text-[9px] tracking-[.3em] text-[#d4b56a]">{current.eyebrow}</div><h2 className="mt-3 text-5xl md:text-7xl tracking-tight">{current.title}</h2><p className="mt-5 max-w-2xl text-white/55 leading-7">{current.description||"No description yet."}</p><div className="mt-12 space-y-6">{current.blocks.map(b=><article key={b.id} className="border border-white/10 bg-white/[.025] p-6">{b.title&&<h3 className="text-2xl">{b.title}</h3>}{b.body&&<p className="mt-3 text-white/55 whitespace-pre-wrap">{b.body}</p>}{b.imageUrl&&<img src={b.imageUrl} alt={b.imageAlt||""} className="mt-5 max-h-[480px] w-full object-cover"/>}{b.videoUrl&&<a className="mt-4 inline-flex text-[#d4b56a]" href={b.videoUrl} target="_blank" rel="noreferrer"><Video size={15} className="mr-2"/>Open video</a>}{b.value&&<div className="mt-3 text-4xl text-[#d4b56a]">{b.value}</div>}</article>)}</div></section>:<div className="mx-auto max-w-[1600px] grid lg:grid-cols-[300px_1fr] min-h-[calc(100vh-73px)]"><aside className="border-r border-white/10 p-4 md:p-6"><div className="flex justify-between items-center mb-4"><span className="text-[9px] tracking-widest text-white/30 uppercase">Sections</span><button onClick={addSection} className="rounded-full bg-[#d4b56a] p-2 text-black"><Plus size={15}/></button></div>{sections.map((s,i)=><button key={s.id} onClick={()=>setActive(i)} className={`w-full text-left border p-4 mb-2 transition ${i===active?"border-[#d4b56a]/60 bg-[#d4b56a]/5":"border-white/10 bg-white/[.02]"}`}><div className="text-[8px] tracking-widest text-[#d4b56a]">{String(i+1).padStart(2,"0")} · {s.published?"PUBLISHED":"DRAFT"}</div><div className="mt-2 text-sm font-medium truncate">{s.title||"Untitled section"}</div><div className="mt-1 text-[9px] text-white/25">/{s.slug}</div></button>)}{!sections.length&&<p className="text-xs leading-5 text-white/30">Create your first section. It will stay private until you publish it.</p>}</aside>
   <section className="p-5 md:p-8 lg:p-12">{current?<><div className="mb-8 flex flex-wrap justify-between gap-4"><div><div className="text-[8px] tracking-widest text-white/25 uppercase">Section settings</div><h2 className="mt-2 text-3xl md:text-5xl tracking-tight">Build the story.</h2></div><div className="flex gap-2"><button onClick={()=>move(-1)} className="border border-white/10 p-2"><ArrowUp size={14}/></button><button onClick={()=>move(1)} className="border border-white/10 p-2"><ArrowDown size={14}/></button><button onClick={duplicate} className="border border-white/10 p-2"><Copy size={14}/></button><button onClick={deleteSection} className="border border-red-400/20 p-2 text-red-300"><Trash2 size={14}/></button></div></div>
    <div className="grid gap-4 md:grid-cols-2">{([["eyebrow","Eyebrow"],["title","Title"],["slug","URL slug"],["description","Description"]] as const).map(([k,l])=><label key={k} className={k==="description"?"md:col-span-2":""}><span className="text-[8px] tracking-widest text-white/30 uppercase">{l}</span>{k==="description"?<textarea rows={4} value={current[k]} onChange={e=>update({[k]:e.target.value})} className="mt-1 w-full bg-white/[.03] border border-white/10 p-3 text-sm outline-none focus:border-[#d4b56a]"/>:<input value={current[k]} onChange={e=>update({[k]:e.target.value})} className="mt-1 w-full bg-white/[.03] border border-white/10 p-3 text-sm outline-none focus:border-[#d4b56a]"/>}</label>)}<label><span className="text-[8px] tracking-widest text-white/30 uppercase">Layout</span><select value={current.layout} onChange={e=>update({layout:e.target.value})} className="mt-1 w-full bg-[#101410] border border-white/10 p-3 text-sm">{["wide","split","feature","grid","story"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="text-[8px] tracking-widest text-white/30 uppercase">Accent</span><select value={current.accent} onChange={e=>update({accent:e.target.value})} className="mt-1 w-full bg-[#101410] border border-white/10 p-3 text-sm">{["gold","white","olive"].map(x=><option key={x}>{x}</option>)}</select></label></div>
    <div className="mt-12 border-t border-white/10 pt-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[8px] tracking-widest text-white/25 uppercase">Content blocks</div><p className="mt-1 text-sm text-white/40">Add text, imagery, galleries, video, quotes, stats, CTAs or embeds.</p></div><div className="flex flex-wrap gap-2">{types.map(t=><button key={t} onClick={()=>addBlock(t)} className="border border-white/10 px-3 py-2 text-[8px] tracking-widest uppercase hover:border-[#d4b56a]/60">+ {t}</button>)}</div></div>
     <div className="mt-6 space-y-4">{current.blocks.map((b,i)=><article key={b.id} className="border border-white/10 bg-white/[.02] p-5"><div className="flex items-center gap-2 text-[8px] tracking-widest text-white/25 uppercase"><GripVertical size={13}/>{String(i+1).padStart(2,"0")} · {b.type}</div><div className="mt-4 grid gap-4 md:grid-cols-2"><input placeholder="Block title" value={b.title||""} onChange={e=>updateBlock(i,{title:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/><input placeholder="Image URL / media URL" value={b.imageUrl||b.videoUrl||""} onChange={e=>b.type==="video"?updateBlock(i,{videoUrl:e.target.value}):updateBlock(i,{imageUrl:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/><textarea placeholder="Content" rows={4} value={b.body||""} onChange={e=>updateBlock(i,{body:e.target.value})} className="md:col-span-2 bg-white/[.03] border border-white/10 p-3 text-sm"/>{(b.type==="cta")&&<><input placeholder="Button label" value={b.buttonLabel||""} onChange={e=>updateBlock(i,{buttonLabel:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/><input placeholder="Button URL" value={b.buttonUrl||""} onChange={e=>updateBlock(i,{buttonUrl:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/></>}{b.type==="stats"&&<><input placeholder="Value" value={b.value||""} onChange={e=>updateBlock(i,{value:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/><input placeholder="Label" value={b.label||""} onChange={e=>updateBlock(i,{label:e.target.value})} className="bg-white/[.03] border border-white/10 p-3 text-sm"/></>}</div></article>)}</div></div>
    <div className="mt-8 flex items-center gap-3"><ImageIcon size={15} className="text-[#d4b56a]"/><span className="text-xs text-white/30">{status}</span></div>
   </>:<div className="min-h-[50vh] grid place-items-center text-center"><Sparkles className="text-[#d4b56a] mx-auto mb-4"/><h2 className="text-3xl">Create an FBMR section</h2><p className="mt-2 text-white/40">Use the + button to start building content.</p></div>}</section></div>}
 </main>;
}
