import { NEXUS_ALLOWED_GUILD_ID } from '../security/access';
import { getCapabilityCatalog } from './capabilities';
import type { DynamicExecutionPlan } from './ai-plan';
import { executeAndVerify } from '../tools/execute-verified';
import { inspectServerForRuntime } from '../tools/runtime';
export type NexusContext = { guildId: string; channelId?: string; userId?: string };
export type AgentTurnResult = { mode: 'conversation' | 'execute'; response: string; plan?: DynamicExecutionPlan; results?: unknown[] };
type MemoryState = { messages: Array<{ role: 'user' | 'assistant'; content: string }>; objective?: string; plan?: DynamicExecutionPlan; results?: unknown[] };
const memory = new Map<string, MemoryState>(); const MAX_MESSAGES = 24; const MAX_STEPS = 12;
function key(c: NexusContext) { return `${c.guildId}:${c.userId || 'unknown'}:${c.channelId || 'unknown'}`; }
function state(c: NexusContext): MemoryState { const k = key(c); const old = memory.get(k); if (old) return old; const fresh: MemoryState = { messages: [] }; memory.set(k, fresh); return fresh; }
function remember(c: NexusContext, role: 'user' | 'assistant', content: string) { const s = state(c); s.messages = [...s.messages, { role, content }].slice(-MAX_MESSAGES); }
function history(c: NexusContext) { const s = state(c); return { messages: s.messages, objective: s.objective, plan: s.plan, results: s.results }; }
function parseJson(text: string): any { const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim(); try { return JSON.parse(cleaned); } catch { return null; } }
async function groq(messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>): Promise<string> { const apiKey = process.env.NEXUS_GROQ_API_KEY; if (!apiKey) throw new Error('Configuration error: NEXUS_GROQ_API_KEY is not configured.'); const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: process.env.NEXUS_AI_MODEL || 'openai/gpt-oss-120b', messages, temperature: 0.2 }), cache: 'no-store' }); const raw = await response.text(); let data: any = null; try { data = raw ? JSON.parse(raw) : null; } catch { throw new Error(`Groq error: non-JSON response (HTTP ${response.status}).`); } if (!response.ok) throw new Error(`Groq error: ${data?.error?.message || `HTTP ${response.status}`}`); const text = data?.choices?.[0]?.message?.content?.trim(); if (!text) throw new Error('Groq error: empty response.'); return text; }
async function channelContext(channelId?: string) { if (!channelId) return '(no channel context)'; try { const { messages } = await import('../discord/rest'); const rows = await messages(channelId, 50); return Array.isArray(rows) ? rows.reverse().map((m: any) => `${m?.author?.global_name || m?.author?.username || m?.author?.id || 'user'}: ${m?.content || ''}`).filter(Boolean).join('\n').slice(-12000) : '(no channel context)'; } catch { return '(channel context unavailable)'; } }
function containsMutation(plan: DynamicExecutionPlan) { return plan.steps.some((s) => ['change', 'destructive'].includes(getCapabilityCatalog().find((c) => c.name === s.capability)?.risk || 'read')); }
export async function decide(message: string, context: NexusContext) { const prompt = ['You are the unified decision layer of NEXUS.', 'Classify the current message using conversation, prior execution state, and recent Discord context.', 'Choose conversation for chatting, questions, explanations, or discussing results without requesting an action.', 'Choose execute when the user asks NEXUS to investigate, inspect, create, modify, moderate, configure, or perform an objective.', 'Resolve references such as this, that, it, continue, change it, undo that, and what did you change using context.', 'Reason from intent; do not use regex or keyword-only routing.', 'Return ONLY JSON: {"mode":"conversation"|"execute","response":"...","goal":"..."}.', `Authoritative guild: ${context.guildId}`, `Context: ${JSON.stringify(history(context))}`, `Discord channel context:\n${await channelContext(context.channelId)}`, `Current message: ${message}`].join('\n\n'); const parsed = parseJson(await groq([{ role: 'system', content: prompt }])); if (!parsed || !['conversation', 'execute'].includes(parsed.mode)) return { mode: 'conversation' as const, response: String(parsed?.response || 'I could not determine the request.') }; if (parsed.mode === 'execute' && !String(parsed.goal || '').trim()) return { mode: 'conversation' as const, response: String(parsed.response || 'Tell me what you want me to do.') }; return parsed as { mode: 'conversation' | 'execute'; response?: string; goal?: string }; }
export async function converse(message: string, context: NexusContext) { const text = await groq([{ role: 'system', content: 'You are NEXUS. Be natural, concise, and honest. Use supplied context to answer follow-ups. Never claim an action happened unless execution results prove it.' }, { role: 'user', content: `Guild: ${context.guildId}\nMemory: ${JSON.stringify(history(context))}\nDiscord context:\n${await channelContext(context.channelId)}\nMessage: ${message}` }]); remember(context, 'user', message); remember(context, 'assistant', text); return text; }
export async function runAgentTurn(message: string, context: NexusContext, forcedGoal?: string): Promise<AgentTurnResult> { if (context.guildId !== NEXUS_ALLOWED_GUILD_ID) throw new Error('Authorization error: NEXUS is disabled outside the authorized guild.'); const decision = forcedGoal ? { mode: 'execute' as const, goal: forcedGoal } : await decide(message, context); if (decision.mode === 'conversation') return { mode: 'conversation', response: await converse(message, context) }; const goal = String(decision.goal || message).trim(); const s = state(context); s.objective = goal; const { createDynamicPlan } = await import('./ai-runtime'); const plan = await createDynamicPlan(goal, context.guildId, context.userId || '', context.channelId || ''); if (plan.steps.length > MAX_STEPS) plan.steps = plan.steps.slice(0, MAX_STEPS); const results: any[] = []; if (containsMutation(plan) && !plan.steps.some((x) => x.capability === 'inspect_server')) results.push({ stepId: '__safety_inspection', capability: 'inspect_server', ok: true, result: await inspectServerForRuntime(context.guildId), automatic: true }); for (const step of plan.steps.slice(0, MAX_STEPS)) { const input = resolveReferences(step.input, results); const result = await executeAndVerify(context, step.capability, { ...input, guildId: context.guildId, channelId: context.channelId }); results.push({ stepId: step.id, capability: step.capability, purpose: step.purpose, ok: result.ok, result: result.result, verification: result.verification, error: result.error }); if (!result.ok || result.verification && !result.verification.ok) break; if (step.verification) { const verification = await executeAndVerify(context, step.verification.capability, { ...resolveReferences(step.verification.input, results), guildId: context.guildId, channelId: context.channelId }); results.push({ stepId: `${step.id}:plan-verification`, capability: step.verification.capability, verification: true, ok: verification.ok, result: verification.result, error: verification.error }); if (!verification.ok) break; } } s.plan = plan; s.results = results; const report = await reportExecution(goal, context, plan, results); remember(context, 'user', message); remember(context, 'assistant', report); return { mode: 'execute', response: report, plan, results }; }
function resolveReferences(value: unknown, results: any[]): any { if (typeof value === 'string') return value.replace(/\{\{([^}]+)\}\}/g, (_, path) => String(resolvePath(results, String(path)) ?? '')); if (Array.isArray(value)) return value.map((v) => resolveReferences(v, results)); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveReferences(v, results)])); return value; }
function resolvePath(results: any[], path: string) { const [stepId, ...parts] = path.split('.'); const item = results.find((r) => r?.stepId === stepId); let current: any = item; for (const part of parts) { if (current == null) return undefined; current = current[part]; } return current; }
async function reportExecution(goal: string, context: NexusContext, plan: DynamicExecutionPlan, results: unknown[]) { return groq([{ role: 'system', content: 'You are NEXUS reporting actual execution. Use only supplied results. Never claim success without ok=true and verified mutations. Summarize objective, plan, completed work, useful findings, verification, issues, deliberate non-changes, manual/external requirements, and security notes. Keep under 1800 characters for Discord.' }, { role: 'user', content: `Objective: ${goal}\nPlan: ${JSON.stringify(plan)}\nResults: ${JSON.stringify(results)}\nGuild: ${context.guildId}` }]); }
