import { createHmac, createPublicKey, randomUUID, verify } from "node:crypto";
import { getQuotaLeaderboard, processQuotaDirect } from "@/lib/quota-sheets";
import { attachQuotaMessage, claimQuotaApproval, createQuotaRequest, getQuotaRequestState, markQuotaApproved, markQuotaRejected } from "@/lib/quota-state";

const STAFF_GUILD_ID = "1539736452995350528";
const STAFF_ROLE_ID = "1539751393139626044";
const LOGISTICS_ROLE_ID = "1539908119067492427";
const TESTER_ROLE_ID = "1540499074061439006";
const QUOTA_CHANNEL_ID = "1545116182858965046";
const QUOTA_LOG_CHANNEL_ID = "1539785260923879505";
const BOT_TOKEN = process.env.DISCORD_BOT_TOKEN?.trim();
const APPLICATION_ID = (process.env.DISCORD_APPLICATION_ID || process.env.DISCORD_CLIENT_ID || "").trim();
const PUBLIC_KEY = process.env.DISCORD_PUBLIC_KEY?.trim();
const encoder = new TextEncoder();
type QuotaRequest = { id:string; userId:string; username:string; quota:number; proof:string; proofName:string; notes:string; createdAt:string };
function secret(){const v=process.env.NEXTAUTH_SECRET;if(!v||v.length<32)throw new Error("NEXTAUTH_SECRET is not configured");return v;}
function hmac(v:string){return createHmac("sha256",secret()).update(v).digest("hex");}
function sig(r:QuotaRequest){return hmac(JSON.stringify({id:r.id,userId:r.userId,username:r.username,quota:r.quota,proof:r.proof,proofName:r.proofName,notes:r.notes})).slice(0,24);}
function pub(){if(!PUBLIC_KEY)throw new Error("DISCORD_PUBLIC_KEY is not configured");const raw=Buffer.from(PUBLIC_KEY,"hex");return createPublicKey({key:Buffer.concat([Buffer.from("302a300506032b6570032100","hex"),raw]),format:"der",type:"spki"});}
function valid(body:string,t:string,s:string){try{return verify(null,encoder.encode(t+body),pub(),Buffer.from(s,"hex"));}catch{return false;}}
function roles(i:any):string[]{return Array.isArray(i?.member?.roles)?i.member.roles:[];}
function has(i:any,r:string){return roles(i).includes(r);}
function response(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json"}});}
function eph(content:string){return {type:4,data:{content,flags:64}};}
async function api(path:string,init:RequestInit={}){if(!BOT_TOKEN)throw new Error("DISCORD_BOT_TOKEN is not configured");const r=await fetch(`https://discord.com/api/v10${path}`,{...init,headers:{Authorization:`Bot ${BOT_TOKEN}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(`Discord API ${r.status}: ${text.slice(0,300)}`);return text?JSON.parse(text):{};}
async function callback(i:any,p:any){return fetch(`https://discord.com/api/v10/interactions/${i.id}/${i.token}/callback`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p),cache:"no-store"});}
async function followup(i:any,p:any){if(!APPLICATION_ID)throw new Error("Discord application ID is not configured");const r=await fetch(`https://discord.com/api/v10/webhooks/${APPLICATION_ID}/${i.token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p),cache:"no-store"});if(!r.ok)throw new Error(`Discord followup ${r.status}: ${(await r.text()).slice(0,300)}`);}
function opts(i:any,n:string){return(i?.data?.options||[]).find((x:any)=>x?.name===n);}
function modalValues(i:any):Record<string,string>{const o:Record<string,string>={};for(const row of i?.data?.components||[])for(const c of row?.components||[])o[c.custom_id]=String(c.value||"");return o;}
function approveModal(requestId:string,signature:string,messageId:string){return{type:9,data:{custom_id:`qac:${requestId}:${signature.slice(0,16)}:${messageId}`,title:"Confirm Quota Approval",components:[{type:1,components:[{type:4,custom_id:"confirm",label:"Type APPROVE to confirm",style:1,required:true,min_length:7,max_length:7,placeholder:"APPROVE"}]}]}};}
function rejectModal(requestId:string,signature:string,messageId:string){return{type:9,data:{custom_id:`qrj:${requestId}:${signature.slice(0,16)}:${messageId}`,title:"Reject Quota",components:[{type:1,components:[{type:4,custom_id:"reason",label:"Reason for rejection",style:2,required:true,min_length:2,max_length:1000,placeholder:"Explain why this quota is being rejected"}]}]}};}
async function registerCommands(){if(!APPLICATION_ID||!BOT_TOKEN)throw new Error("Discord application credentials are not configured");const base=`/applications/${APPLICATION_ID}/guilds/${STAFF_GUILD_ID}/commands`;const wanted=[{name:"quota-submit",description:"Submit staff quota with a proof image",type:1,default_member_permissions:null,options:[{type:4,name:"minutes",description:"Quota completed in minutes",required:true,min_value:1,max_value:100000},{type:11,name:"proof",description:"Attach the proof image directly",required:true},{type:3,name:"notes",description:"Optional notes for Logistics",required:false,max_length:1000}]},{name:"quota-leaderboard",description:"Show the live quota leaderboard in Discord",type:1,default_member_permissions:null,options:[]}];const existing=await api(base);for(const c of Array.isArray(existing)?existing:[])if(c.name==="quota"&&c.id)await api(`${base}/${c.id}`,{method:"DELETE"});for(const w of wanted){const c=(Array.isArray(existing)?existing:[]).find((x:any)=>x.name===w.name);if(c?.id)await api(`${base}/${c.id}`,{method:"PATCH",body:JSON.stringify(w)});else await api(base,{method:"POST",body:JSON.stringify(w)});}}
async function review(r:QuotaRequest,displayName:string){const s=sig(r);return api(`/channels/${QUOTA_CHANNEL_ID}/messages`,{method:"POST",body:JSON.stringify({content:`<@&${LOGISTICS_ROLE_ID}>`,embeds:[{title:"Quota Submission — Pending Review",description:`<@${r.userId}> submitted a quota for Logistics review.`,fields:[{name:"Request ID",value:r.id},{name:"Member",value:`<@${r.userId}> (${r.username})`,inline:true},{name:"Display Name",value:displayName||r.username,inline:true},{name:"Quota (minutes)",value:`${r.quota} min`,inline:true},{name:"Proof",value:`[${r.proofName||"View proof image"}](${r.proof})`},{name:"Notes",value:r.notes||"—"}],image:{url:r.proof},footer:{text:"QUSM Quota System • Staff Team"},timestamp:r.createdAt}],components:[{type:1,components:[{type:2,style:3,label:"Approve & Add Minutes",custom_id:`quota:approve:${r.id}:${s}`},{type:2,style:4,label:"Reject",custom_id:`quota:reject:${r.id}:${s}`}]}],allowed_mentions:{users:[r.userId],roles:[LOGISTICS_ROLE_ID]}})});}
async function approvalLog(r:QuotaRequest,by:string,name:string){const users=[...new Set([r.userId,by])];return api(`/channels/${QUOTA_LOG_CHANNEL_ID}/messages`,{method:"POST",body:JSON.stringify({content:`<@&${LOGISTICS_ROLE_ID}>`,embeds:[{title:"Quota Approved",description:`<@${r.userId}> quota has been approved and added to the Google Staff Database.`,color:0x57f287,fields:[{name:"Staff Member",value:`<@${r.userId}> (${r.username})`,inline:true},{name:"Minutes Added",value:`${r.quota} min`,inline:true},{name:"Approved By",value:`<@${by}> (${name})`,inline:true},{name:"Request ID",value:r.id},{name:"Proof",value:`[${r.proofName||"View proof image"}](${r.proof})`},{name:"Notes",value:r.notes||"—"}],image:{url:r.proof},footer:{text:"QUSM Quota System • Approval Log"},timestamp:new Date().toISOString()}],allowed_mentions:{users,roles:[LOGISTICS_ROLE_ID]}})});}
async function rejectionLog(r:QuotaRequest,reason:string,by:string,name:string){const users=[...new Set([r.userId,by])];return api(`/channels/${QUOTA_LOG_CHANNEL_ID}/messages`,{method:"POST",body:JSON.stringify({content:`<@&${LOGISTICS_ROLE_ID}>`,embeds:[{title:"Quota Rejected",description:`<@${r.userId}> quota submission has been rejected by Logistics.`,color:0xed4245,fields:[{name:"Staff Member",value:`<@${r.userId}> (${r.username})`,inline:true},{name:"Quota Submitted",value:`${r.quota} min`,inline:true},{name:"Rejected By",value:`<@${by}> (${name})`,inline:true},{name:"Request ID",value:r.id},{name:"Reason",value:reason},{name:"Proof",value:`[${r.proofName||"View proof image"}](${r.proof})`},{name:"Notes",value:r.notes||"—"}],image:{url:r.proof},footer:{text:"QUSM Quota System • Rejection Log"},timestamp:new Date().toISOString()}],allowed_mentions:{users,roles:[LOGISTICS_ROLE_ID]}})});}
async function dmReject(uid:string,reason:string,minutes:number){const dm=await api("/users/@me/channels",{method:"POST",body:JSON.stringify({recipient_id:uid})});await api(`/channels/${dm.id}/messages`,{method:"POST",body:JSON.stringify({content:`❌ Your **${minutes} minute** quota submission has been rejected by Logistics.\n\n**Reason:** ${reason}`})});}
async function messageData(messageId:string,requestId:string,signature:string){const m=await api(`/channels/${QUOTA_CHANNEL_ID}/messages/${messageId}`);const f=m?.embeds?.[0]?.fields;if(!Array.isArray(f))return null;const v=Object.fromEntries(f.map((x:any)=>[String(x.name),String(x.value||"")]));const member=String(v.Member||"");const uid=member.match(/^<@(\d+)>/)?.[1];const userMatch=member.match(/^<@\d+>\s*\(([^\n]*)\)$/);const username=userMatch?.[1]?.trim()||"";const minutes=Number(String(v["Quota (minutes)"]||"").replace(/\s*min(?:utes?)?\s*$/i,""));const proofField=String(v.Proof||"");const proof=proofField.match(/\((https?:\/\/[^)]+)\)/i)?.[1]||proofField;const proofName=proofField.match(/^\[([^\]]+)\]/)?.[1]||"Proof image";if(v["Request ID"]!==requestId||!uid||!username||!Number.isFinite(minutes)||minutes<=0||!/^https?:\/\//i.test(proof)||sig({id:requestId,userId:uid,username,quota:minutes,proof,proofName,notes:v.Notes==="—"?"":String(v.Notes||""),createdAt:String(m.timestamp||"")})!==signature)return null;const button=`quota:approve:${requestId}:${signature}`;const pending=m?.embeds?.[0]?.title==="Quota Submission — Pending Review"&&m?.components?.some((row:any)=>row?.components?.some((c:any)=>c?.custom_id===button));if(!pending)return null;return{message:m,request:{id:requestId,userId:uid,username,quota:minutes,proof,proofName,notes:v.Notes==="—"?"":String(v.Notes||""),createdAt:String(m.timestamp||"")}};}
export async function GET(){try{await registerCommands();return response({success:true,commands:["/quota-submit","/quota-leaderboard"]});}catch(e){console.error("[quota] command registration failed",e);return response({success:false,error:e instanceof Error?e.message:"unknown error"},500);}}
export async function POST(request:Request){const body=await request.text();if(!valid(body,request.headers.get("x-signature-timestamp")||"",request.headers.get("x-signature-ed25519")||""))return response({error:"invalid signature"},401);let i:any;try{i=JSON.parse(body);}catch{return response({error:"invalid json"},400);}console.info("[quota] interaction received",{interactionId:i.id,interactionType:i.type,userId:i?.member?.user?.id||i?.user?.id,customId:i?.data?.custom_id||""});if(i.type===1)return response({type:1});if(i.guild_id!==STAFF_GUILD_ID)return response(eph("This quota system is only available in the Staff Team server."));
if(i.type===2&&i.data?.name==="quota-leaderboard"){if(!has(i,STAFF_ROLE_ID))return response(eph("You need the Staff Team server staff role to view the quota leaderboard."));try{await callback(i,{type:5,data:{flags:64}});const rows=await getQuotaLeaderboard();const embeds:any[]=[];for(let n=0;n<rows.length;n+=25){const c=rows.slice(n,n+25);embeds.push({title:n===0?"QUSM Quota Leaderboard":"QUSM Quota Leaderboard — Continued",description:c.map((r:any,j:number)=>`${n+j+1}. **${r.username}** — ${r.minutes} min${r.rank?` · ${r.rank}`:""}`).join("\n"),color:0xd4af37});}await followup(i,{content:rows.length?undefined:"No staff quota records were found in the Google Staff Database.",embeds:embeds.slice(0,10),flags:64});}catch(e){console.error("[quota] leaderboard failed",e);}return new Response(null,{status:204});}
if(i.type===2&&i.data?.name==="quota-submit"){if(!has(i,STAFF_ROLE_ID))return response(eph("You need the Staff Team role to submit quota."));try{await callback(i,{type:5,data:{flags:64}});const minutes=Number(opts(i,"minutes")?.value);const proofId=String(opts(i,"proof")?.value||"");const notes=String(opts(i,"notes")?.value||"").trim();const a=i?.data?.resolved?.attachments?.[proofId];const proof=String(a?.url||"");const proofName=String(a?.filename||"Proof image");const type=String(a?.content_type||"").toLowerCase();if(!Number.isFinite(minutes)||minutes<=0||minutes>100000||!proof||(type&&!type.startsWith("image/")))return followup(i,{content:"Invalid quota submission. Minutes must be positive and proof must be an image.",flags:64});const uid=String(i?.member?.user?.id||i?.user?.id||"");const username=String(i?.member?.user?.username||i?.user?.username||"").trim();const displayName=String(i?.member?.nick||i?.member?.user?.global_name||username).trim();const r:QuotaRequest={id:randomUUID(),userId:uid,username,quota:Math.round(minutes),proof,proofName,notes,createdAt:new Date().toISOString()};await createQuotaRequest({requestId:r.id,userId:r.userId,username:r.username,minutes:r.quota,signature:sig(r)});const m=await review(r,displayName);await attachQuotaMessage(r.id,String(m.id));await followup(i,{content:`✅ Your ${r.quota} minute quota was submitted to Logistics for review.`,flags:64});}catch(e){console.error("[quota] submit failed",{interactionId:i.id,error:e});try{await followup(i,{content:`⚠️ Could not submit your quota: ${e instanceof Error?e.message:"unknown error"}`,flags:64});}catch{}}return new Response(null,{status:204});}
const customId=String(i?.data?.custom_id||"");
if(i.type===3){const a=customId.match(/^quota:approve:([0-9a-f-]{36}):([0-9a-f]{24})$/i);if(a){const requestId=a[1],signature=a[2].toLowerCase(),messageId=String(i?.message?.id||"");console.info("[quota] approve button received",{interactionId:i.id,requestId,userId:i?.member?.user?.id});if(!has(i,LOGISTICS_ROLE_ID)&&!has(i,TESTER_ROLE_ID))return response(eph("Only Logistics or an approved tester can approve quota."));if(String(i.channel_id)!==QUOTA_CHANNEL_ID||!messageId)return response(eph("⚠️ Invalid quota review message."));return response(approveModal(requestId,signature,messageId));}const r=customId.match(/^quota:reject:([0-9a-f-]{36}):([0-9a-f]{24})$/i);if(r){const requestId=r[1],signature=r[2].toLowerCase(),messageId=String(i?.message?.id||"");if(!has(i,LOGISTICS_ROLE_ID)&&!has(i,TESTER_ROLE_ID))return response(eph("Only Logistics or an approved tester can reject quota."));if(String(i.channel_id)!==QUOTA_CHANNEL_ID||!messageId)return response(eph("⚠️ Invalid quota review message."));return response(rejectModal(requestId,signature,messageId));}return response(eph("Unknown quota action."));}
if(i.type===5){const m=modalValues(i);const approval=i.data?.custom_id?.match(/^qac:([0-9a-f-]{36}):([0-9a-f]{16}):(\d+)$/i);if(approval){if(!has(i,LOGISTICS_ROLE_ID)&&!has(i,TESTER_ROLE_ID))return response(eph("Only Logistics or an approved tester can approve quota."));if(String(i.channel_id)!==QUOTA_CHANNEL_ID)return response(eph("⚠️ Invalid quota review channel."));if(String(m.confirm||"")!=="APPROVE")return response(eph("Approval cancelled. Type exactly APPROVE to confirm."));try{await callback(i,{type:5,data:{flags:64}});const requestId=approval[1];const signaturePrefix=approval[2].toLowerCase();const messageId=approval[3];const state=await getQuotaRequestState(requestId);if(state!=="pending")return followup(i,{content:`⚠️ This quota request is no longer pending (status: ${state||"not found"}).`,flags:64});const original=await messageData(messageId,requestId,signaturePrefix);if(!original)return followup(i,{content:"⚠️ This quota approval request is invalid, outdated, or no longer pending.",flags:64});const claim=await claimQuotaApproval(requestId);if(!claim)return followup(i,{content:"⚠️ This quota request is already being processed or has been completed.",flags:64});const approverId=String(i?.member?.user?.id||i?.user?.id||"");const approverName=String(i?.member?.nick||i?.member?.user?.global_name||i?.member?.user?.username||i?.user?.username||approverId);try{await processQuotaDirect({userId:original.request.userId,username:original.request.username,minutes:original.request.quota,requestId:original.request.id,proof:original.request.proof,approvedBy:approverId,approvedByUsername:approverName});await markQuotaApproved(requestId);await approvalLog(original.request,approverId,approverName);await api(`/channels/${QUOTA_CHANNEL_ID}/messages/${messageId}`,{method:"PATCH",body:JSON.stringify({components:[]})});await followup(i,{content:`✅ ${original.request.quota} minutes approved and added to the Staff Database.`,flags:64});}catch(e){console.error("[quota] approval execution failed",{interactionId:i.id,requestId,error:e});throw e;}}catch(e){console.error("[quota] approval failed",{interactionId:i.id,error:e});try{await followup(i,{content:`⚠️ Quota approval failed: ${e instanceof Error?e.message:"unknown error"}`,flags:64});}catch{}}return new Response(null,{status:204});}
const rejection=i.data?.custom_id?.match(/^qrj:([0-9a-f-]{36}):([0-9a-f]{16}):(\d+)$/i);if(rejection){if(!has(i,LOGISTICS_ROLE_ID)&&!has(i,TESTER_ROLE_ID))return response(eph("Only Logistics or an approved tester can reject quota."));if(String(i.channel_id)!==QUOTA_CHANNEL_ID)return response(eph("⚠️ Invalid quota review channel."));const reason=String(m.reason||"").trim();if(!reason)return response(eph("A rejection reason is required."));try{await callback(i,{type:5,data:{flags:64}});const requestId=rejection[1],signaturePrefix=rejection[2].toLowerCase(),messageId=rejection[3];const state=await getQuotaRequestState(requestId);if(state!=="pending")return followup(i,{content:`⚠️ This quota request is no longer pending (status: ${state||"not found"}).`,flags:64});const original=await messageData(messageId,requestId,signaturePrefix);if(!original)return followup(i,{content:"⚠️ This quota rejection request is invalid, outdated, or no longer pending.",flags:64});const rejected=await markQuotaRejected(requestId);if(!rejected)return followup(i,{content:"⚠️ This quota request is already being processed or has been completed.",flags:64});const approverId=String(i?.member?.user?.id||i?.user?.id||"");const approverName=String(i?.member?.nick||i?.member?.user?.global_name||i?.member?.user?.username||i?.user?.username||approverId);await rejectionLog(original.request,reason,approverId,approverName);await dmReject(original.request.userId,reason,original.request.quota);await api(`/channels/${QUOTA_CHANNEL_ID}/messages/${messageId}`,{method:"PATCH",body:JSON.stringify({components:[]})});await followup(i,{content:`❌ ${original.request.quota} minute quota rejected.`,flags:64});}catch(e){console.error("[quota] rejection failed",{interactionId:i.id,error:e});try{await followup(i,{content:`⚠️ Quota rejection failed: ${e instanceof Error?e.message:"unknown error"}`,flags:64});}catch{}}return new Response(null,{status:204});}
return response(eph("Unsupported quota interaction."));}
