import fs from "fs/promises";
import path from "path";
import { FBMRP_GUILD_ID } from "./discord-roles";
export type Content={org:any;announcements:any[];leadership:any[];divisions:any[];rules:any[];government:any[];ranks:any[];news:any[];media:any[];applications:any[]};
const filePath=path.join(process.cwd(),"data","content.json");
const defaults:Content={org:{name:"FBMRP",fullName:"Fort Bliss Military Roleplay",owner:"",coOwner:"",status:"active"},announcements:[],leadership:[],divisions:[],rules:[],government:[],ranks:[],news:[],media:[],applications:[]};
const CMS_CHANNEL="qusm-cms-data";
const bot=()=>process.env.DISCORD_BOT_TOKEN;
async function d(pathname:string,init?:RequestInit){const t=bot();if(!t)throw Error("Discord storage unavailable");return fetch(`https://discord.com/api/v10${pathname}`,{...init,headers:{Authorization:`Bot ${t}`,...(init?.headers||{})},cache:"no-store"})}
async function readRemote(){try{const r=await d(`/guilds/${FBMRP_GUILD_ID}/channels`);if(!r.ok)return null;const cs=await r.json();const ch=cs.find((c:any)=>c.type===0&&c.name===CMS_CHANNEL);if(!ch)return null;const m=await d(`/channels/${ch.id}/messages?limit=10`);if(!m.ok)return null;const ms=await m.json();const x=ms.find((m:any)=>m.author?.bot&&m.content?.startsWith("FBMRP_CMS:"));return x?JSON.parse(x.content.slice(10)):null}catch{return null}}
async function writeRemote(content:Content){const r=await d(`/guilds/${FBMRP_GUILD_ID}/channels`);if(!r.ok)throw Error("Discord channels unavailable");const cs=await r.json();let ch=cs.find((c:any)=>c.type===0&&c.name===CMS_CHANNEL);if(!ch){const cr=await d(`/guilds/${FBMRP_GUILD_ID}/channels`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:CMS_CHANNEL,type:0})});if(!cr.ok)throw Error("CMS channel cannot be created");ch=await cr.json()}const body=`FBMRP_CMS:${JSON.stringify(content)}`;if(body.length>2000)throw Error("CMS content exceeds Discord message limit");const m=await d(`/channels/${ch.id}/messages?limit=10`);if(m.ok){for(const x of await m.json())if(x.author?.bot&&x.content?.startsWith("FBMRP_CMS:"))await d(`/channels/${ch.id}/messages/${x.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:body})});else continue;return}const p=await d(`/channels/${ch.id}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:body})});if(!p.ok)throw Error("CMS write failed")}
export async function getContent():Promise<Content>{const remote=await readRemote();if(remote)return {...defaults,...remote};try{return {...defaults,...JSON.parse(await fs.readFile(filePath,"utf8"))}}catch{return defaults}}
export async function saveContent(content:Content){if(bot()){await writeRemote(content);return}await fs.mkdir(path.dirname(filePath),{recursive:true});await fs.writeFile(filePath,JSON.stringify(content,null,2),"utf8")}
