import { neon } from "@neondatabase/serverless";
import { getStaffDatabaseSnapshot, updateStaffRankInDatabase } from "@/lib/quota-sheets";
import { STAFF_GUILD_ID } from "@/lib/discord/quota/config";
const LOGS={management:"1551552375989342260",promotion:"1551552552468750417",discipline:"1551552704126386176"};
const AUTHORIZED_COS_ROLE_ID="1550747605091360788";
const RANK_LADDER=[
  {name:"Junior Moderator",roleId:"1539741693866283009"},
  {name:"Moderator",roleId:"1539736453007802451"},
  {name:"Senior Moderator",roleId:"1539741689584029726"},
  {name:"Junior Administrator",roleId:"1539736453016330303"},
  {name:"Administrator",roleId:"1539736453016330305"},
  {name:"Senior Administrator",roleId:"1539736453016330306"},
  {name:"Head of Administrator",roleId:"1539736453016330309"},
  {name:"Deputy Chief of Staff",roleId:"1545599457226137720"},
  {name:"Chief of Staff",roleId:"1539736453024849972"},
] as const;
const ranks=()=>RANK_LADDER.map(x=>x.name);
const db=()=>{const u=process.env.DATABASE_URL;if(!u)throw new Error("DATABASE_URL is not configured");return neon(u)};const arr=(v:any)=>Array.isArray(v)?v:[];const envNum=(k:string,d:number)=>{const x=Number(process.env[k]);return Number.isFinite(x)?Math.max(0,Math.floor(x)):d};
export type StaffProfile={userId:string;username:string;rank:string;status:string;merits:number;demerits:number;net:number;quotaMinutes:number;tickets:number;duties:any[];warnings:any[];strikes:any[];rankLocked:boolean;departments:any[];recognition:any[];promotionHistory:any[];demotionHistory:any[];staffHistory:any[];eligibility:{eligible:boolean;reasons:string[];rankLocked:boolean;configured:boolean};updatedAt:string|null};
async function init(){const q=db();await q`CREATE TABLE IF NOT EXISTS staff_profiles(user_id TEXT PRIMARY KEY,username TEXT NOT NULL,rank TEXT NOT NULL DEFAULT 'Unknown',status TEXT NOT NULL DEFAULT 'Active',merits INTEGER NOT NULL DEFAULT 0,demerits INTEGER NOT NULL DEFAULT 0,duties JSONB NOT NULL DEFAULT '[]'::jsonb,warnings JSONB NOT NULL DEFAULT '[]'::jsonb,strikes JSONB NOT NULL DEFAULT '[]'::jsonb,rank_locked BOOLEAN NOT NULL DEFAULT FALSE,departments JSONB NOT NULL DEFAULT '[]'::jsonb,recognition JSONB NOT NULL DEFAULT '[]'::jsonb,promotion_history JSONB NOT NULL DEFAULT '[]'::jsonb,demotion_history JSONB NOT NULL DEFAULT '[]'::jsonb,staff_history JSONB NOT NULL DEFAULT '[]'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await q`CREATE TABLE IF NOT EXISTS staff_point_transactions(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL,amount INTEGER NOT NULL,point_type TEXT NOT NULL,reason TEXT NOT NULL,issuer_id TEXT NOT NULL,issuer_username TEXT NOT NULL,source TEXT NOT NULL,related_action TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await q`CREATE TABLE IF NOT EXISTS staff_cases(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL,case_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',reason TEXT NOT NULL,created_by TEXT NOT NULL,created_by_username TEXT NOT NULL,decided_by TEXT,decided_by_username TEXT,payload JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),decided_at TIMESTAMPTZ)`;await q`CREATE TABLE IF NOT EXISTS staff_audit(id BIGSERIAL PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,reason TEXT,source TEXT NOT NULL,issuer_id TEXT,issuer_username TEXT,before_state JSONB,after_state JSONB,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
async function row(id:string){await init();const q=db();const r=await q`SELECT * FROM staff_profiles WHERE user_id=${id} LIMIT 1`;return r[0]||null}
const snap=(r:any)=>r?{username:r.username,rank:r.rank,status:r.status,merits:r.merits,demerits:r.demerits,rankLocked:r.rank_locked,departments:r.departments,warnings:r.warnings,strikes:r.strikes}:null;
async function audit(id:string,a:string,reason:string,source:string,issuerId:string,issuerUsername:string,before:any,after:any,metadata:any={}){const q=db();await q`INSERT INTO staff_audit(user_id,action,reason,source,issuer_id,issuer_username,before_state,after_state,metadata)VALUES(${id},${a},${reason||null},${source},${issuerId},${issuerUsername},${JSON.stringify(before)}::jsonb,${JSON.stringify(after)}::jsonb,${JSON.stringify(metadata)}::jsonb)`}
async function discord(path:string,init?:RequestInit){const t=process.env.DISCORD_BOT_TOKEN?.trim();if(!t)throw new Error("DISCORD_BOT_TOKEN is not configured");const r=await fetch(`https://discord.com/api/v10${path}`,{...init,headers:{Authorization:`Bot ${t}`,"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(`Discord API ${r.status}`);return r.status===204?null:r.json()}
async function log(channel:string,title:string,description:string){try{await discord(`/channels/${channel}/messages`,{method:"POST",body:JSON.stringify({embeds:[{title,description,timestamp:new Date().toISOString()}]})})}catch(e){console.warn("[staff-management] log failed",e)}}
export async function isHighcom(i:any){const id=String(i?.member?.user?.id||i?.user?.id||"");if(id&&id===process.env.DISCORD_SPECIAL_USER_ID?.trim())return true;const roles=arr(i?.member?.roles) as string[];return Boolean(roles.includes(AUTHORIZED_COS_ROLE_ID)||(process.env.QUSM_COS_ROLE_ID&&roles.includes(process.env.QUSM_COS_ROLE_ID))||(process.env.QUSM_HIGHCOM_ROLE_ID&&roles.includes(process.env.QUSM_HIGHCOM_ROLE_ID)))}
async function ensure(id:string,username:string,rank:string,forceRank=false){await init();const q=db();await q`INSERT INTO staff_profiles(user_id,username,rank)VALUES(${id},${username},${rank||"Unknown"})ON CONFLICT(user_id)DO UPDATE SET username=EXCLUDED.username,rank=CASE WHEN ${forceRank} OR staff_profiles.rank IN ('','Unknown') THEN EXCLUDED.rank ELSE staff_profiles.rank END,updated_at=NOW()`;return row(id)}
function rankEntry(name:string){return RANK_LADDER.find(x=>x.name.toLowerCase()===String(name||"").trim().toLowerCase())||null}
function eligibility(r:any,q:number,t:number){const reasons:string[]=[];const current=rankEntry(r.rank);if(r.rank_locked)reasons.push("Rank lock is active");const mn=envNum("QUSM_PROMOTION_MIN_NET_POINTS",0);if(Number(r.merits)-Number(r.demerits)<mn)reasons.push(`Net points below ${mn}`);const mq=envNum("QUSM_PROMOTION_MIN_QUOTA_MINUTES",0);if(q<mq)reasons.push(`Quota below ${mq} minutes`);const mt=envNum("QUSM_PROMOTION_MIN_TICKETS",0);if(t<mt)reasons.push(`Tickets below ${mt}`);if(arr(r.strikes).length)reasons.push("Active strike(s)");if(!current)reasons.push("Current rank is not in the configured rank ladder");else if(RANK_LADDER[RANK_LADDER.length-1].roleId===current.roleId)reasons.push("Chief of Staff is the highest configured rank");return{eligible:!reasons.length,reasons,rankLocked:Boolean(r.rank_locked),configured:true}}
async function discordUsername(id:string){try{const m=await discord(`/guilds/${STAFF_GUILD_ID}/members/${id}`) as any;return String(m?.user?.username||"").trim()}catch{return ""}}
export async function getStaffProfile(id:string):Promise<StaffProfile|null>{let r=await row(id);if(!r)return null;const snapshot=await getStaffDatabaseSnapshot();const liveUsername=await discordUsername(id);const lookupUsername=liveUsername||String(r.username||"").trim();const s=snapshot.find(x=>x.username.trim().toLowerCase()===lookupUsername.toLowerCase());if(s&&s.rank){if(String(r.username).trim()!==s.username.trim()||String(r.rank).trim().toLowerCase()!==s.rank.trim().toLowerCase()){const q=db();await q`UPDATE staff_profiles SET username=${s.username},rank=${s.rank},updated_at=NOW() WHERE user_id=${id}`;r=await row(id)}}const effectiveRank=s?.rank||String(r.rank||"Unknown");const effectiveProfile={...r,rank:effectiveRank};return{userId:String(r.user_id),username:String(r.username),rank:effectiveRank,status:String(r.status),merits:Number(r.merits)||0,demerits:Number(r.demerits)||0,net:(Number(r.merits)||0)-(Number(r.demerits)||0),quotaMinutes:s?.minutes||0,tickets:s?.tickets||0,duties:arr(r.duties),warnings:arr(r.warnings),strikes:arr(r.strikes),rankLocked:Boolean(r.rank_locked),departments:arr(r.departments),recognition:arr(r.recognition),promotionHistory:arr(r.promotion_history),demotionHistory:arr(r.demotion_history),staffHistory:arr(r.staff_history),eligibility:eligibility(effectiveProfile,s?.minutes||0,s?.tickets||0),updatedAt:r.updated_at?String(r.updated_at):null}}
export async function findDiscordStaff(username:string){const wanted=username.trim().toLowerCase();if(!wanted)return null;const m=await discord(`/guilds/${STAFF_GUILD_ID}/members/search?query=${encodeURIComponent(username.trim())}&limit=20`) as any[];const x=m.filter(v=>String(v?.user?.username||"").toLowerCase()===wanted);if(x.length!==1)return null;return{id:String(x[0].user.id),username:String(x[0].user.username),roles:arr(x[0].roles) as string[]}}
export async function openStaffByUsername(username:string){const m=await findDiscordStaff(username);if(!m)throw new Error(`No unique Discord username match for "${username}".`);const databaseRow=(await getStaffDatabaseSnapshot()).find(x=>x.username.trim().toLowerCase()===m.username.trim().toLowerCase());const databaseRank=databaseRow?.rank||"Unknown";await ensure(m.id,m.username,databaseRank);return getStaffProfile(m.id)}
export async function addPoints(id:string,amount:number,type:"merit"|"demerit",reason:string,issuerId:string,issuerUsername:string,source="manual"){if(!Number.isInteger(amount)||amount<=0)throw new Error("Points must be a positive whole number.");if(!reason.trim())throw new Error("A reason is required.");const r=await row(id);if(!r)throw new Error("Staff profile not found.");const before=snap(r),q=db(),merits=Number(r.merits)+(type==="merit"?amount:0),demerits=Number(r.demerits)+(type==="demerit"?amount:0);await q`UPDATE staff_profiles SET merits=${merits},demerits=${demerits},updated_at=NOW() WHERE user_id=${id}`;await q`INSERT INTO staff_point_transactions(user_id,amount,point_type,reason,issuer_id,issuer_username,source,related_action)VALUES(${id},${type==="merit"?amount:-amount},${type},${reason},${issuerId},${issuerUsername},${source},${type})`;await audit(id,type==="merit"?"merit_added":"demerit_added",reason,source,issuerId,issuerUsername,before,snap(await row(id)),{amount});if(type==="demerit")await discipline(id,issuerId,issuerUsername);return getStaffProfile(id)}
async function discipline(id:string,issuerId:string,issuerUsername:string){const r=await row(id);if(!r)return;const d=Number(r.demerits)||0,w=arr(r.warnings),q=db(),wt=envNum("QUSM_DEMERIT_WARNING_THRESHOLD",5),st=envNum("QUSM_DEMERIT_SERIOUS_THRESHOLD",10);if(d>=wt&&!w.length){const item={reason:`Automatic threshold reached at ${d} demerits`,issuerId,issuerUsername,createdAt:new Date().toISOString(),source:"automation"};await q`UPDATE staff_profiles SET warnings=${JSON.stringify([...w,item])}::jsonb,updated_at=NOW() WHERE user_id=${id}`;await audit(id,"warning_auto_issued",item.reason,"automation",issuerId,issuerUsername,snap(r),snap(await row(id)));await log(LOGS.discipline,"Automatic Warning",`<@${id}> reached **${d} demerits**.`)}if(d>=st){const p=await q`SELECT id FROM staff_cases WHERE user_id=${id} AND case_type='strike' AND status='pending' LIMIT 1`;if(!p.length){const x=await q`INSERT INTO staff_cases(user_id,case_type,reason,created_by,created_by_username,payload)VALUES(${id},'strike',${`Demerit threshold reached at ${d}`},${issuerId},${issuerUsername},${JSON.stringify({automatic:true,demerits:d})}::jsonb)RETURNING id`;await log(LOGS.discipline,"Strike Approval Required",`Case **#${x[0].id}** for <@${id}> requires HighCOM approval. No serious punishment was applied automatically.`)}}}
export async function addWarning(id:string,reason:string,issuerId:string,issuerUsername:string){if(!reason.trim())throw new Error("A reason is required.");const r=await row(id);if(!r)throw new Error("Staff profile not found.");const q=db(),items=[...arr(r.warnings),{reason,issuerId,issuerUsername,createdAt:new Date().toISOString(),source:"manual"}];await q`UPDATE staff_profiles SET warnings=${JSON.stringify(items)}::jsonb,updated_at=NOW() WHERE user_id=${id}`;await audit(id,"warning_added",reason,"manual",issuerId,issuerUsername,snap(r),snap(await row(id)));await log(LOGS.discipline,"Warning Added",`<@${id}> • ${reason}`);return getStaffProfile(id)}
export async function addRecognition(id:string,reason:string,issuerId:string,issuerUsername:string){if(!reason.trim())throw new Error("A reason is required.");const r=await row(id);if(!r)throw new Error("Staff profile not found.");const q=db(),items=[...arr(r.recognition),{reason,issuerId,issuerUsername,createdAt:new Date().toISOString()}];await q`UPDATE staff_profiles SET recognition=${JSON.stringify(items)}::jsonb,updated_at=NOW() WHERE user_id=${id}`;await audit(id,"recognition_added",reason,"manual",issuerId,issuerUsername,snap(r),snap(await row(id)));await log(LOGS.management,"Recognition Added",`<@${id}> • ${reason}`);return getStaffProfile(id)}
export async function setRankLock(id:string,locked:boolean,reason:string,issuerId:string,issuerUsername:string){const r=await row(id);if(!r)throw new Error("Staff profile not found.");const q=db(),before=snap(r);await q`UPDATE staff_profiles SET rank_locked=${locked},updated_at=NOW() WHERE user_id=${id}`;await audit(id,locked?"rank_lock_applied":"rank_lock_removed",reason,"manual",issuerId,issuerUsername,before,snap(await row(id)));await log(LOGS.promotion,locked?"Rank Lock Applied":"Rank Lock Removed",`<@${id}> • ${reason}`);return getStaffProfile(id)}
async function changeDiscordRank(id:string,oldRoleId:string,newRoleId:string){if(oldRoleId&&oldRoleId!==newRoleId)await discord(`/guilds/${STAFF_GUILD_ID}/members/${id}/roles/${oldRoleId}`,{method:"DELETE"});await discord(`/guilds/${STAFF_GUILD_ID}/members/${id}/roles/${newRoleId}`,{method:"PUT",body:"{}"})}
async function rollbackDiscordRank(id:string,oldRoleId:string,newRoleId:string){try{await discord(`/guilds/${STAFF_GUILD_ID}/members/${id}/roles/${newRoleId}`,{method:"DELETE"});if(oldRoleId)await discord(`/guilds/${STAFF_GUILD_ID}/members/${id}/roles/${oldRoleId}`,{method:"PUT",body:"{}"})}catch(e){console.warn("[staff-management] Discord rank rollback failed",e)}}
export async function changeRank(id:string,direction:1|-1,reason:string,issuerId:string,issuerUsername:string,override=false){const r=await row(id);if(!r)throw new Error("Staff profile not found.");const current=rankEntry(r.rank);if(!current)throw new Error(`Current database rank "${r.rank}" is not in the configured rank ladder.`);const index=RANK_LADDER.findIndex(x=>x.roleId===current.roleId),target=RANK_LADDER[index+direction];if(!target)throw new Error("Configured rank ladder does not allow this rank change.");return changeRankToRole(id,direction,target.roleId,reason,issuerId,issuerUsername,override)}
export async function changeRankToRole(id:string,direction:1|-1,roleId:string,reason:string,issuerId:string,issuerUsername:string,override=false){if(!reason.trim())throw new Error("A reason is required.");const r=await row(id);if(!r)throw new Error("Staff profile not found.");const p=await getStaffProfile(id);if(!p)throw new Error("Staff profile not found.");if(direction===1&&!override&&!p.eligibility.eligible)throw new Error(`Promotion blocked: ${p.eligibility.reasons.join("; ")}`);if(direction===1&&!override&&r.rank_locked)throw new Error("Promotion blocked: rank lock is active.");const current=rankEntry(r.rank);if(!current)throw new Error(`Current database rank "${r.rank}" is not in the configured rank ladder.`);const index=RANK_LADDER.findIndex(x=>x.roleId===current.roleId),target=RANK_LADDER[index+direction];if(!target)throw new Error("Configured rank ladder does not allow this rank change.");if(String(roleId)!==String(target.roleId))throw new Error(`Invalid rank selection. ${direction===1?"Promotion":"demotion"} from ${current.name} must go to ${target.name}.`);const rs=await discord(`/guilds/${STAFF_GUILD_ID}/roles`) as any[];const targetRole=rs.find(x=>String(x.id)===String(target.roleId));if(!targetRole)throw new Error(`Configured Discord role for rank "${target.name}" was not found.`);if(targetRole.managed)throw new Error("The configured rank role is managed by Discord/integration and cannot be assigned.");const oldRole=rs.find(x=>String(x.id)===String(current.roleId));const before=snap(r);await changeDiscordRank(id,String(oldRole?.id||current.roleId),String(target.roleId));let sheetUpdated=false;try{await updateStaffRankInDatabase(r.username,target.name);sheetUpdated=true}catch(e){await rollbackDiscordRank(id,String(oldRole?.id||current.roleId),String(target.roleId));throw e}const q=db(),item={from:r.rank,to:target.name,roleId:String(target.roleId),reason,issuerId,issuerUsername,createdAt:new Date().toISOString(),override};if(direction===1)await q`UPDATE staff_profiles SET rank=${target.name},promotion_history=${JSON.stringify([...arr(r.promotion_history),item])}::jsonb,updated_at=NOW() WHERE user_id=${id}`;else await q`UPDATE staff_profiles SET rank=${target.name},demotion_history=${JSON.stringify([...arr(r.demotion_history),item])}::jsonb,updated_at=NOW() WHERE user_id=${id}`;await audit(id,direction===1?"promoted":"demoted",reason,"manual",issuerId,issuerUsername,before,snap(await row(id)),{override,roleId:String(target.roleId),staffDatabaseUpdated:sheetUpdated});await log(LOGS.promotion,direction===1?"Promotion Completed":"Demotion Completed",`<@${id}> **${r.rank} → ${target.name}**\nRole: <@&${target.roleId}>\nStaff Database: **Updated**\nReason: ${reason}${override?"\nOverride: Yes":""}`);return getStaffProfile(id)}
export async function createCase(id:string,type:string,reason:string,issuerId:string,issuerUsername:string,payload:any={}){await init();const q=db(),r=await q`INSERT INTO staff_cases(user_id,case_type,reason,created_by,created_by_username,payload)VALUES(${id},${type},${reason},${issuerId},${issuerUsername},${JSON.stringify(payload)}::jsonb)RETURNING id`;await log(LOGS.discipline,"HighCOM Approval Required",`Case **#${r[0].id}** • <@${id}> • **${type}**\n${reason}`);return Number(r[0].id)}
export async function decideCase(caseId:number,decision:"approved"|"denied",issuerId:string,issuerUsername:string){await init();const q=db();const rows=await q`SELECT * FROM staff_cases WHERE id=${caseId} AND status='pending' LIMIT 1`;if(!rows.length)throw new Error("Approval case is no longer pending.");const c=rows[0];await q`UPDATE staff_cases SET status=${decision},decided_by=${issuerId},decided_by_username=${issuerUsername},decided_at=NOW() WHERE id=${caseId} AND status='pending'`;if(decision==="approved"&&c.case_type==="strike"){const r=await row(String(c.user_id));if(r){const strikes=[...arr(r.strikes),{reason:c.reason,issuerId,issuerUsername,caseId,createdAt:new Date().toISOString()}];await q`UPDATE staff_profiles SET strikes=${JSON.stringify(strikes)}::jsonb,updated_at=NOW() WHERE user_id=${c.user_id}`}}await audit(String(c.user_id),`case_${decision}`,String(c.reason),"approval",issuerId,issuerUsername,null,null,{caseId,caseType:c.case_type});return getStaffProfile(String(c.user_id))}
export async function listPendingCases(id?:string){await init();const q=db();return id?q`SELECT * FROM staff_cases WHERE user_id=${id} AND status='pending' ORDER BY created_at DESC LIMIT 20`:q`SELECT * FROM staff_cases WHERE status='pending' ORDER BY created_at DESC LIMIT 50`}
export async function syncProfiles(issuerId:string,issuerUsername:string){const rows=await getStaffDatabaseSnapshot(),out={created:0,updated:0,unmatched:[] as string[]};for(const r of rows){const m=await findDiscordStaff(r.username);if(!m){out.unmatched.push(r.username);continue}const existing=await row(m.id);await ensure(m.id,m.username,r.rank||"Unknown",true);if(existing)out.updated++;else out.created++;await audit(m.id,existing?"profile_sync_updated":"profile_sync_created","Staff Database synchronization","profile-sync",issuerId,issuerUsername,existing?snap(existing):null,snap(await row(m.id)),{databaseRank:r.rank,quotaMinutes:r.minutes,tickets:r.tickets})}return out}
