import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import "./staff.css";
import { FBMRP_GUILD_ID, SPECIAL_OWNER_ID, getAccessLevel, getPermissions, type DiscordGuildRole } from "@/lib/discord-roles";
import { DISCORD_SESSION_COOKIE, readDiscordSession } from "@/lib/discord-session";
const cards = [["Website Content","Edit leadership, divisions, CoC and site information.","site:edit","org"],["Section Studio","Create new information sections, stories, galleries, briefings and CTAs with live preview.","site:edit","builder"],["Announcements","Manage public announcements and automatic Discord feed.","announcements:manage","announcements"],["Calendar","Create and manage official FBMRP events.","calendar:manage","calendar"],["Developer Media","Publish approved developer images and media.","developer:publish","media"],["Audit Log","View the immutable record of staff changes and publishing activity.","site:read","audit-log"]] as const;
const accessGuide = [["Owner","Owner, Co-Owner, Chairman, Vice Chairman, OFC Admin","Everything: site, leadership, divisions, announcements, calendar, developer publishing, applications, media and full admin."],["Ownership","Head Management, Head Operations, Head Administration, Community Affairs, CEO, Head Development","Site, leadership, divisions, announcements, calendar, applications and media."],["Senior Leadership","General Manager, Head Department, Senior Management","Leadership, announcements, calendar and applications."],["Developer","Developer Posts","Developer publishing and media."],["Aide","Aides","Verified staff portal access; no management permission currently."],["Staff","Staff","Verified staff portal access; no management permission currently."],["Member","All other members","Public/member access only."]] as const;
async function getLiveAccess(){const session=readDiscordSession((await cookies()).get(DISCORD_SESSION_COOKIE)?.value);if(!session)return null;if(session.id===SPECIAL_OWNER_ID)return {session,access:"special-user" as const,permissions:getPermissions("special-user")};const botToken=process.env.DISCORD_BOT_TOKEN;if(!botToken)return {session,access:"member" as const,permissions:getPermissions("member")};try{const headers={Authorization:`Bot ${botToken}`};const [mr,rr]=await Promise.all([fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/members/${session.id}`,{headers,cache:"no-store"}),fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/roles`,{headers,cache:"no-store"})]);if(!mr.ok||!rr.ok)return {session,access:"member" as const,permissions:getPermissions("member")};const member=await mr.json() as {roles?:string[]};const guildRoles=await rr.json() as DiscordGuildRole[];const roleIds=member.roles??[];const access=getAccessLevel(session.id,roleIds,guildRoles);return {session:{...session,roles:roleIds},access,permissions:getPermissions(access)};}catch{return {session,access:"member" as const,permissions:getPermissions("member")}}}
export default async function StaffDashboard(){const auth=await getLiveAccess();if(!auth)redirect("/authorize?next=/staff");if(auth.access==="member")redirect("/?auth=staff_required");const visibleCards=cards.filter(([, , permission])=>auth.permissions.includes(permission)||auth.permissions.includes("admin:all"));return <main className="staff-page"><div className="staff-shell"><div className="staff-top"><div><span className="eyebrow">FBMRP STAFF PORTAL · DISCORD VERIFIED</span><h1>Command Center</h1><p>Signed in as <strong>{auth.session.username||"Discord user"}</strong></p></div><div className="staff-top-actions"><span className="access-badge">{auth.access.replaceAll("-"," ")}</span><form action="/api/auth/logout" method="post"><button type="submit" className="staff-logout">Log out</button></form></div></div><section className="staff-grid">{visibleCards.map(([title,description,permission,section])=><article className="staff-card" key={title}><span className="card-arrow">↗</span><h2>{title}</h2><p>{description}</p><a className="staff-button" href={section==="builder"?"/admin/builder":`/admin?section=${section}`}>Open</a></article>)}</section><section className="access-guide"><div className="access-guide-head"><span className="eyebrow">PERMISSION REFERENCE</span><h2>Who can access what?</h2><p>Access is determined from live Discord Role IDs. Changing a Discord role name does not change website permissions.</p></div><div className="access-guide-table"><div className="access-row access-header"><strong>Access level</strong><strong>Discord roles</strong><strong>Website access</strong></div>{accessGuide.map(([level,roles,description])=><div className="access-row" key={level}><strong>{level}</strong><span>{roles}</span><span>{description}</span></div>)}</div></section>{!visibleCards.length&&<section className="staff-card"><h2>Read-only staff access</h2><p>Your Discord role is verified, but it does not include a management permission.</p></section>}</div></main>}
