import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {FBMRP_GUILD_ID,getAccessLevel,can,type DiscordGuildRole} from "@/lib/discord-roles";
import {readContent,writeContent} from "@/lib/content-store";
type Announcement={id:string;title:string;body:string;published:boolean;createdAt:string;updatedAt:string;discordMessageId?:string};
async function auth(){const raw=(await cookies()).get("fbmrp_discord_user")?.value,t=process.env.DISCORD_BOT_TOKEN;if(!raw||!t)return false;try{const s=JSON.parse(raw);if(!s.id)return false;const h={Authorization:`Bot ${t}`};const[m,r]=await Promise.all([fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/members/${s.id}`,{headers:h,cache:"no-store"}),fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/roles`,{headers:h,cache:"no-store"})]);if(!m.ok||!r.ok)return false;return can(getAccessLevel(s.id,(await m.json()).roles||[],await r.json() as DiscordGuildRole[]),"announcements:manage")}catch{return false}}
async function publish(a:Announcement){const token=process.env.DISCORD_BOT_TOKEN,channel=process.env.DISCORD_ANNOUNCEMENTS_CHANNEL_ID;if(!token||!channel)throw Object.assign(new Error("Discord announcements are not configured"),{status:503});const r=await fetch(`https://discord.com/api/v10/channels/${channel}/messages`,{method:"POST",headers:{Authorization:`Bot ${token}`,"Content-Type":"application/json"},body:JSON.stringify({content:`**${a.title}**\n\n${a.body}`})});if(r.status===429){const retry=Number(r.headers.get("retry-after")||"0");throw Object.assign(new Error(`Discord is rate-limited. Retry after ${Math.ceil(retry)} seconds.`),{status:429})}if(r.status===401)throw Object.assign(new Error("Discord bot authentication failed"),{status:502});if(r.status===403)throw Object.assign(new Error("Discord bot lacks permission to post in the announcements channel"),{status:502});if(r.status===404)throw Object.assign(new Error("Announcements channel was not found"),{status:502});if(!r.ok)throw Object.assign(new Error(`Discord publishing failed (${r.status})`),{status:502});return(await r.json()).id}
export async function GET(){try{return NextResponse.json((await readContent()).announcements||[])}catch{return NextResponse.json({error:"Announcements unavailable"},{status:503})}}
export async function POST(req:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:403});try{const b=await req.json();if(!b||typeof b.title!=="string"||typeof b.body!=="string"||!b.title.trim()||!b.body.trim())return NextResponse.json({error:"Title and body are required"},{status:400});const now=new Date().toISOString();const a:Announcement={id:crypto.randomUUID(),title:b.title.trim(),body:b.body.trim(),published:Boolean(b.published),createdAt:now,updatedAt:now};if(a.published)a.discordMessageId=await publish(a);const c=await readContent();c.announcements=[...(c.announcements||[]),a];await writeContent(c);return NextResponse.json(a,{status:201})}catch(e:any){return NextResponse.json({error:e?.message||"Announcement persistence failed"},{status:e?.status||503})}}
export async function PATCH(req:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:403});try{const b=await req.json();if(!b?.id)return NextResponse.json({error:"Missing id"},{status:400});const c=await readContent(),i=(c.announcements||[]).findIndex((x:any)=>x.id===b.id);if(i<0)return NextResponse.json({error:"Not found"},{status:404});const old=c.announcements[i] as Announcement,next={...old,title:typeof b.title==="string"?b.title.trim():old.title,body:typeof b.body==="string"?b.body.trim():old.body,published:typeof b.published==="boolean"?b.published:old.published,updatedAt:new Date().toISOString()};if(!next.title||!next.body)return NextResponse.json({error:"Title and body are required"},{status:400});if(next.published&&!old.published)next.discordMessageId=await publish(next);c.announcements[i]=next;await writeContent(c);return NextResponse.json(next)}catch(e:any){return NextResponse.json({error:e?.message||"Announcement persistence failed"},{status:e?.status||503})}}
export async function DELETE(req:Request){if(!(await auth()))return NextResponse.json({error:"Unauthorized"},{status:403});try{const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id"},{status:400});const c=await readContent(),before=c.announcements?.length||0;c.announcements=(c.announcements||[]).filter((x:any)=>x.id!==id);if(c.announcements.length===before)return NextResponse.json({error:"Not found"},{status:404});await writeContent(c);return NextResponse.json({ok:true})}catch(e:any){return NextResponse.json({error:e?.message||"Announcement persistence failed"},{status:503})}}
