import {NextResponse} from "next/server";
import {cookies} from "next/headers";
import {FBMRP_GUILD_ID,getAccessLevel,can,type DiscordGuildRole} from "@/lib/discord-roles";
import {readContent,writeContent} from "@/lib/content-store";
async function access(){const raw=(await cookies()).get("fbmrp_discord_user")?.value,t=process.env.DISCORD_BOT_TOKEN;if(!raw||!t)return false;try{const s=JSON.parse(raw),h={Authorization:`Bot ${t}`};const[m,r]=await Promise.all([fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/members/${s.id}`,{headers:h,cache:"no-store"}),fetch(`https://discord.com/api/v10/guilds/${FBMRP_GUILD_ID}/roles`,{headers:h,cache:"no-store"})]);if(!m.ok||!r.ok)return false;const member=await m.json(),roles=await r.json() as DiscordGuildRole[];return can(getAccessLevel(s.id,member.roles||[],roles),"media:manage")}catch{return false}}
export async function GET(){const c=await readContent();return NextResponse.json(c.media||[])}
export async function POST(req:Request){if(!(await access()))return NextResponse.json({error:"Unauthorized"},{status:403});const b=await req.json();if(!b.title||!b.imageUrl)return NextResponse.json({error:"Title and image URL are required"},{status:400});const c=await readContent();const item={id:crypto.randomUUID(),title:String(b.title).trim(),caption:String(b.caption||""),imageUrl:String(b.imageUrl).trim(),category:String(b.category||"general"),createdAt:new Date().toISOString()};c.media=[...(c.media||[]),item];await writeContent(c);return NextResponse.json(item,{status:201})}
export async function PATCH(req:Request){if(!(await access()))return NextResponse.json({error:"Unauthorized"},{status:403});const b=await req.json(),c=await readContent(),i=(c.media||[]).findIndex((x:any)=>x.id===b.id);if(i<0)return NextResponse.json({error:"Not found"},{status:404});c.media[i]={...c.media[i],...b,updatedAt:new Date().toISOString()};await writeContent(c);return NextResponse.json(c.media[i])}
export async function DELETE(req:Request){if(!(await access()))return NextResponse.json({error:"Unauthorized"},{status:403});const id=new URL(req.url).searchParams.get("id");const c=await readContent();c.media=(c.media||[]).filter((x:any)=>x.id!==id);await writeContent(c);return NextResponse.json({ok:true})}
