"use client";
import { motion } from "framer-motion";
import { ArrowUpRight, Play, Quote, Image as ImageIcon } from "lucide-react";

type Block={id:string;type:string;title?:string;body?:string;imageUrl?:string;imageAlt?:string;images?:string[];videoUrl?:string;buttonLabel?:string;buttonUrl?:string;value?:string;label?:string;embedUrl?:string};
type Section={id:string;slug:string;eyebrow?:string;title:string;description?:string;layout?:string;accent?:string;published?:boolean;order:number;blocks?:Block[]};
const gold="#d4b56a";
export default function CustomSections({sections}:{sections:Section[]}){const live=(sections||[]).filter(s=>s.published).sort((a,b)=>a.order-b.order);if(!live.length)return null;return <>{live.map((s,si)=><section key={s.id} id={s.slug||s.id} className="relative border-t border-white/10 py-24 md:py-36 overflow-hidden"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><div className="max-w-4xl"><span className="text-[9px] tracking-[.35em] text-[#d4b56a]">{s.eyebrow||String(si+6).padStart(2,"0")} / FBMR INFORMATION</span><h2 className="mt-5 text-5xl md:text-8xl font-semibold tracking-[-.07em]">{s.title}</h2>{s.description&&<p className="mt-7 max-w-2xl text-base leading-7 text-white/40">{s.description}</p>}</div><div className={`mt-16 grid gap-5 ${s.layout==="split"?"lg:grid-cols-2":s.layout==="grid"?"md:grid-cols-2 lg:grid-cols-3":"grid-cols-1"}`}>{(s.blocks||[]).map((b,i)=><BlockView key={b.id||i} b={b} i={i} layout={s.layout}/>)}</div></div></section>)}</>}
function BlockView({b,i,layout}:{b:Block;i:number;layout?:string}){return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-60px"}} transition={{duration:.55,delay:i*.05}} className={b.type==="divider"?"h-px bg-white/10 md:col-span-full":"relative overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[.025]"}>{b.type==="text"&&<div className="p-7 md:p-10"><h3 className="text-2xl md:text-3xl tracking-tight">{b.title}</h3><p className="mt-4 whitespace-pre-line text-sm md:text-base leading-7 text-white/45">{b.body}</p></div>}{b.type==="image"&&<><img src={b.imageUrl} alt={b.imageAlt||"FBMR"} className="w-full max-h-[620px] object-cover"/><div className="p-5"><h3 className="text-lg">{b.title}</h3><p className="mt-2 text-sm text-white/40">{b.body}</p></div></>}{b.type==="gallery"&&<div className="grid grid-cols-2 gap-px bg-white/10">{(b.images||[]).map((u,j)=><img key={j} src={u} alt="" className="aspect-square w-full object-cover bg-[#0b0d0b]"/>)}</div>}{b.type==="video"&&<a href={b.videoUrl} target="_blank" rel="noreferrer" className="group block relative aspect-video bg-black"><div className="absolute inset-0 grid place-items-center"><span className="grid h-16 w-16 place-items-center rounded-full border border-white/20 bg-white/10 group-hover:scale-110 transition"><Play fill="white" size={18}/></span></div><div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black to-transparent"><h3>{b.title||"Watch briefing"}</h3></div></a>}{b.type==="quote"&&<div className="p-8 md:p-12"><Quote className="mb-8 text-[#d4b56a]" size={28}/><p className="text-2xl md:text-4xl leading-tight tracking-[-.03em]">{b.body}</p><p className="mt-6 text-[9px] tracking-[.25em] text-white/30 uppercase">{b.title||"FBMR"}</p></div>}{b.type==="stats"&&<div className="p-8 md:p-10"><div className="text-5xl md:text-7xl text-[#d4b56a] tracking-[-.06em]">{b.value||"—"}</div><div className="mt-3 text-[9px] tracking-[.25em] text-white/35 uppercase">{b.label||"Metric"}</div></div>}{b.type==="cta"&&<div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 p-8 md:p-10"><div><h3 className="text-2xl">{b.title||"Continue"}</h3><p className="mt-2 text-sm text-white/40">{b.body}</p></div>{b.buttonUrl&&<a href={b.buttonUrl} className="inline-flex items-center gap-2 rounded-full bg-[#d4b56a] px-5 py-3 text-[9px] tracking-[.2em] text-black">{b.buttonLabel||"OPEN"}<ArrowUpRight size={14}/></a>}</div>}{b.type==="embed"&&<div className="p-4"><div className="mb-3 flex items-center gap-2 text-[9px] tracking-[.2em] text-white/30"><ImageIcon size={13}/> EMBED</div><a href={b.embedUrl} target="_blank" rel="noreferrer" className="text-sm text-[#d4b56a] break-all">{b.embedUrl}</a></div>}</motion.div>}
