"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ChevronDown, ChevronRight, Menu, Radio, X } from "lucide-react";
import { motion } from "framer-motion";

type Any = Record<string, any>;
const clean = (items: Any[] = []) => items.filter(x => x?.active !== false && x?.status !== "inactive" && x?.status !== "draft").sort((a,b) => Number(a?.order || 0) - Number(b?.order || 0));
const fade = { hidden:{opacity:0,y:24}, show:{opacity:1,y:0,transition:{duration:.6,ease:[.16,1,.3,1]}} } as const;

function Avatar({ src, name }: { src?: string; name: string }) {
  const [bad,setBad] = useState(false);
  if (!src || bad) return <div className="grid h-full w-full place-items-center bg-gradient-to-br from-[#1a201b] to-[#080a08]"><span className="text-4xl font-semibold text-white/15">{name?.[0]?.toUpperCase() || "F"}</span></div>;
  return <img src={src} alt="" onError={()=>setBad(true)} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>;
}
function Skeleton(){ return <div className="animate-pulse border border-white/10 bg-white/[.025] p-5"><div className="flex items-center gap-4"><div className="h-16 w-16 shrink-0 rounded-full bg-white/[.06]"/><div className="flex-1 space-y-2"><div className="h-2 w-16 rounded bg-white/[.06]"/><div className="h-4 w-2/3 rounded bg-white/[.06]"/><div className="h-2 w-1/2 rounded bg-white/[.05]"/></div></div><div className="mt-5 h-4 border-t border-white/[.06]"/></div>; }
function Profile({ person, role }: { person: Any; role: string }) {
  const status=String(person.status||"offline").toLowerCase();
  const dot=status==="online"?"bg-emerald-400":status==="idle"?"bg-amber-300":status==="dnd"?"bg-red-400":"bg-white/25";
  const [src,setSrc]=useState(person.avatar||"");
  const fallback=`https://cdn.discordapp.com/embed/avatars/${Number(String(person.id||"0").slice(-1))%5}.png`;
  useEffect(()=>setSrc(person.avatar||fallback),[person.avatar,person.id]);
  return <motion.article whileHover={{y:-3}} className="group min-w-0 overflow-hidden border border-white/10 bg-[#0b0e0c] p-5 transition hover:border-[#d4b56a]/35 hover:bg-[#10140f]"><div className="flex min-w-0 items-center gap-4"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-full border border-[#d4b56a]/30 bg-white/[.04]"><Avatar src={src||fallback} name={person.displayName||person.username||"F"}/><span className={`absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-[#0b0e0c] ${dot}`}/></div><div className="min-w-0 flex-1"><div className="font-mono text-[8px] tracking-[.2em] text-[#d4b56a]">{role}</div><h3 className="mt-1 break-words text-lg font-semibold leading-5">{person.displayName||person.username||"Profile unavailable"}</h3><p className="truncate text-xs text-white/35">@{person.username||"unknown"}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-white/[.07] pt-4 font-mono text-[8px] uppercase tracking-[.13em] text-white/30"><span className="flex items-center gap-2"><i className={`h-1.5 w-1.5 rounded-full ${dot}`}/>{status}</span><ChevronRight size={13} className="text-white/20 transition group-hover:translate-x-1 group-hover:text-[#d4b56a]"/></div></motion.article>;
}
function Empty({title}:{title:string}){return <div className="border border-dashed border-white/10 px-6 py-12 text-center"><div className="font-mono text-[9px] tracking-[.2em] text-[#d4b56a]">{title}</div><p className="mt-2 text-sm text-white/25">Nothing is published here yet.</p></div>}
function ContentGroup({ title, items }: { title:string; items:Any[] }) { return <div className="border border-white/10 bg-[#0b0e0c] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between border-b border-white/[.07] pb-4"><span className="font-mono text-[9px] tracking-[.2em] text-[#d4b56a]">{title}</span><span className="font-mono text-[8px] text-white/20">{String(items.length).padStart(2,"0")}</span></div>{items.length?<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><article key={x.id||i} className="border border-white/[.07] bg-white/[.015] p-5"><div className="font-mono text-[8px] text-[#d4b56a]/70">{String(i+1).padStart(2,"0")}</div><h3 className="mt-2 break-words text-sm font-semibold">{x.title||x.name||"Position"}</h3>{x.name&&x.title&&<p className="mt-1 text-xs text-white/40">{x.name}</p>}{x.description&&<p className="mt-2 text-xs leading-5 text-white/30">{x.description}</p>}</article>)}</div>:<Empty title={`NO ${title.toUpperCase()} PUBLISHED`}/>}</div> }

export default function FBMRExperience(){
 const [c,setC]=useState<Any>({}); const [p,setP]=useState<Any>({}); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [openOther,setOpenOther]=useState("leadership");
 useEffect(()=>{let alive=true;const load=async()=>{try{const [a,b]=await Promise.allSettled([fetch('/api/content',{cache:'no-store'}),fetch('/api/discord/leadership',{cache:'no-store'})]);if(!alive)return;if(a.status==='fulfilled'&&a.value.ok)setC(await a.value.json());if(b.status==='fulfilled'&&b.value.ok)setP(await b.value.json());}finally{if(alive)setLoading(false)}};void load();const t=setInterval(load,15000);return()=>{alive=false;clearInterval(t)}},[]);
 const org=c.org||{}; const announcements=useMemo(()=>clean(c.announcements||[]).filter(x=>x.published!==false).slice(0,3),[c.announcements]); const divisions=useMemo(()=>clean(c.divisions||[]),[c.divisions]); const events=useMemo(()=>clean(c.calendar||[]).slice(0,3),[c.calendar]);
 const owners=p.owner||[], chairs=p.chairman||[], coOwners=p.coOwner||[], vcms=p.viceChairman||[]; const other=[['leadership','Leadership CoC',c.cocLeadership||[]],['staff','Staff CoC',c.cocStaff||[]],['roleplay','Roleplay CoC',c.cocRoleplay||[]]] as const;
 return <main className="min-h-screen overflow-x-hidden bg-[#050706] text-[#f3f0e7] selection:bg-[#d4b56a] selection:text-black">
  <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_75%_12%,rgba(212,181,106,.12),transparent_30%),radial-gradient(circle_at_15%_55%,rgba(70,110,90,.10),transparent_28%)]"/>
  <nav className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#050706]/82 backdrop-blur-2xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 md:px-10"><a href="#home" className="font-black tracking-[-.05em] text-xl">FBMR<span className="text-[#d4b56a]">.</span></a><div className="hidden gap-7 text-[10px] tracking-[.2em] text-white/45 md:flex">{['INTEL','COMMAND','DIVISIONS','OPERATIONS','MEDIA','STORE'].map(x=><a key={x} href={'#'+x.toLowerCase()} className="transition hover:text-white">{x}</a>)}</div><a href="/staff" className="hidden rounded-full border border-white/15 px-4 py-2 text-[10px] tracking-widest transition hover:border-[#d4b56a] md:block">STAFF <ArrowRight size={13} className="inline"/></a><button className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-white/10 bg-[#070907] px-5 py-6 grid gap-5 text-xs tracking-widest md:hidden">{['intel','command','divisions','operations','media','store'].map(x=><a key={x} href={'#'+x} onClick={()=>setOpen(false)}>{x.toUpperCase()}</a>)}<a href="/staff">STAFF PORTAL</a></div>}</nav>
  <section id="home" className="relative flex min-h-[100svh] items-end"><div className="mx-auto w-full max-w-[1500px] px-5 pb-16 pt-32 md:px-10 md:pb-24"><motion.div initial="hidden" animate="show" variants={fade} className="max-w-5xl"><div className="mb-7 flex items-center gap-3 text-[9px] tracking-[.35em] text-[#d4b56a]"><span className="h-px w-10 bg-[#d4b56a]"/> FORT BLISS MILITARY ROLEPLAY</div><h1 className="text-[clamp(4rem,14vw,12.5rem)] font-semibold leading-[.78] tracking-[-.09em]">FORGED<br/><span className="text-[#d4b56a]">TO LEAD.</span></h1><p className="mt-10 max-w-xl text-base leading-7 text-white/45 md:text-lg">{org.heroDescription||'A disciplined military roleplay organization built around command, service, investigation and immersive operations.'}</p></motion.div><div className="mt-16 flex items-end justify-between border-t border-white/10 pt-5 text-[9px] tracking-[.2em] text-white/30"><span>FBMR // OFFICIAL NETWORK</span><span className="flex items-center gap-2"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/> SYSTEM OPERATIONAL</span></div></div></section>
  <section id="intel" className="relative border-t border-white/10 py-28 md:py-40"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><div className="mb-16 flex items-end justify-between"><div><span className="text-[9px] tracking-[.3em] text-[#d4b56a]">01 / INTELLIGENCE</span><h2 className="mt-5 text-5xl tracking-[-.06em] md:text-7xl">What matters<br/><span className="text-white/35">right now.</span></h2></div><Radio className="hidden text-[#d4b56a] md:block"/></div>{loading?<div className="grid gap-px bg-white/10 lg:grid-cols-3"><Skeleton/><Skeleton/><Skeleton/></div>:announcements.length?<div className="grid gap-px bg-white/10 lg:grid-cols-3">{announcements.map((x,i)=><motion.article initial="hidden" whileInView="show" viewport={{once:true}} variants={fade} key={x.id||i} className="group min-h-[300px] bg-[#080b09] p-7 transition hover:bg-[#0e130f] md:p-9"><span className="text-[10px] text-[#d4b56a]">0{i+1}</span><h3 className="mt-20 text-2xl md:text-3xl">{x.title||'Official announcement'}</h3><p className="mt-4 text-sm leading-6 text-white/40">{x.body||x.description||'No additional details have been published.'}</p><div className="mt-8 h-px w-0 bg-[#d4b56a] transition-all duration-700 group-hover:w-full"/></motion.article>)}</div>:<Empty title="NO ANNOUNCEMENTS"/>}</div></section>
  <section id="command" className="relative border-y border-white/10 py-28 md:py-40"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><div className="mb-16"><span className="text-[9px] tracking-[.3em] text-[#d4b56a]">02 / COMMAND STRUCTURE</span><h2 className="mt-5 text-5xl tracking-[-.06em] md:text-8xl">The people<br/><span className="text-white/35">behind FBMR.</span></h2><p className="mt-5 max-w-xl text-sm leading-6 text-white/35">The live Discord roles drive the official top command. CMS-managed Leadership, Staff and Roleplay CoC remain separate below so no existing command group is lost.</p></div>
   <div className="space-y-10">
    <motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><div className="mb-4 font-mono text-[9px] tracking-[.25em] text-[#d4b56a]">OVERSIGHT</div>{loading?<Skeleton/>:owners.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{owners.map((x:Any)=><Profile key={x.id} person={x} role="OWNER"/>)}</div>:<Empty title="NO OWNER PROFILE"/>}</motion.div>
    <motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><div className="mb-4 font-mono text-[9px] tracking-[.25em] text-[#d4b56a]">CO-OWNER</div>{loading?<Skeleton/>:coOwners.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{coOwners.map((x:Any)=><Profile key={x.id} person={x} role="CO-OWNER"/>)}</div>:<Empty title="NO CO-OWNER PROFILE"/>}</motion.div>
    <motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><div className="mb-4 font-mono text-[9px] tracking-[.25em] text-[#d4b56a]">CHAIRMAN BOARD</div>{loading?<Skeleton/>:chairs.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{chairs.map((x:Any)=><Profile key={x.id} person={x} role="CHAIRMAN"/>)}</div>:<Empty title="NO CHAIRMAN PROFILE"/>}</motion.div>
    <motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><div className="mb-4 font-mono text-[9px] tracking-[.25em] text-[#d4b56a]">VICE CHAIRMAN</div>{loading?<Skeleton/>:vcms.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{vcms.map((x:Any)=><Profile key={x.id} person={x} role="VICE CHAIRMAN"/>)}</div>:<Empty title="NO VCM PROFILE"/>}</motion.div>
    <div className="border-t border-white/10 pt-10"><button onClick={()=>setOpenOther(openOther?"":"leadership")} className="mb-4 flex w-full items-center justify-between border border-white/10 bg-[#0b0e0c] p-5 text-left"><span><span className="font-mono text-[9px] tracking-[.25em] text-[#d4b56a]">OTHER COMMAND STRUCTURES</span><strong className="mt-2 block text-xl">Leadership • Staff • Roleplay CoC</strong></span><ChevronDown className={`text-[#d4b56a] transition ${openOther?"rotate-180":""}`}/></button>{openOther&&<div className="space-y-3">{other.map(([key,title,list])=><div key={key} className="overflow-hidden border border-white/10 bg-[#0b0e0c]"><button onClick={()=>setOpenOther(openOther===key?"":key)} className="flex w-full items-center justify-between p-5 text-left"><span className="font-mono text-[9px] tracking-[.2em] text-white/55">{title}</span><ChevronDown size={16} className={`text-[#d4b56a] transition ${openOther===key?"rotate-180":""}`}/></button>{openOther===key&&<div className="border-t border-white/[.07] p-3"><ContentGroup title={title} items={clean(list)}/></div>}</div>)}</div>}</div>
   </div>
  </div></section>
  <section id="divisions" className="relative py-28 md:py-40"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><span className="text-[9px] tracking-[.3em] text-[#d4b56a]">03 / DIVISIONS</span><div className="mt-10">{divisions.length?divisions.map((x:Any,i:number)=><motion.a initial="hidden" whileInView="show" viewport={{once:true}} variants={fade} href={x.href||'#'} key={x.id||i} className="group flex items-center justify-between gap-6 border-t border-white/10 py-7 md:py-9"><div className="flex min-w-0 items-center gap-6 md:gap-12"><span className="text-[10px] text-white/20">{String(i+1).padStart(2,'0')}</span><h3 className="break-words text-3xl tracking-[-.05em] transition group-hover:text-[#d4b56a] md:text-6xl">{x.name||x.title||'Division'}</h3></div><ArrowRight className="shrink-0 text-white/20 transition group-hover:translate-x-1 group-hover:text-[#d4b56a]"/></motion.a>):<Empty title="NO DIVISIONS"/>}</div></div></section>
  <section id="operations" className="relative border-t border-white/10 py-28 md:py-40"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><span className="text-[9px] tracking-[.3em] text-[#d4b56a]">04 / OPERATIONS</span><div className="mt-12 grid gap-5 lg:grid-cols-3">{events.length?events.map((x:Any,i:number)=><article key={x.id||i} className="border border-white/10 bg-white/[.025] p-7 transition duration-500 hover:-translate-y-2"><div className="text-[10px] text-[#d4b56a]">{x.date||'DATE TBA'} / {x.time||'TIME TBA'}</div><h3 className="mt-16 text-3xl">{x.title||'FBMR Operation'}</h3><p className="mt-4 text-sm text-white/40">{x.description||'Official FBMR operation.'}</p><div className="mt-10 text-[9px] tracking-widest text-white/25">{x.location||'LOCATION TBA'}</div></article>):<div className="lg:col-span-3"><Empty title="NO UPCOMING OPERATIONS"/></div>}</div></div></section>
  <footer className="border-t border-white/10 py-10"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-5 px-5 text-[9px] tracking-[.2em] text-white/25 md:flex-row md:px-10"><span>FBMR // FORT BLISS MILITARY ROLEPLAY</span><span>WE SERVE. WE LEAD. WE ROLEPLAY.</span></div></footer>
 </main>;
}
