"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, ChevronRight, Menu, Shield, X } from "lucide-react";
import { motion } from "framer-motion";

type Item = Record<string, any>;
const active = (items: Item[] = []) => items.filter((x) => x?.active !== false && x?.status !== "inactive" && x?.status !== "draft").sort((a, b) => Number(a.order || 0) - Number(b.order || 0));

function Group({ title, items }: { title: string; items: Item[] }) {
  const rows = items.filter((x) => x.section === title);
  if (!rows.length) return null;
  return <section className="border-t border-white/10 pt-6 first:border-0">
    <div className="mb-2 flex items-center gap-4"><span className="font-mono text-[9px] tracking-[.28em] text-[#c7aa68]">{title}</span><span className="h-px flex-1 bg-white/[.06]" /></div>
    <div className="divide-y divide-white/[.06]">{rows.map((x, i) => <motion.article key={x.id || x.title} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .3, delay: i * .02 }} className="grid gap-4 py-6 md:grid-cols-[44px_270px_1fr]"><span className="font-mono text-[8px] text-white/25">{String(i + 1).padStart(2, "0")}</span><h3 className="text-lg font-semibold tracking-[-.02em] transition-colors group-hover:text-[#c7aa68]">{x.title}</h3><p className="text-sm leading-6 text-white/45">{x.description}</p></motion.article>)}</div>
  </section>;
}

export default function LiveHomeRevamp2() {
  const [c, setC] = useState<Item>({}); const [menu, setMenu] = useState(false);
  useEffect(() => { const load = async () => { try { const r = await fetch("/api/content", { cache: "no-store" }); if (r.ok) setC(await r.json()); } catch {} }; void load(); const t = setInterval(load, 15000); return () => clearInterval(t); }, []);
  const org = c.org || {}; const news = useMemo(() => active(c.announcements || []).slice(0, 4), [c.announcements]); const divisions = useMemo(() => active(c.divisions || []), [c.divisions]); const events = useMemo(() => active(c.calendar || []).slice(0, 4), [c.calendar]); const media = useMemo(() => active(c.media || []).slice(0, 6), [c.media]); const leadership = active(c.cocLeadership || []); const staff = active(c.cocStaff || []);
  return <main className="min-h-screen overflow-hidden bg-[#080a09] text-[#ece9df]">
    <div className="pointer-events-none fixed inset-0 opacity-[.12]" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px)", backgroundSize: "52px 52px" }} />
    <nav className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#080a09]/85 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center gap-3 font-mono text-[11px] tracking-[.2em]"><span className="h-2 w-2 rounded-full bg-[#c7aa68] shadow-[0_0_0_5px_rgba(199,170,104,.08)]" />QUSM</a><div className="hidden lg:flex gap-7 font-mono text-[9px] tracking-[.16em] text-white/40">{[["NEWS","news"],["COMMAND","command"],["DIVISIONS","divisions"],["OPERATIONS","operations"],["MEDIA","media"]].map(([a,b])=><a key={b} href={`#${b}`} className="hover:text-[#c7aa68]">{a}</a>)}</div><a href="/staff" className="hidden sm:block bg-[#c7aa68] px-4 py-3 font-mono text-[9px] tracking-[.12em] text-[#10110e]">STAFF PORTAL</a><button onClick={()=>setMenu(!menu)} className="lg:hidden p-2">{menu?<X size={20}/>:<Menu size={20}/>}</button></div>{menu&&<div className="grid gap-4 border-t border-white/10 bg-[#080a09] px-5 py-5 font-mono text-[10px]"><a href="#news">NEWS</a><a href="#command">COMMAND</a><a href="#divisions">DIVISIONS</a><a href="#operations">OPERATIONS</a><a href="#media">MEDIA</a><a href="/staff">STAFF PORTAL</a></div>}</nav>
    <header id="top" className="relative flex min-h-[92svh] items-end border-b border-white/10 px-5 pb-16 pt-36 sm:px-8 lg:px-12"><div className="mx-auto grid w-full max-w-7xl gap-14 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5}} className="mb-6 font-mono text-[9px] tracking-[.28em] text-[#c7aa68]">{org.fullName || "QUAVY'S UNITED STATES MILITARY"} / OFFICIAL</motion.div><motion.h1 initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:[.16,1,.3,1]}} className="font-sans text-[clamp(4rem,11vw,10rem)] font-semibold leading-[.82] tracking-[-.075em]">BUILT TO<br/><span className="text-[#c7aa68]">SERVE.</span></motion.h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/50 sm:text-lg">{org.heroDescription || "A structured military roleplay community built around organization, progression, leadership and immersive operations."}</p><a href="#command" className="mt-8 inline-flex items-center gap-3 bg-[#c7aa68] px-5 py-3.5 font-mono text-[9px] tracking-[.12em] text-[#10110e] transition hover:-translate-y-1">VIEW CHAIN OF COMMAND <ArrowRight size={13}/></a></div><div className="hidden border-l border-[#c7aa68]/30 pl-8 pb-2 lg:block"><div className="font-mono text-[8px] tracking-[.2em] text-white/25">SYSTEM STATUS</div><div className="mt-3 text-4xl tracking-[-.04em]">Operational.</div><div className="mt-8 grid grid-cols-2 gap-6 font-mono text-[8px] uppercase text-white/25"><div><b className="block text-3xl text-white">{divisions.length}</b>Divisions</div><div><b className="block text-3xl text-white">{leadership.length}</b>Command roles</div><div><b className="block text-3xl text-white">{news.length}</b>Updates</div><div><b className="block text-3xl text-white">{events.length}</b>Operations</div></div></div></div></header>
    <section id="news" className="border-b border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><Head n="01" label="NEWS" title={<>What changed.<br/><span>What matters.</span></>}/><div className="divide-y divide-white/10 border-y border-white/10">{news.map((x,i)=><article key={x.id||i} className="grid gap-5 py-7 md:grid-cols-[55px_1fr_140px] hover:bg-white/[.018]"><span className="font-mono text-[9px] text-[#c7aa68]">{String(i+1).padStart(2,"0")}</span><div><h3 className="text-2xl font-semibold">{x.title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">{x.body}</p></div><time className="font-mono text-[8px] text-white/25 md:text-right">{x.date||"OFFICIAL"}</time></article>)}</div></div></section>
    <section id="command" className="border-b border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><Head n="02" label="CHAIN OF COMMAND" title={<>One structure.<br/><span>Clear authority.</span></>}/><div className="border border-white/10 bg-white/[.012] p-6 sm:p-10"><div className="mb-8 flex items-center gap-3 font-mono text-[9px] tracking-[.2em] text-[#c7aa68]"><Shield size={14}/> COMMAND STRUCTURE</div><Group title="OVERSIGHT" items={leadership}/><Group title="CHAIRMAN BOARD" items={leadership}/><Group title="OWNERSHIP TEAM" items={leadership}/><Group title="SENIOR LEADERSHIP" items={leadership}/><Group title="DEVELOPMENT" items={leadership}/><div className="mt-12 border-t border-white/10 pt-8"><div className="mb-5 font-mono text-[9px] tracking-[.2em] text-[#c7aa68]">STAFF</div><Group title="LEADERSHIP" items={staff}/><Group title="STAFF" items={staff}/></div></div></div></section>
    <section id="divisions" className="border-b border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><Head n="03" label="DIVISIONS" title={<>The operating<br/><span>branches.</span></>}/><div className="grid border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-3">{divisions.map((x,i)=><motion.article key={x.id||i} whileHover={{y:-5}} className="min-h-[220px] border-b border-r border-white/10 bg-[#0d110f] p-7"><div className="flex justify-between font-mono text-[8px] text-white/25"><span>{String(i+1).padStart(2,"0")}</span><ChevronRight size={12}/></div><h3 className="mt-12 text-3xl font-semibold tracking-[-.04em]">{x.name}</h3><p className="mt-3 text-sm leading-6 text-white/40">{x.description||x.desc}</p><div className="mt-6 font-mono text-[8px] uppercase text-[#c7aa68]/60">{x.leadership||x.head||"Leadership pending"}</div></motion.article>)}</div></div></section>
    <section id="operations" className="border-b border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><Head n="04" label="OPERATIONS" title={<>Next on the<br/><span>schedule.</span></>}/><div className="divide-y divide-white/10 border-y border-white/10">{events.length?events.map((x,i)=><article key={x.id||i} className="grid gap-5 py-7 md:grid-cols-[110px_1fr_180px]"><div className="font-mono text-[9px] text-[#c7aa68]">{x.date||"DATE TBA"}<br/><span className="text-white/25">{x.time||"TIME TBA"}</span></div><div><h3 className="text-2xl font-semibold">{x.title}</h3><p className="mt-2 text-sm text-white/40">{x.description||"Official operation."}</p></div><div className="font-mono text-[8px] text-white/25"><CalendarDays size={12} className="mr-2 inline text-[#c7aa68]"/>{x.location||"LOCATION TBA"}</div></article>):<Empty text="No upcoming operations."/>}</div></div></section>
    <section id="media" className="border-b border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><Head n="05" label="MEDIA" title={<>On the ground.<br/><span>In the archive.</span></>}/><div className="grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{media.length?media.map((x,i)=><article key={x.id||i} className="bg-[#0d110f] transition hover:bg-[#111612]"><div className="aspect-video overflow-hidden bg-[#101510]">{x.imageUrl?<img src={x.imageUrl} alt="" className="h-full w-full object-cover saturate-75 transition duration-700 hover:scale-105 hover:saturate-100"/>:<div className="grid h-full place-items-center font-mono text-[9px] text-white/20">FIELD ARCHIVE / {String(i+1).padStart(2,"0")}</div>}</div><div className="p-5"><div className="font-mono text-[8px] text-[#c7aa68]">{x.category||"FIELD ARCHIVE"}</div><h3 className="mt-2 text-lg font-semibold">{x.title||x.caption||"Untitled media"}</h3></div></article>):<Empty text="No media published."/>}</div></div></section>
    <footer className="px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl border-t border-white/10 pt-8 font-mono text-[8px] tracking-[.16em] text-white/20">QUSM / QUAVY'S UNITED STATES MILITARY · OFFICIAL INFORMATION SYSTEM</div></footer>
  </main>;
}
function Head({n,label,title}:{n:string;label:string;title:React.ReactNode}){return <div className="mb-12 flex items-end justify-between gap-8 border-b border-white/10 pb-7"><div><div className="mb-4 font-mono text-[9px] tracking-[.25em] text-[#c7aa68]">{n} / {label}</div><h2 className="text-[clamp(2.8rem,6vw,6rem)] font-medium leading-[.88] tracking-[-.065em]">{title}</h2></div><span className="hidden font-mono text-[8px] text-white/20 sm:block">LIVE CMS</span></div>}
function Empty({text}:{text:string}){return <div className="border border-white/10 px-6 py-12 font-mono text-[9px] text-white/25">{text}</div>}
