"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, ChevronDown, Clock3, ExternalLink, LogIn, Megaphone, Shield, Users, Code2, ScrollText, Landmark, BadgeCheck, Newspaper, ShoppingBag } from "lucide-react";
import { motion } from "framer-motion";

type R=Record<string,any>; type Content=R;
const clean=(a:any[]=[])=>a.filter(x=>x?.active!==false&&x?.status!=="inactive").sort((a,b)=>Number(a.order||0)-Number(b.order||0));
const dateText=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"OFFICIAL";
const fade={initial:{opacity:0,y:16},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.08},transition:{duration:.45}};

export default function LiveHomeV2(){
 const [content,setContent]=useState<Content>({}); const [open,setOpen]=useState("leadership");
 useEffect(()=>{let dead=false;const load=async()=>{try{const r=await fetch("/api/content",{cache:"no-store"});if(r.ok&&!dead)setContent(await r.json())}catch{}};void load();const t=setInterval(load,15000);return()=>{dead=true;clearInterval(t)}},[]);
 const org=content.org||{}; const announcements=useMemo(()=>clean(content.announcements).filter(x=>x.published).slice(0,6),[content.announcements]); const divisions=useMemo(()=>clean(content.divisions),[content.divisions]); const events=useMemo(()=>clean(content.calendar).filter(x=>x.status!=="draft").slice(0,6),[content.calendar]); const leadership=useMemo(()=>clean(content.leadership),[content.leadership]); const rules=useMemo(()=>clean(content.rules),[content.rules]); const government=useMemo(()=>clean(content.government),[content.government]); const ranks=useMemo(()=>clean(content.ranks),[content.ranks]); const news=useMemo(()=>clean(content.news).slice(0,6),[content.news]); const media=useMemo(()=>clean(content.media).slice(0,9),[content.media]); const shop=useMemo(()=>clean(content.shop).slice(0,6),[content.shop]);
 const coc=[['leadership','Leadership',content.cocLeadership||[]],['staff','Staff CoC',content.cocStaff||[]],['roleplay','Roleplay CoC',content.cocRoleplay||[]]] as const;
 return <main className="site-shell bg-bg text-white">
  <nav className="site-nav sticky top-0 z-50 backdrop-blur-xl bg-bg/90 border-b border-border/70 px-5 sm:px-10"><a href="#top" className="brand-mark"><span className="brand-dot"/>{org.name||"FBMRP"}</a><div className="nav-links hidden 2xl:flex"><a href="#announcements">NEWS</a><a href="#command">COMMAND</a><a href="#divisions">DIVISIONS</a><a href="#calendar">OPERATIONS</a><a href="#organization">ORGANIZATION</a><a href="#media">MEDIA</a><a href="#developers">DEVELOPERS</a><a href="#shop">SHOP</a></div><div className="flex items-center gap-2"><a href={org.recruitmentUrl||"#recruitment"} target="_blank" rel="noreferrer" className="nav-action hidden sm:inline-flex"><ExternalLink size={12}/> RECRUITMENT</a><a href="/staff" className="nav-action"><LogIn size={12}/> STAFF PANEL<ArrowRight size={11}/></a></div></nav>
  <section id="top" className="hero-section relative overflow-hidden"><div className="hero-grid"/><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><motion.div className="hero-copy" {...fade}><div className="eyebrow"><span/> {org.heroEyebrow||org.fullName||"FORT BLISS MILITARY ROLEPLAY"}<b>LIVE CMS</b></div><h1><span className="hero-line"><span className="hero-word hero-word-1">{String(org.heroTitle||"BUILT TO SERVE").split(" ")[0]}</span></span><span className="hero-line"><span className="hero-word hero-word-2 hero-outline">{String(org.heroTitle||"BUILT TO SERVE").split(" ").slice(1).join(" ")}</span></span></h1><div className="hero-meta"><span>STRUCTURE</span><span>DISCIPLINE</span><span>IMMERSION</span><span>COMMUNITY</span></div><p className="hero-description">{org.heroDescription||"A structured military roleplay community built around organization, progression, leadership and immersive operations."}</p><div className="hero-actions flex flex-wrap gap-3"><a className="button button-primary" href="#announcements">VIEW UPDATES<ArrowRight size={13}/></a><a className="button button-ghost" href="/staff">STAFF PANEL<LogIn size={12}/></a><a className="button button-ghost" href="/shop">SHOP<ShoppingBag size={12}/></a></div></motion.div><motion.div className="hero-card-wrap" {...fade}><div className="hero-card-shadow"/><div className="hero-card"><div className="card-topbar"><span><i className="status-dot"/> LIVE SYSTEM</span><span>{String(divisions.length).padStart(2,"0")} DIVISIONS</span></div><div className="card-symbol"><Shield size={28}/></div><div className="card-big-number">01</div><div className="card-caption"><span>{org.name||"FBMRP"}</span><strong>{org.fullName||"MILITARY ROLEPLAY"}</strong><span>{org.footerText||"COMMAND // COMMUNITY // OPERATIONS"}</span></div></div></motion.div></section>
  <section id="announcements" className="section-pad"><Header n="01" label="INTELLIGENCE FEED" title={<>Official<br/><span>updates.</span></>} text="Published announcements from Staff Management." icon={<Megaphone className="heading-icon"/>}/>{announcements.length?<Grid>{announcements.map((a,i)=><Card key={a.id} index={i}><h3>{a.title}</h3><p>{a.body}</p><small>{dateText(a.createdAt||a.date)}</small></Card>)}</Grid>:<Empty title="No published announcements"/>}</section>
  <section id="command" className="section-pad bg-panel/20"><Header n="02" label="CHAIN OF COMMAND" title={<>Command<br/><span>structure.</span></>} text="Leadership, staff and roleplay hierarchy are controlled from Staff Management." icon={<Shield className="heading-icon"/>}/><div className="space-y-3 max-w-5xl mx-auto">{coc.map(([key,title,list],i)=>{const visible=clean(list);const isOpen=open===key;return <div key={key} className={`rounded-2xl border ${isOpen?"border-gold/50":"border-border"} bg-panel overflow-hidden`}><button onClick={()=>setOpen(isOpen?"":key)} className="w-full p-5 flex items-center justify-between text-left"><span className="flex items-center gap-4"><span className="h-10 w-10 rounded-xl bg-gold/10 border border-gold/25 flex items-center justify-center font-mono text-[9px] text-golddim">0{i+1}</span><span><strong className="font-serif text-xl">{title}</strong><small className="block font-mono text-[8px] text-textfaint uppercase mt-1">{visible.length} levels</small></span></span><ChevronDown size={18} className={`text-golddim transition-transform ${isOpen?"rotate-180":""}`}/></button>{isOpen&&<div className="border-t border-gold/20 p-5"><div className="border-l border-gold/25 ml-4">{visible.map((x,j)=><div key={x.id||j} className="relative pl-8 py-3"><span className="absolute -left-[5px] top-5 w-2.5 h-2.5 rounded-full border border-gold bg-bg"/><div className="font-mono text-[8px] text-golddim">LEVEL {String(j+1).padStart(2,"0")}</div><div className="font-medium mt-1">{x.title}</div>{x.name&&<div className="text-xs text-golddim mt-1">{x.name}</div>}{x.description&&<div className="text-xs text-textdim mt-1">{x.description}</div>}</div>)}</div>{!visible.length&&<p className="text-textfaint">No entries published.</p>}</div>}</div>})}</div></section>
  <section id="divisions" className="section-pad"><Header n="03" label="ORGANIZATION" title={<>Active<br/><span>divisions.</span></>} text="Division records are managed from Staff Management." icon={<Shield className="heading-icon"/>}/>{divisions.length?<Grid>{divisions.map((d,i)=><Card key={d.id} index={i} image={d.logoUrl}><h3>{d.name}</h3><p>{d.description||"Official division."}</p><small>{d.code||"DIVISION"} · {String(d.status||"active").toUpperCase()}</small></Card>)}</Grid>:<Empty title="No divisions published"/>}</section>
  <section id="calendar" className="section-pad bg-panel/20"><Header n="04" label="OPERATIONS CALENDAR" title={<>Upcoming<br/><span>operations.</span></>} text="Training and operations published by staff." icon={<CalendarDays className="heading-icon"/>}/>{events.length?<Grid>{events.map((e,i)=><Card key={e.id||i} index={i}><h3>{e.title}</h3><div className="font-mono text-[9px] text-textfaint space-y-2 mt-4"><div><CalendarDays size={11} className="inline text-golddim mr-2"/>{e.date||"Date TBA"}</div><div><Clock3 size={11} className="inline text-golddim mr-2"/>{e.time||"Time TBA"}</div><div><Shield size={11} className="inline text-golddim mr-2"/>{e.location||"Location TBA"}</div></div><p>{e.description||"Official operation."}</p></Card>)}</Grid>:<Empty title="No upcoming operations"/>}</section>
  <section id="organization" className="section-pad"><Header n="05" label="OFFICIAL ORGANIZATION" title={<>People &amp;<br/><span>structure.</span></>} text="Leadership, government, ranks and rules are maintained from the CMS." icon={<Users className="heading-icon"/>}/><div className="grid lg:grid-cols-2 gap-5"><Panel title="Command" icon={<Users size={16}/>} items={leadership} render={(x)=><><strong>{x.title}</strong><span>{x.name||x.rank||""}</span><small>{x.division||x.description||""}</small></>}/><Panel title="Government" icon={<Landmark size={16}/>} items={government} render={(x)=><><strong>{x.name||"Vacant"}</strong><span>{x.role||x.title||""}</span><small>{x.department||x.description||""}</small></>}/><Panel title="Ranks" icon={<BadgeCheck size={16}/>} items={ranks} render={(x)=><><strong>{x.name}</strong><span>{x.level||x.code||""}</span><small>{x.description||x.desc||""}</small></>}/><Panel title="Rules & Regulations" icon={<ScrollText size={16}/>} items={rules} render={(x)=><><strong>{x.title}</strong><span>{x.category||"POLICY"}</span><small>{x.body}</small></>}/></div></section>
  <section id="news" className="section-pad bg-panel/20"><Header n="06" label="NEWSROOM" title={<>Latest<br/><span>briefings.</span></>} text="News published by staff." icon={<Newspaper className="heading-icon"/>}/>{news.length?<Grid>{news.map((n,i)=><Card key={n.id||i} index={i} image={n.imageUrl}><small>{n.tag||"NEWS"} · {dateText(n.date)}</small><h3>{n.title}</h3><p>{n.excerpt||n.body}</p></Card>)}</Grid>:<Empty title="No news published"/>}</section>
  <section id="media" className="section-pad"><Header n="07" label="MEDIA ARCHIVE" title={<>Field<br/><span>archive.</span></>} text="Images and videos published through Staff Management and Developer Media." icon={<ImageIcon className="heading-icon"/>}/>{media.length?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{media.map((m,i)=><article key={m.id||i} className="rounded-2xl border border-border bg-panel overflow-hidden">{m.videoUrl?<video src={m.videoUrl} controls className="w-full aspect-video object-cover"/>:m.imageUrl?<img src={m.imageUrl} alt="" className="w-full aspect-video object-cover"/>:<div className="aspect-video bg-panel2 flex items-center justify-center"><Shield size={30} className="text-golddim"/></div>}<div className="p-5"><div className="font-mono text-[9px] text-golddim uppercase">{m.category||"ARCHIVE"}</div><h3 className="font-serif text-xl font-bold mt-2">{m.title||m.caption||"Media"}</h3>{m.caption&&<p className="text-sm text-textdim mt-2">{m.caption}</p>}</div></article>)}</div>:<Empty title="No media published"/>}</section>
  <section id="developers" className="section-pad bg-panel/20"><Header n="08" label="DEVELOPER PROGRAM" title={<>Build the<br/><span>system.</span></>} text="Developers can publish approved media and maintain the community platform." icon={<Code2 className="heading-icon"/>}/><div className="max-w-4xl mx-auto rounded-2xl border border-gold/25 bg-panel p-7 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-5"><div><h3 className="font-serif text-2xl font-bold">Developer Media Studio</h3><p className="text-textdim mt-2">Upload images and videos up to 8 MB through the protected developer area.</p></div><a href="/developer-media" className="button button-primary">OPEN STUDIO<ArrowRight size={13}/></a></div></section>
  <section id="shop" className="section-pad"><Header n="09" label="OFFICIAL MARKETPLACE" title={<>Factions<br/><span>&amp; families.</span></>} text="Official packages managed only by Owner and Co-Owner." icon={<ShoppingBag className="heading-icon"/>}/>{shop.length?<Grid>{shop.map((s,i)=><Card key={s.id||i} index={i} image={s.imageUrl}><small>{s.type||"faction"} · {s.price||"Contact staff"}</small><h3>{s.name}</h3><p>{s.description||"Official package."}</p>{s.gamepassUrl&&<a href={s.gamepassUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-mono text-[9px] text-golddim uppercase">Purchase gamepass<ExternalLink size={11}/></a>}</Card>)}</Grid>:<Empty title="No shop listings"/>}<div className="text-center mt-8"><a href="/shop" className="button button-ghost">VIEW FULL SHOP<ArrowRight size={13}/></a></div></section>
  <section id="recruitment" className="section-pad bg-panel/20"><div className="max-w-5xl mx-auto rounded-3xl border border-gold/25 bg-gradient-to-br from-gold/10 via-panel to-panel p-8 sm:p-12 text-center"><div className="font-mono text-[9px] tracking-[3px] text-golddim">JOIN THE RANKS</div><h2 className="font-serif text-4xl sm:text-5xl font-bold mt-3">Ready to serve?</h2><p className="text-textdim max-w-2xl mx-auto mt-4">Apply through the official recruitment channel and begin your progression.</p><a href={org.recruitmentUrl||"#"} target="_blank" rel="noreferrer" className="button button-primary inline-flex mt-7">RECRUITMENT<ExternalLink size={13}/></a></div></section>
  <footer className="border-t border-border px-5 sm:px-10 py-10 flex flex-col sm:flex-row justify-between gap-5 font-mono text-[9px] text-textfaint uppercase"><span>{org.name||"FBMRP"} · {org.fullName||"Fort Bliss Military Roleplay"}</span><span>{org.footerText||"COMMAND // COMMUNITY // OPERATIONS"}</span></footer>
 </main>;
}
function Header({n,label,title,text,icon}:{n:string;label:string;title:any;text:string;icon:any}){return <div className="max-w-6xl mx-auto mb-10"><div className="flex items-center justify-between"><div className="font-mono text-[9px] tracking-[3px] text-golddim">{n} / {label}</div>{icon}</div><h2 className="font-serif text-5xl sm:text-6xl font-bold mt-3 leading-[.95]">{title}</h2><p className="text-textdim max-w-2xl mt-5 leading-7">{text}</p></div>}
function Grid({children}:{children:any}){return <div className="max-w-6xl mx-auto grid md:grid-cols-2 xl:grid-cols-3 gap-5">{children}</div>}
function Card({children,index,image}:{children:any;index?:number;image?:string}){return <motion.article {...fade} transition={{duration:.4,delay:(index||0)*.03}} className="rounded-2xl border border-border bg-panel overflow-hidden hover:border-gold/40 transition-colors">{image&&<img src={image} alt="" className="w-full aspect-video object-cover"/>}<div className="p-6"><div className="font-mono text-[8px] text-golddim uppercase">{String((index||0)+1).padStart(2,"0")} / RECORD</div><div className="mt-3">{children}</div></div></motion.article>}
function Panel({title,icon,items,render}:{title:string;icon:any;items:any[];render:(x:any)=>any}){return <div className="rounded-2xl border border-border bg-panel p-6"><div className="flex items-center gap-3 border-b border-border pb-4"><span className="text-golddim">{icon}</span><h3 className="font-serif text-2xl font-bold">{title}</h3></div><div className="divide-y divide-border">{items.length?items.map((x,i)=><div key={x.id||i} className="py-4 flex flex-col gap-1">{render(x)}</div>):<p className="py-6 text-textfaint text-sm">No records published.</p>}</div></div>}
function Empty({title}:{title:string}){return <div className="max-w-6xl mx-auto rounded-2xl border border-dashed border-border p-14 text-center text-textfaint">{title}<div className="font-mono text-[8px] uppercase mt-2">Staff-managed content will appear here.</div></div>}
