"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, ChevronDown, Clock3, ExternalLink, LogIn, Megaphone, Shield, Users, Code2, ScrollText, Landmark, BadgeCheck, Newspaper, ShoppingBag, Menu, X } from "lucide-react";
import { motion } from "framer-motion";

type R=Record<string,any>;
const active=(a:R[]=[])=>a.filter(x=>x?.active!==false&&x?.status!=="inactive"&&x?.status!=="draft").slice().sort((a,b)=>Number(a.order||0)-Number(b.order||0));
const date=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"OFFICIAL";
const fade={initial:{opacity:0,y:12},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.08},transition:{duration:.35}};

export default function LiveHomeV3(){
 const [c,setC]=useState<R>({}); const [open,setOpen]=useState("leadership"); const [menu,setMenu]=useState(false);
 const load=async()=>{try{const r=await fetch("/api/content",{cache:"no-store"});if(r.ok)setC(await r.json())}catch{}};
 useEffect(()=>{void load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 const org=c.org||{};
 const announcements=useMemo(()=>active(c.announcements||[]).filter(x=>x.published!==false).slice(0,5),[c.announcements]);
 const divisions=useMemo(()=>active(c.divisions||[]),[c.divisions]); const events=useMemo(()=>active(c.calendar||[]).slice(0,5),[c.calendar]);
 const leadership=useMemo(()=>active(c.leadership||[]),[c.leadership]); const rules=useMemo(()=>active(c.rules||[]),[c.rules]); const government=useMemo(()=>active(c.government||[]),[c.government]);
 const ranks=useMemo(()=>active(c.ranks||[]),[c.ranks]); const news=useMemo(()=>active(c.news||[]).slice(0,4),[c.news]); const media=useMemo(()=>active(c.media||[]).slice(0,6),[c.media]); const shop=useMemo(()=>active(c.shop||[]).slice(0,4),[c.shop]);
 const coc=[['leadership','Leadership',c.cocLeadership||[]],['staff','Staff CoC',c.cocStaff||[]],['roleplay','Roleplay CoC',c.cocRoleplay||[]]] as const;
 return <main className="site-shell bg-bg text-white selection:bg-gold selection:text-black">
  <nav className="site-nav sticky top-0 z-50 bg-bg/95 backdrop-blur border-b border-border"><div className="max-w-7xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between"><a href="#top" className="brand-mark"><span className="brand-dot"/>{org.name||"FBMRP"}</a><div className="hidden lg:flex items-center gap-7 font-mono text-[9px] tracking-[1.5px] text-textdim"><a href="#news" className="hover:text-white">NEWS</a><a href="#command" className="hover:text-white">COMMAND</a><a href="#divisions" className="hover:text-white">DIVISIONS</a><a href="#operations" className="hover:text-white">OPERATIONS</a><a href="#media" className="hover:text-white">MEDIA</a><a href="#developers" className="hover:text-white">DEVELOPERS</a><a href="#shop" className="hover:text-white">SHOP</a></div><div className="hidden sm:flex items-center gap-2"><a href={org.recruitmentUrl||"#recruitment"} target="_blank" rel="noreferrer" className="button button-ghost py-2.5">RECRUITMENT <ExternalLink size={11}/></a><a href="/staff" className="button button-primary py-2.5">STAFF <LogIn size={11}/></a></div><button className="lg:hidden p-2" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="lg:hidden border-t border-border bg-bg px-5 py-5 grid gap-4 font-mono text-[10px] uppercase"><a href="#news" onClick={()=>setMenu(false)}>News</a><a href="#command" onClick={()=>setMenu(false)}>Command</a><a href="#divisions" onClick={()=>setMenu(false)}>Divisions</a><a href="#operations" onClick={()=>setMenu(false)}>Operations</a><a href="#media" onClick={()=>setMenu(false)}>Media</a><a href="#developers" onClick={()=>setMenu(false)}>Developers</a><a href="#shop" onClick={()=>setMenu(false)}>Shop</a><a href="/staff">Staff Panel</a></div>}</nav>
  <header id="top" className="border-b border-border"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-16 lg:py-24 grid lg:grid-cols-[1.35fr_.65fr] gap-14 items-end"><div><div className="font-mono text-[9px] tracking-[3px] text-golddim mb-5">{org.heroEyebrow||org.fullName||"FORT BLISS MILITARY ROLEPLAY"} <span className="text-textfaint ml-3">/ LIVE</span></div><h1 className="font-serif text-[clamp(4rem,11vw,9rem)] font-bold leading-[.78] tracking-[-.05em]">{String(org.heroTitle||"BUILT TO SERVE").split(" ").slice(0,-1).join(" ")||"BUILT"}<br/><em className="text-gold not-italic">{String(org.heroTitle||"BUILT TO SERVE").split(" ").slice(-1)[0]}</em></h1><p className="max-w-xl text-textdim text-base sm:text-lg leading-7 mt-9">{org.heroDescription||"A structured military roleplay community built around organization, progression, leadership and immersive operations."}</p><div className="flex flex-wrap gap-2 mt-8"><a className="button button-primary" href="#news">ENTER THE COMMUNITY <ArrowRight size={13}/></a><a className="button button-ghost" href="/shop">VIEW SHOP <ShoppingBag size={12}/></a></div></div><div className="border-l border-gold/40 pl-7 hidden lg:block"><div className="font-mono text-[8px] text-textfaint tracking-[2px]">SYSTEM STATUS</div><div className="font-serif text-3xl mt-3">Operational.</div><div className="grid grid-cols-2 gap-x-5 gap-y-4 mt-8 text-[9px] font-mono uppercase"><div><b className="text-white block text-xl font-sans">{divisions.length}</b>Divisions</div><div><b className="text-white block text-xl font-sans">{leadership.length}</b>Command</div><div><b className="text-white block text-xl font-sans">{announcements.length}</b>Updates</div><div><b className="text-white block text-xl font-sans">{shop.length}</b>Packages</div></div></div></div></header>
  <section id="news" className="section-pad border-b border-border"><Heading n="01" label="NEWS" title={<>What changed.<br/><span>What matters.</span></>} text="Official updates published by staff. This feed is read from the live CMS." icon={<Megaphone/>}/><div className="max-w-6xl mx-auto">{announcements.length?<div className="divide-y divide-border border-y border-border">{announcements.map((x,i)=><article key={x.id||i} className="grid md:grid-cols-[90px_1fr_170px] gap-5 py-6 items-start"><span className="font-mono text-[9px] text-golddim">{String(i+1).padStart(2,"0")}</span><div><h3 className="font-serif text-2xl font-bold">{x.title}</h3><p className="text-textdim mt-2 max-w-3xl leading-6">{x.body}</p></div><time className="font-mono text-[9px] text-textfaint md:text-right">{date(x.createdAt||x.date)}</time></article>)}</div>:<Empty text="No published announcements."/>}</div></section>
  <section id="command" className="section-pad border-b border-border"><Heading n="02" label="CHAIN OF COMMAND" title={<>Three lines.<br/><span>One structure.</span></>} text="Leadership, Staff CoC and Roleplay CoC are maintained independently in Staff Management." icon={<Shield/>}/><div className="max-w-6xl mx-auto grid lg:grid-cols-3 border-y border-border">{coc.map(([key,title,list],i)=>{const items=active(list);const is=open===key;return <div key={key} className="border-b lg:border-b-0 lg:border-r last:border-r-0 border-border"><button onClick={()=>setOpen(is?"":key)} className="w-full text-left p-6 hover:bg-panel/40"><div className="font-mono text-[8px] text-golddim">0{i+1}</div><div className="font-serif text-2xl font-bold mt-2">{title}</div><div className="font-mono text-[8px] text-textfaint mt-2">{items.length} POSITIONS <ChevronDown size={12} className={`inline ml-2 ${is?"rotate-180":""}`}/></div></button>{is&&<div className="px-6 pb-7"><ol className="border-l border-gold/30">{items.map((x,j)=><li key={x.id||j} className="relative pl-6 py-3"><span className="absolute -left-[4px] top-5 h-1.5 w-1.5 bg-gold"/><div className="font-mono text-[8px] text-golddim">{String(j+1).padStart(2,"0")}</div><div className="font-serif text-lg">{x.title}</div>{x.name&&<div className="text-xs text-gold/80">{x.name}</div>}{x.description&&<p className="text-xs text-textfaint mt-1 leading-5">{x.description}</p>}</li>)}</ol></div>}</div>})}</div></section>
  <section id="divisions" className="section-pad border-b border-border"><Heading n="03" label="DIVISIONS" title={<>The operating<br/><span>branches.</span></>} text="Every division displayed here comes from the same records staff edit." icon={<Users/>}/><div className="max-w-6xl mx-auto grid sm:grid-cols-2 lg:grid-cols-3 border-t border-l border-border">{divisions.length?divisions.map((x,i)=><article key={x.id||i} className="border-r border-b border-border p-6 min-h-[220px] hover:bg-panel/30 transition"><div className="font-mono text-[8px] text-golddim">{String(i+1).padStart(2,"0")} / {x.code||"DIV"}</div><h3 className="font-serif text-3xl font-bold mt-10">{x.name}</h3><p className="text-textdim text-sm leading-6 mt-3">{x.description||x.desc||"Official division."}</p><div className="font-mono text-[8px] text-textfaint mt-6 uppercase">{x.leadership||x.head||"Leadership assignment pending"}</div></article>):<div className="col-span-full"><Empty text="No divisions published."/></div>}</div></section>
  <section id="operations" className="section-pad border-b border-border"><Heading n="04" label="OPERATIONS" title={<>Next on the<br/><span>schedule.</span></>} text="Training, operations and official events." icon={<CalendarDays/>}/><div className="max-w-6xl mx-auto">{events.length?<div className="border-t border-border">{events.map((x,i)=><article key={x.id||i} className="grid md:grid-cols-[120px_1fr_220px] gap-6 py-7 border-b border-border items-start"><div className="font-mono text-[9px] text-golddim">{x.date||"DATE TBA"}<br/><span className="text-textfaint">{x.time||"TIME TBA"}</span></div><div><h3 className="font-serif text-2xl">{x.title}</h3><p className="text-textdim text-sm mt-2">{x.description||"Official operation."}</p></div><div className="font-mono text-[8px] text-textfaint uppercase"><Clock3 size={12} className="inline mr-2 text-gold"/>{x.location||"Location TBA"}</div></article>)}</div>:<Empty text="No upcoming operations."/>}</div></section>
  <section className="section-pad border-b border-border"><Heading n="05" label="ORGANIZATION" title={<>People. Policy.<br/><span>Standards.</span></>} text="The rest of the public organization is also CMS-driven." icon={<Landmark/>}/><div className="max-w-6xl mx-auto grid lg:grid-cols-2 border-t border-l border-border">{[["COMMAND",leadership,(x:R)=><><b>{x.title||x.role||"Position"}</b><span>{x.name}</span><small>{x.rank||x.division||""}</small></>],["GOVERNMENT",government,(x:R)=><><b>{x.name||"Vacant"}</b><span>{x.title||x.role||""}</span><small>{x.note||x.department||x.description||""}</small></>],["RANK STRUCTURE",ranks,(x:R)=><><b>{x.name}</b><span>{x.level||x.code||""}</span><small>{x.description||x.desc||""}</small></>],["RULES & REGULATIONS",rules,(x:R)=><><b>{x.title}</b><span>{x.category||"POLICY"}</span><small>{x.body}</small></>]].map(([title,list,render]:any)=><div key={title} className="border-r border-b border-border p-6"><div className="font-mono text-[9px] tracking-[2px] text-golddim mb-5">{title}</div>{(list as R[]).slice(0,7).map((x,i)=><div key={x.id||i} className="py-3 border-t border-border/70 grid grid-cols-[1fr_auto] gap-4 text-sm">{render(x)}</div>)}{!(list as R[]).length&&<span className="text-textfaint text-sm">No records published.</span>}</div>)}</div></section>
  <section id="media" className="section-pad border-b border-border"><Heading n="06" label="MEDIA" title={<>On the ground.<br/><span>In the archive.</span></>} text="Published images and videos." icon={<Newspaper/>}/><div className="max-w-6xl mx-auto grid md:grid-cols-2 lg:grid-cols-3 gap-px bg-border">{media.length?media.map((x,i)=><article key={x.id||i} className="bg-bg">{x.videoUrl?<video src={x.videoUrl} controls className="w-full aspect-video object-cover"/>:x.imageUrl?<img src={x.imageUrl} alt="" className="w-full aspect-video object-cover"/>:<div className="aspect-video bg-panel flex items-center justify-center font-mono text-[9px] text-textfaint">MEDIA / {String(i+1).padStart(2,"0")}</div>}<div className="p-5"><div className="font-mono text-[8px] text-golddim">{x.category||"FIELD ARCHIVE"}</div><h3 className="font-serif text-xl mt-2">{x.title||x.caption||"Untitled media"}</h3></div></article>):<div className="col-span-full"><Empty text="No media published."/></div>}</div></section>
  <section id="developers" className="section-pad border-b border-border"><Heading n="07" label="DEVELOPERS" title={<>Build with us.<br/><span>Ship clean work.</span></>} text="A dedicated place for approved developer media. Uploads are limited to 8 MB." icon={<Code2/>}/><div className="max-w-6xl mx-auto border-y border-border flex flex-col sm:flex-row justify-between gap-8 p-7 sm:p-10"><div><div className="font-mono text-[8px] text-golddim">DEVELOPER MEDIA STUDIO</div><p className="text-textdim mt-3 max-w-xl">Publish screenshots, artwork and videos without mixing developer material into the general administration workflow.</p></div><a href="/developer-media" className="button button-primary self-start">OPEN STUDIO <ArrowRight size={13}/></a></div></section>
  <section id="shop" className="section-pad border-b border-border"><Heading n="08" label="MARKETPLACE" title={<>Factions &amp;<br/><span>families.</span></>} text="Official gamepass packages. Shop inventory is restricted to Owner, Co-Owner and the designated shop owner." icon={<ShoppingBag/>}/><div className="max-w-6xl mx-auto grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-border">{shop.length?shop.map((x,i)=><article key={x.id||i} className="bg-bg p-6"><div className="font-mono text-[8px] text-golddim uppercase">{x.type||"package"}</div>{x.imageUrl?<img src={x.imageUrl} alt="" className="w-full aspect-square object-cover mt-5"/>:<div className="aspect-square mt-5 border border-border flex items-center justify-center"><ShoppingBag className="text-textfaint"/></div>}<h3 className="font-serif text-2xl mt-5">{x.name}</h3><p className="text-textdim text-sm mt-2 leading-5">{x.description||"Official package."}</p><div className="font-mono text-[9px] text-golddim mt-5">{x.price||"GAMEPASS"}</div>{x.gamepassUrl&&<a href={x.gamepassUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-4 font-mono text-[8px] uppercase hover:text-gold">Purchase <ExternalLink size={10}/></a>}</article>):<div className="col-span-full"><Empty text="No shop packages published."/></div>}</div><div className="text-center mt-8"><a href="/shop" className="button button-ghost">VIEW FULL MARKETPLACE <ArrowRight size={13}/></a></div></section>
  <section id="recruitment" className="section-pad"><div className="max-w-6xl mx-auto border-y border-gold/40 py-12 sm:py-16 flex flex-col lg:flex-row justify-between gap-8 items-start lg:items-end"><div><div className="font-mono text-[9px] tracking-[3px] text-golddim">09 / RECRUITMENT</div><h2 className="font-serif text-5xl sm:text-7xl font-bold mt-3">Ready to<br/><span className="text-gold">serve?</span></h2></div><div className="max-w-md"><p className="text-textdim leading-7">Join through the official recruitment channel. Staff will guide you through onboarding and placement.</p><a href={org.recruitmentUrl||"#"} target="_blank" rel="noreferrer" className="button button-primary inline-flex mt-6">APPLY NOW <ExternalLink size={12}/></a></div></div></section>
  <footer className="border-t border-border"><div className="max-w-7xl mx-auto px-5 sm:px-8 py-8 flex flex-col sm:flex-row justify-between gap-3 font-mono text-[8px] text-textfaint uppercase"><span>{org.name||"FBMRP"} / {org.fullName||"Fort Bliss Military Roleplay"}</span><span>{org.footerText||"COMMAND // COMMUNITY // OPERATIONS"}</span></div></footer>
 </main>;
}
function Heading({n,label,title,text,icon}:{n:string;label:string;title:any;text:string;icon:any}){return <div className="max-w-6xl mx-auto mb-10"><div className="flex justify-between"><div className="font-mono text-[9px] tracking-[3px] text-golddim">{n} / {label}</div><span className="text-golddim">{icon}</span></div><h2 className="font-serif text-5xl sm:text-6xl font-bold mt-3 leading-[.95]">{title}</h2><p className="text-textdim max-w-2xl mt-5 leading-7">{text}</p></div>}
function Empty({text}:{text:string}){return <div className="border-y border-dashed border-border py-14 text-center font-mono text-[9px] text-textfaint uppercase tracking-[1.5px]">{text}</div>}
