"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, ChevronDown, Clock3, ExternalLink, LogIn, Megaphone, Play, Shield, Users, Code2, ScrollText, Landmark, BadgeCheck, Newspaper } from "lucide-react";
import { motion } from "framer-motion";

type AnyRecord = Record<string, any>;
type Content = {
  org?: AnyRecord; divisions?: AnyRecord[]; leadership?: AnyRecord[]; announcements?: AnyRecord[]; calendar?: AnyRecord[]; media?: AnyRecord[];
  rules?: AnyRecord[]; government?: AnyRecord[]; ranks?: AnyRecord[]; news?: AnyRecord[];
  cocLeadership?: AnyRecord[]; cocStaff?: AnyRecord[]; cocRoleplay?: AnyRecord[];
};

const fadeUp = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.1 } };
const clean = (items: AnyRecord[] = []) => items.filter(x => x.active !== false && x.status !== "inactive").sort((a, b) => Number(a.order || 0) - Number(b.order || 0));
const dateText = (v: any) => v ? new Date(v).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }) : "OFFICIAL";

export default function LiveHome() {
  const [content, setContent] = useState<Content>({});
  const [openCoc, setOpenCoc] = useState<string | null>("leadership");

  useEffect(() => {
    let cancelled = false;
    const load = async () => { try { const r = await fetch("/api/content", { cache: "no-store" }); if (r.ok && !cancelled) setContent(await r.json()); } catch {} };
    void load(); const timer = window.setInterval(load, 15000); return () => { cancelled = true; window.clearInterval(timer); };
  }, []);

  const org = content.org || {};
  const divisions = useMemo(() => clean(content.divisions).filter(x => x.status !== "inactive"), [content.divisions]);
  const announcements = useMemo(() => (content.announcements || []).filter(x => x.published).sort((a, b) => String(b.createdAt || "").localeCompare(String(a.createdAt || ""))).slice(0, 6), [content.announcements]);
  const events = useMemo(() => (content.calendar || []).filter(x => x.status !== "draft").sort((a, b) => `${a.date || ""}${a.time || ""}`.localeCompare(`${b.date || ""}${b.time || ""}`)).slice(0, 6), [content.calendar]);
  const leadership = useMemo(() => clean(content.leadership), [content.leadership]);
  const media = useMemo(() => clean(content.media).slice(0, 9), [content.media]);
  const rules = useMemo(() => clean(content.rules), [content.rules]);
  const government = useMemo(() => clean(content.government), [content.government]);
  const ranks = useMemo(() => clean(content.ranks), [content.ranks]);
  const news = useMemo(() => clean(content.news).slice(0, 6), [content.news]);
  const coc = [
    ["leadership", "Leadership", content.cocLeadership || []],
    ["staff", "Staff CoC", content.cocStaff || []],
    ["roleplay", "Roleplay CoC", content.cocRoleplay || []],
  ] as const;

  return <main className="site-shell bg-bg text-white">
    <nav className="site-nav sticky top-0 z-50 backdrop-blur-xl bg-bg/90 border-b border-border/70 px-5 sm:px-10">
      <a href="#top" className="brand-mark"><span className="brand-dot" /> {org.name || "FBMRP"}</a>
      <div className="nav-links hidden xl:flex"><a href="#announcements">NEWS</a><a href="#command">COMMAND</a><a href="#divisions">DIVISIONS</a><a href="#calendar">OPERATIONS</a><a href="#organization">ORGANIZATION</a><a href="#media">MEDIA</a><a href="#developers">DEVELOPERS</a></div>
      <div className="flex items-center gap-2"><a href={org.recruitmentUrl || "#recruitment"} target="_blank" rel="noreferrer" className="nav-action hidden sm:inline-flex"><ExternalLink size={12}/> RECRUITMENT</a><a href="/staff" className="nav-action"><LogIn size={12}/> STAFF PANEL <ArrowRight size={11}/></a></div>
    </nav>

    <section id="top" className="hero-section relative overflow-hidden"><div className="hero-grid"/><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><motion.div className="hero-copy" {...fadeUp} transition={{ duration: .65 }}>
      <div className="eyebrow"><span/> {org.heroEyebrow || org.fullName || "FORT BLISS MILITARY ROLEPLAY"} <b>LIVE CMS</b></div>
      <h1><span className="hero-line"><span className="hero-word hero-word-1">{String(org.heroTitle || "BUILT TO SERVE").split(" ").slice(0, 1).join(" ")}</span></span><span className="hero-line"><span className="hero-word hero-word-2 hero-outline">{String(org.heroTitle || "BUILT TO SERVE").split(" ").slice(1).join(" ") || "TO SERVE"}</span></span></h1>
      <div className="hero-meta"><span>STRUCTURE</span><span>DISCIPLINE</span><span>IMMERSION</span><span>COMMUNITY</span></div><p className="hero-description">{org.heroDescription || "A structured military roleplay community built around organization, progression, leadership and immersive operations."}</p>
      <div className="hero-actions flex flex-wrap gap-3"><a className="button button-primary" href="#announcements">VIEW UPDATES <ArrowRight size={13}/></a><a className="button button-ghost" href="/staff">STAFF PANEL <LogIn size={12}/></a><a className="button button-ghost" href={org.recruitmentUrl || "#recruitment"} target="_blank" rel="noreferrer">RECRUITMENT <ExternalLink size={12}/></a></div>
    </motion.div><motion.div className="hero-card-wrap" {...fadeUp} transition={{ duration: .75, delay: .1 }}><div className="hero-card-shadow"/><div className="hero-card"><div className="card-topbar"><span><i className="status-dot"/> LIVE SYSTEM</span><span>{String(divisions.length).padStart(2, "0")} DIVISIONS</span></div><div className="card-symbol"><Shield size={28}/></div><div className="card-big-number">01</div><div className="card-caption"><span>{org.name || "FBMRP"}</span><strong>{org.fullName || "MILITARY ROLEPLAY"}</strong><span>{org.footerText || "COMMAND // COMMUNITY // OPERATIONS"}</span></div></div></motion.div></section>

    <section id="announcements" className="section-pad"><Header n="01" label="INTELLIGENCE FEED" title={<>Official<br/><span>updates.</span></>} description="Published announcements from Staff Management are displayed as operational briefings." icon={<Megaphone className="heading-icon"/>} />{announcements.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{announcements.map((a, i) => <motion.article {...fadeUp} key={a.id} className="group relative overflow-hidden rounded-2xl border border-border bg-panel/90 p-6 min-h-[230px] shadow-2xl hover:-translate-y-1 transition-transform"><div className="absolute left-0 top-0 h-1 w-full bg-gold/70"/><div className="flex items-center justify-between gap-3 mb-6"><span className="font-mono text-[9px] tracking-[2px] text-golddim">UPDATE {String(i + 1).padStart(2, "0")}</span><span className="rounded-full border border-border px-2.5 py-1 font-mono text-[8px] text-textfaint">PUBLISHED</span></div><h3 className="font-serif text-2xl font-bold leading-tight">{a.title}</h3><p className="mt-4 text-sm leading-7 text-textdim whitespace-pre-wrap">{a.body}</p><div className="mt-6 pt-4 border-t border-border flex justify-between font-mono text-[8px] uppercase text-textfaint"><span>{org.name || "FBMRP"} COMMAND</span><span>{dateText(a.createdAt)}</span></div></motion.article>)}</div> : <EmptyCard icon={<Megaphone size={25}/>} title="No published announcements" text="New staff announcements will appear here automatically."/>}</section>

    <section id="command" className="section-pad bg-panel/20"><Header n="02" label="CHAIN OF COMMAND" title={<>Command<br/><span>structure.</span></>} description="Every command tier is now managed from Staff Management. Nothing on this hierarchy is hard-coded." icon={<Shield className="heading-icon"/>}/><div className="grid lg:grid-cols-[.9fr_1.5fr] gap-6 items-start"><div className="rounded-2xl border border-gold/30 bg-gradient-to-br from-gold/10 via-panel to-panel p-6 lg:sticky lg:top-24"><div className="font-mono text-[9px] tracking-[2px] text-golddim">{org.name || "FBMRP"} / AUTHORITY</div><div className="mt-6 h-16 w-16 rounded-2xl border border-gold/30 bg-bg flex items-center justify-center text-gold"><Shield size={28}/></div><h3 className="font-serif text-3xl font-bold mt-5">Chain of Command</h3><p className="text-textdim text-sm leading-6 mt-3">Leadership, staff and roleplay hierarchy are read directly from the live CMS.</p></div><div className="space-y-3">{coc.map(([key, title, list], idx) => { const visible = clean(list); const open = openCoc === key; return <div key={key} className={`overflow-hidden rounded-2xl border ${open ? "border-gold/50" : "border-border"} bg-panel`}><button onClick={() => setOpenCoc(open ? null : key)} className="w-full flex items-center justify-between gap-4 p-5 text-left"><span className="flex items-center gap-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-gold/25 bg-gold/5 font-mono text-[9px] text-golddim">0{idx + 1}</span><span><strong className="block font-serif text-xl">{title}</strong><span className="font-mono text-[8px] uppercase tracking-widest text-textfaint">{visible.length} levels</span></span></span><ChevronDown size={18} className={`text-golddim transition-transform ${open ? "rotate-180" : ""}`}/></button>{open && <div className="border-t border-gold/20 px-5 pb-5 pt-3">{visible.length ? <div className="relative ml-4 border-l border-gold/25">{visible.map((item, i) => <div key={item.id || i} className="relative pl-8 py-3"><span className="absolute -left-[5px] top-5 h-2.5 w-2.5 rounded-full border border-gold bg-bg"/><div className="font-mono text-[8px] text-golddim mb-1">LEVEL {String(i + 1).padStart(2, "0")}</div><div className="font-medium text-sm sm:text-base">{item.title}</div>{item.name && <div className="text-xs text-golddim mt-1">{item.name}</div>}{item.description && <div className="text-xs text-textdim mt-1">{item.description}</div>}</div>)}</div> : <p className="text-textfaint text-sm py-5">No entries published.</p>}</div>}</div>})}</div></div></section>

    <section id="divisions" className="section-pad"><Header n="03" label="ORGANIZATION" title={<>Active<br/><span>divisions.</span></>} description="Division records, descriptions, status and logos are controlled from Staff Management." icon={<Shield className="heading-icon"/>}/>{divisions.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{divisions.map((d, i) => <article key={d.id || d.code} className="division-card group"><div className="division-top"><span>DIV / {String(i + 1).padStart(2, "0")}</span><span className="text-golddim">{String(d.status || "ACTIVE").toUpperCase()}</span></div><div className="my-7 h-16 w-16 rounded-2xl border border-border bg-bg flex items-center justify-center overflow-hidden">{d.logoUrl ? <img src={d.logoUrl} alt="" className="h-full w-full object-cover"/> : <Shield size={25}/>}</div><h3>{d.name}</h3><p className="min-h-[56px]">{d.description || "Official division."}</p><div className="mt-6 pt-4 border-t border-border flex items-center justify-between font-mono text-[9px] text-golddim"><span>{d.code || "DIVISION"}</span><ArrowRight size={13} className="group-hover:translate-x-1 transition-transform"/></div></article>)}</div> : <EmptyCard icon={<Shield size={25}/>} title="No divisions published" text="Active divisions will appear here once staff publish them."/>}</section>

    <section id="calendar" className="section-pad bg-panel/20"><Header n="04" label="OPERATIONS CALENDAR" title={<>Upcoming<br/><span>operations.</span></>} description="Training, operations and community events published through Staff Management." icon={<CalendarDays className="heading-icon"/>}/>{events.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{events.map((e, i) => <article key={e.id || i} className="rounded-2xl border border-border bg-panel p-6 hover:border-gold/30 transition-colors"><div className="flex items-start justify-between gap-4"><div className="h-12 w-12 rounded-xl border border-border bg-bg flex items-center justify-center text-golddim"><CalendarDays size={20}/></div><span className="font-mono text-[9px] text-golddim border border-border rounded-full px-3 py-1">OP {String(i + 1).padStart(2, "0")}</span></div><h3 className="font-serif text-xl font-bold mt-6">{e.title}</h3><div className="mt-4 space-y-2 font-mono text-[9px] uppercase text-textfaint"><div className="flex gap-2"><CalendarDays size={12} className="text-golddim"/>{e.date || "Date TBA"}</div><div className="flex gap-2"><Clock3 size={12} className="text-golddim"/>{e.time || "Time TBA"}</div><div className="flex gap-2"><Shield size={12} className="text-golddim"/>{e.location || "Location TBA"}</div></div><p className="mt-5 text-sm leading-6 text-textdim">{e.description || "Official community operation."}</p></article>)}</div> : <EmptyCard icon={<CalendarDays size={25}/>} title="No upcoming operations" text="Published events will appear here automatically."/>}</section>

    <section id="organization" className="section-pad"><Header n="05" label="OFFICIAL ORGANIZATION" title={<>People &amp;<br/><span>structure.</span></>} description="Staff can maintain leadership, government, rank structure and rules from one management system." icon={<Users className="heading-icon"/>}/><div className="grid lg:grid-cols-2 gap-6"><DataPanel title="Leadership" icon={<Users size={16}/>} items={leadership} render={(x) => <><strong>{x.title}</strong><span className="text-golddim">{x.name || x.rank || ""}</span><small>{x.division || x.description || ""}</small></>}/><DataPanel title="Government" icon={<Landmark size={16}/>} items={government} render={(x) => <><strong>{x.name}</strong><span className="text-golddim">{x.role || ""}</span><small>{x.department || x.description || ""}</small></>}/><DataPanel title="Rank Structure" icon={<BadgeCheck size={16}/>} items={ranks} render={(x) => <><strong>{x.name}</strong><span className="text-golddim">{x.level || ""}</span><small>{x.description || ""}</small></>}/><DataPanel title="Rules & Regulations" icon={<ScrollText size={16}/>} items={rules} render={(x) => <><strong>{x.title}</strong><span className="text-golddim">{x.category || "OFFICIAL"}</span><small>{x.body || ""}</small></>}/></div></section>

    <section id="news" className="section-pad bg-panel/20"><Header n="06" label="NEWS & BULLETIN" title={<>Field<br/><span>briefings.</span></>} description="News records published by staff are displayed here as editorial cards." icon={<Newspaper className="heading-icon"/>}/>{news.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{news.map(n => <article key={n.id || n.title} className="rounded-2xl border border-border bg-panel overflow-hidden">{n.imageUrl && <img src={n.imageUrl} alt="" className="w-full aspect-video object-cover"/>}<div className="p-6"><div className="font-mono text-[8px] text-golddim uppercase">{dateText(n.date)}</div><h3 className="font-serif text-xl font-bold mt-2">{n.title}</h3><p className="text-textdim text-sm leading-6 mt-3">{n.excerpt || n.body || "Official bulletin."}</p></div></article>)}</div> : <EmptyCard icon={<Newspaper size={25}/>} title="No bulletins published" text="Staff news will appear here automatically."/>}</section>

    <section id="media" className="section-pad"><Header n="07" label="MEDIA ARCHIVE" title={<>Mission<br/><em>in motion.</em></>} description="Approved images and videos from the Developer Media area are displayed here." icon={<Play className="heading-icon"/>}/>{media.length ? <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{media.map(m => <article key={m.id || m.title} className="overflow-hidden rounded-2xl border border-border bg-panel group"><div className="aspect-video bg-bg flex items-center justify-center overflow-hidden">{m.videoUrl ? <video src={m.videoUrl} controls preload="metadata" className="h-full w-full object-cover"/> : m.imageUrl ? <img src={m.imageUrl} alt={m.title || "FBMRP media"} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/> : <Play size={30}/>}</div><div className="p-5"><div className="font-mono text-[8px] text-golddim uppercase tracking-widest">{m.category || "DEVELOPER MEDIA"}</div><h3 className="font-serif text-xl font-bold mt-2">{m.title || "Untitled media"}</h3><p className="text-textdim text-sm mt-2">{m.caption || "Official media."}</p></div></article>)}</div> : <EmptyCard icon={<Play size={25}/>} title="Media archive is empty" text="Developer uploads approved for publication will appear here."/>}</section>

    <section id="developers" className="section-pad bg-panel/20"><div className="rounded-3xl border border-gold/25 bg-gradient-to-br from-gold/10 via-panel to-panel p-8 sm:p-12 flex flex-col lg:flex-row lg:items-center justify-between gap-8"><div><div className="section-label">08 / DEVELOPER STUDIO</div><h2 className="font-serif text-4xl sm:text-5xl font-bold mt-3">Build the<br/><span>archive.</span></h2><p className="text-textdim max-w-2xl mt-4 leading-7">Developers can upload approved images and videos through the protected media studio. Maximum upload size is 8 MB per file.</p></div><a href="/developer-media" className="button button-primary shrink-0"><Code2 size={14}/> DEVELOPER MEDIA <ArrowRight size={13}/></a></div></section>

    <section id="recruitment" className="section-pad"><div className="rounded-3xl border border-border bg-panel p-8 sm:p-12 text-center"><div className="font-mono text-[9px] tracking-[2px] text-golddim">JOIN THE RANKS</div><h2 className="font-serif text-4xl sm:text-5xl font-bold mt-3">Ready to <span className="text-golddim">serve?</span></h2><p className="text-textdim max-w-2xl mx-auto mt-4">Applications and recruitment are managed through the official community channel.</p><a href={org.recruitmentUrl || "#"} target="_blank" rel="noreferrer" className="button button-primary inline-flex mt-7">OPEN RECRUITMENT <ExternalLink size={13}/></a></div></section>

    <footer className="border-t border-border px-5 sm:px-10 py-10"><div className="max-w-7xl mx-auto flex flex-col sm:flex-row justify-between gap-4"><div><div className="font-mono text-[9px] text-golddim">{org.name || "FBMRP"}</div><div className="font-serif text-xl font-bold mt-1">{org.fullName || "Fort Bliss Military Roleplay"}</div></div><div className="font-mono text-[8px] text-textfaint uppercase text-left sm:text-right">{org.footerText || "COMMAND // COMMUNITY // OPERATIONS"}<br/>LIVE CONTENT SYSTEM</div></div></footer>
  </main>;
}

function Header({ n, label, title, description, icon }: { n: string; label: string; title: any; description: string; icon: any }) { return <motion.div {...fadeUp} className="section-heading-row mb-10"><div><div className="section-label">{n} / {label}</div><h2>{title}</h2><p className="text-textdim max-w-2xl mt-4">{description}</p></div><div className="heading-index">{icon} LIVE CMS</div></motion.div>; }
function EmptyCard({ icon, title, text }: { icon: any; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-border bg-panel/40 p-12 text-center"><div className="mx-auto h-14 w-14 rounded-2xl border border-border flex items-center justify-center text-golddim">{icon}</div><h3 className="font-serif text-2xl font-bold mt-5">{title}</h3><p className="text-textfaint text-sm mt-2">{text}</p></div>; }
function DataPanel({ title, icon, items, render }: { title: string; icon: any; items: AnyRecord[]; render: (x: AnyRecord) => any }) { return <section className="rounded-2xl border border-border bg-panel p-6"><div className="flex items-center justify-between mb-5"><h3 className="font-serif text-2xl font-bold">{title}</h3><span className="h-9 w-9 rounded-lg border border-border flex items-center justify-center text-golddim">{icon}</span></div>{items.length ? <div className="space-y-2">{items.map((x, i) => <article key={x.id || i} className="rounded-xl border border-border bg-bg/60 p-4 flex flex-col gap-1">{render(x)}</article>)}</div> : <div className="rounded-xl border border-dashed border-border p-6 text-center text-textfaint text-sm">Nothing published yet.</div>}</section>; }
