"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, ShoppingBag, Sparkles } from "lucide-react";
import { motion } from "framer-motion";

type Item={id:string;name:string;type:"faction"|"family";description?:string;price?:string;gamepassUrl?:string;imageUrl?:string;status?:string;badge?:string;features?:string[]};
export default function StoreSection(){
 const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/content",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setItems(Array.isArray(d?.shop)?d.shop.filter((x:Item)=>x.status!=="inactive"):[])).catch(()=>setItems([])).finally(()=>setLoading(false))},[]);
 return <section id="store" className="relative overflow-hidden border-t border-white/10 bg-[#080a08] py-28 md:py-40"><div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_80%_20%,rgba(212,181,106,.14),transparent_30%)]"/><div className="relative mx-auto max-w-[1500px] px-5 md:px-10"><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-8"><div><span className="text-[9px] tracking-[.35em] text-[#d4b56a]">05 / FBMR EXCHANGE</span><h2 className="mt-5 text-6xl md:text-8xl font-semibold tracking-[-.07em]">THE<br/><span className="text-[#d4b56a]">GOLD STORE.</span></h2><p className="mt-7 max-w-xl text-sm md:text-base leading-7 text-white/40">Official faction and family listings, presented with the same standard as the rest of the FBMR information network.</p></div><div className="hidden md:flex h-20 w-20 items-center justify-center rounded-full border border-[#d4b56a]/40 text-[#d4b56a]"><ShoppingBag size={25}/></div></div>
 {loading?<div className="mt-16 grid md:grid-cols-2 lg:grid-cols-3 gap-5">{[1,2,3].map(i=><div key={i} className="h-[430px] animate-pulse rounded-[2rem] border border-white/10 bg-white/[.025]"/>)}</div>:items.length?<div className="mt-16 grid md:grid-cols-2 lg:grid-cols-3 gap-5">{items.sort((a,b)=>(a.id||"").localeCompare(b.id||"")).map((x,i)=><motion.article initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{delay:i*.07}} key={x.id} className="group relative min-h-[430px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#0c100d] hover:border-[#d4b56a]/50 transition-colors"><div className="absolute inset-0">{x.imageUrl?<img src={x.imageUrl} alt="" className="h-full w-full object-cover opacity-45 transition duration-700 group-hover:scale-105 group-hover:opacity-60"/>:<div className="h-full w-full bg-[linear-gradient(135deg,#161b16,#070907)]"/>}</div><div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/10"/><div className="relative flex min-h-[430px] flex-col justify-between p-7 md:p-8"><div className="flex justify-between gap-3"><span className="rounded-full border border-[#d4b56a]/35 bg-black/30 px-3 py-1.5 text-[8px] tracking-[.2em] text-[#d4b56a] uppercase">{x.badge||x.type}</span>{x.status==="sold-out"&&<span className="text-[8px] tracking-[.2em] text-white/40 uppercase">Sold out</span>}</div><div><div className="mb-5 flex items-center gap-2 text-[#d4b56a]"><Sparkles size={13}/><span className="text-[8px] tracking-[.25em]">FBMR OFFICIAL</span></div><h3 className="text-3xl md:text-4xl font-semibold tracking-[-.04em]">{x.name}</h3><p className="mt-4 text-sm leading-6 text-white/50">{x.description||"Official FBMR listing."}</p>{x.features?.length?<ul className="mt-5 flex flex-wrap gap-2">{x.features.slice(0,4).map(f=><li key={f} className="rounded-full border border-white/10 px-3 py-1 text-[8px] text-white/45">{f}</li>)}</ul>:null}<div className="mt-7 flex items-center justify-between border-t border-white/10 pt-5"><span className="font-mono text-sm text-[#d4b56a]">{x.price||"CONTACT"}</span>{x.gamepassUrl&&x.status!=="sold-out"?<a href={x.gamepassUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-[9px] tracking-[.2em] text-white hover:text-[#d4b56a]">VIEW <ArrowUpRight size={14}/></a>:<span className="text-[9px] tracking-[.2em] text-white/25">INFORMATION</span>}</div></div></div></motion.article>)}</div>:<div className="mt-16 rounded-[2rem] border border-dashed border-[#d4b56a]/25 bg-[#0b0e0b] px-8 py-20 text-center"><ShoppingBag className="mx-auto mb-5 text-[#d4b56a]/50" size={30}/><h3 className="text-2xl">The Exchange is preparing.</h3><p className="mt-3 text-sm text-white/35">No store listings are currently published. Check back when the next official release is announced.</p></div>}
 <div className="mt-8 flex items-center justify-between text-[8px] tracking-[.2em] text-white/20"><span>FBMR / OFFICIAL EXCHANGE</span><span>CURATED · VERIFIED · OFFICIAL</span></div></div></section>
}
